"""Extension part 3 - final remaining decks."""


def extend3(NEW, lit, lit_list, adapt, adapt_list, fill, card, sc, t, bulk_literal):
    bulk_literal("animalSounds", [
        ("cock_a_doodle", 1, "Rooster crow", {"tr": "Horoz ötüşü", "de": "Hahn kräht", "es": "Canto del gallo", "fr": "Coq chante", "ru": "Петух кричит", "uk": "Півень кукурікає"}),
        ("cat_purr", 1, "Cat purr", {"tr": "Kedi mırıltısı", "de": "Katze schnurrt", "es": "Gato ronronea", "fr": "Chat ronronne", "ru": "Кошка мурлычет", "uk": "Кішка муркоче"}),
        ("dog_whine", 1, "Dog whine", {"tr": "Köpek inlemesi", "de": "Hund winselt", "es": "Perro gime", "fr": "Chien gémit", "ru": "Собака скулит", "uk": "Собака скулить"}),
        ("cat_hiss", 1, "Cat hiss", {"tr": "Kedi tıslaması", "de": "Katze faucht", "es": "Gato sisea", "fr": "Chat siffle", "ru": "Кошка шипит", "uk": "Кішка шипить"}),
        ("monkey_ooh", 1, "Monkey call", {"tr": "Maymun sesi", "de": "Affe schreit", "es": "Mono grita", "fr": "Singe crie", "ru": "Обезьяна кричит", "uk": "Мавпа кричить"}),
        ("donkey_bray", 1, "Donkey bray", {"tr": "Eşek anırması", "de": "Esel iaht", "es": "Burro rebuzna", "fr": "Âne braie", "ru": "Осёл иаёт", "uk": "Осел іає"}),
        ("camel_grunt", 1, "Camel grunt", {"tr": "Deve homurdanması", "de": "Kamel grunzt", "es": "Camello gruñe", "fr": "Chameau grogne", "ru": "Camel grunt", "uk": "Camel grunt"}),
        ("seal_bark", 1, "Seal bark", {"tr": "Fok havlaması", "de": "Robbe bellt", "es": "Foca ladra", "fr": "Phoque aboie", "ru": "Тюлень лает", "uk": "Тюлень гавкає"}),
        ("dolphin_click", 1, "Dolphin click", {"tr": "Yunus sesi", "de": "Delfin klickt", "es": "Delfín hace clic", "fr": "Dauphin clique", "ru": "Дельфин щёлкает", "uk": "Dolphin click"}),
        ("whale_song", 1, "Whale song", {"tr": "Balina şarkısı", "de": "Walgesang", "es": "Canto de ballena", "fr": "Chant de baleine", "ru": "Песня кита", "uk": "Пісня кita"}),
        ("cricket_chirp", 1, "Cricket chirp", {"tr": "Cırcır böceği", "de": "Grille zirpt", "es": "Grillo canta", "fr": "Grillon chante", "ru": "Сверчок стрекочет", "uk": "Cricket chirp"}),
        ("mosquito_buzz", 1, "Mosquito buzz", {"tr": "Sivrisinek vızıltısı", "de": "Mücke summt", "es": "Mosquito zumbido", "fr": "Moustique bourdonne", "ru": "Комар жужжит", "uk": "Mosquito buzz"}),
        ("fly_buzz", 1, "Fly buzz", {"tr": "Sinek vızıltısı", "de": "Fliege summt", "es": "Mosca zumbido", "fr": "Mouche bourdonne", "ru": "Муха жужжит", "uk": "Fly buzz"}),
        ("snake_rattle", 1, "Snake rattle", {"tr": "Yılan çıngırak", "de": "Klapperschlange", "es": "Serpiente de cascabel", "fr": "Serpent à sonnettes", "ru": "Гремучая змея", "uk": "Snake rattle"}),
        ("frog_croak", 1, "Frog croak", {"tr": "Kurbağa vıraklaması", "de": "Frosch quakt", "es": "Rana croa", "fr": "Grenouille coasse", "ru": "Лягушка квакает", "uk": "Frog croak"}),
        ("owl_hoot_s", 1, "Owl hoot", {"tr": "Baykuş ötüşü", "de": "Eule ruft", "es": "Búho ulula", "fr": "Hibou hulule", "ru": "Сова ухает", "uk": "Owl hoot"}),
        ("peacock_call", 1, "Peacock call", {"tr": "Tavus kuşu", "de": "Pfau schreit", "es": "Pavo real grita", "fr": "Paon crie", "ru": "Peacock call", "uk": "Peacock call"}),
        ("wolf_pack", 1, "Wolf pack howl", {"tr": "Kurt sürüsü uluması", "de": "Wolfsrudel heult", "es": "Manada de lobos aúlla", "fr": "Meute hurle", "ru": "Wolf pack howl", "uk": "Wolf pack howl"}),
        ("hyena_laugh", 1, "Hyena laugh", {"tr": "Sırtlan kahkaha", "de": "Hyäne lacht", "es": "Hiena ríe", "fr": "Hyène rit", "ru": "Hyena laugh", "uk": "Hyena laugh"}),
        ("parrot_talk", 1, "Parrot talk", {"tr": "Papağan konuşması", "de": "Papagei spricht", "es": "Loro habla", "fr": "Perroquet parle", "ru": "Parrot talk", "uk": "Parrot talk"}),
        ("penguin_call", 1, "Penguin call", {"tr": "Penguen sesi", "de": "Pinguin ruft", "es": "Pingüino grita", "fr": "Pingouin crie", "ru": "Penguin call", "uk": "Penguin call"}),
        ("bat_squeak", 1, "Bat squeak", {"tr": "Yarasa cıyaklaması", "de": "Fledermaus quietscht", "es": "Murciélago chilla", "fr": "Chauve-souris grince", "ru": "Bat squeak", "uk": "Bat squeak"}),
        ("mouse_squeak_s", 1, "Mouse squeak", {"tr": "Fare ciyaklaması", "de": "Maus quietscht", "es": "Ratón chilla", "fr": "Souris couine", "ru": "Мышь пищит", "uk": "Mouse squeak"}),
        ("rabbit_thump", 1, "Rabbit thump", {"tr": "Tavşan vurması", "de": "Hase trommelt", "es": "Conejo golpea", "fr": "Lapin tambourine", "ru": "Rabbit thump", "uk": "Rabbit thump"}),
        ("horse_whinny", 1, "Horse whinny", {"tr": "At kişnemesi", "de": "Pferd wiehert", "es": "Caballo relincha", "fr": "Cheval hennit", "ru": "Лошадь ржёт", "uk": "Horse whinny"}),
        ("pig_squeal", 1, "Pig squeal", {"tr": "Domuz ciyaklaması", "de": "Schwein quiekt", "es": "Cerdo chilla", "fr": "Cochon crie", "ru": "Свинья визжит", "uk": "Pig squeal"}),
        ("goat_bleat_s", 1, "Goat bleat", {"tr": "Keçi melemesi", "de": "Ziege meckert", "es": "Cabra bala", "fr": "Chèvre bêle", "ru": "Коза блеет", "uk": "Goat bleat"}),
        ("sheep_baa", 1, "Sheep baa", {"tr": "Koyun melemesi", "de": "Schaf blökt", "es": "Oveja bala", "fr": "Mouton bêle", "ru": "Овца блеет", "uk": "Sheep baa"}),
        ("chicken_cluck_s", 1, "Hen cluck", {"tr": "Tavuk gıdaklaması", "de": "Henne gackert", "es": "Gallina cacarea", "fr": "Poule caquette", "ru": "Курица кудахчет", "uk": "Hen cluck"}),
        ("duck_quack_s", 1, "Duck quack", {"tr": "Ördek vaklaması", "de": "Ente quakt", "es": "Pato grazna", "fr": "Canard cancane", "ru": "Утка крякает", "uk": "Duck quack"}),
        ("goose_honk", 1, "Goose honk", {"tr": "Kaz vaklaması", "de": "Gans schnattert", "es": "Ganso grazna", "fr": "Oie cacarde", "ru": "Goose honk", "uk": "Goose honk"}),
        ("elephant_trumpet_s", 1, "Elephant trumpet", {"tr": "Fil borusu", "de": "Elefant trompetet", "es": "Elefante barrita", "fr": "Éléphant barrit", "ru": "Слон трубит", "uk": "Elephant trumpet"}),
        ("lion_roar_s", 1, "Lion roar", {"tr": "Aslan kükremesi", "de": "Löwe brüllt", "es": "León ruge", "fr": "Lion rugit", "ru": "Лев рычит", "uk": "Lion roar"}),
        ("tiger_roar", 1, "Tiger roar", {"tr": "Kaplan kükremesi", "de": "Tiger brüllt", "es": "Tigre ruge", "fr": "Tigre rugit", "ru": "Tiger roar", "uk": "Tiger roar"}),
        ("bear_growl_s", 1, "Bear growl", {"tr": "Ayı homurdanması", "de": "Bär knurrt", "es": "Oso gruñe", "fr": "Ours grogne", "ru": "Медведь рычит", "uk": "Bear growl"}),
        ("cow_moo_s", 1, "Cow moo", {"tr": "İnek mölemesi", "de": "Kuh muht", "es": "Vaca mue", "fr": "Vache meugle", "ru": "Корова мычит", "uk": "Cow moo"}),
        ("cat_meow_s", 1, "Cat meow", {"tr": "Kedi miyavlaması", "de": "Katze miaut", "es": "Gato maúlla", "fr": "Chat miaule", "ru": "Кошка мяукает", "uk": "Cat meow"}),
        ("dog_bark_s", 1, "Dog bark", {"tr": "Köpek havlaması", "de": "Hund bellt", "es": "Perro ladra", "fr": "Chien aboie", "ru": "Собака лает", "uk": "Dog bark"}),
        ("baby_cry_animal", 1, "Baby bird chirp", {"tr": "Yavru kuş ciyaklaması", "de": "Küken piept", "es": "Pollito pía", "fr": "Oisillon pépie", "ru": "Baby bird chirp", "uk": "Baby bird chirp"}),
        ("bee_buzz_s", 1, "Bee buzz", {"tr": "Arı vızıltısı", "de": "Biene summt", "es": "Abeja zumba", "fr": "Abeille bourdonne", "ru": "Пчела жужжит", "uk": "Bee buzz"}),
        ("crow_caw_s", 1, "Crow caw", {"tr": "Karga gaklaması", "de": "Krähe krächzt", "es": "Cuervo grazna", "fr": "Corbeau croasse", "ru": "Ворона каркает", "uk": "Crow caw"}),
    ])

    bulk_literal("fruits", [
        ("blueberry", 1, "Blueberry", {"tr": "Yaban mersini", "de": "Heidelbeere", "es": "Arándano", "fr": "Myrtille", "ru": "Черника", "uk": "Чорниця"}),
        ("raspberry", 1, "Raspberry", {"tr": "Ahududu", "de": "Himbeere", "es": "Frambuesa", "fr": "Framboise", "ru": "Малина", "uk": "Малина"}),
        ("blackberry", 1, "Blackberry", {"tr": "Böğürtlen", "de": "Brombeere", "es": "Mora", "fr": "Mûre", "ru": "Ежевика", "uk": "Ожина"}),
        ("plum", 1, "Plum", {"tr": "Erik", "de": "Pflaume", "es": "Ciruela", "fr": "Prune", "ru": "Слива", "uk": "Слива"}),
        ("apricot", 1, "Apricot", {"tr": "Kayısı", "de": "Aprikose", "es": "Albaricoque", "fr": "Abricot", "ru": "Абрикос", "uk": "Абрикос"}),
        ("fig", 1, "Fig", {"tr": "İncir", "de": "Feige", "es": "Higo", "fr": "Figue", "ru": "Инжир", "uk": "Інжир"}),
        ("pomegranate", 1, "Pomegranate", {"tr": "Nar", "de": "Granatapfel", "es": "Granada", "fr": "Grenade", "ru": "Гранат", "uk": "Гранат"}),
        ("melon", 1, "Melon", {"tr": "Kavun", "de": "Melone", "es": "Melón", "fr": "Melon", "ru": "Дыня", "uk": "Диня"}),
        ("papaya", 1, "Papaya", {"tr": "Papaya", "de": "Papaya", "es": "Papaya", "fr": "Papaye", "ru": "Папайя", "uk": "Папайя"}),
        ("guava", 1, "Guava", {"tr": "Guava", "de": "Guave", "es": "Guayaba", "fr": "Goyave", "ru": "Guava", "uk": "Guava"}),
        ("dragon_fruit", 1, "Dragon fruit", {"tr": "Ejder meyvesi", "de": "Drachenfrucht", "es": "Pitaya", "fr": "Fruit du dragon", "ru": "Dragon fruit", "uk": "Dragon fruit"}),
        ("passion_fruit", 1, "Passion fruit", {"tr": "Passion fruit", "de": "Passionsfrucht", "es": "Maracuyá", "fr": "Fruit de la passion", "ru": "Passion fruit", "uk": "Passion fruit"}),
        ("lychee", 2, "Lychee", {"tr": "Liçi", "de": "Litschi", "es": "Lichi", "fr": "Litchi", "ru": "Lychee", "uk": "Lychee"}),
        ("avocado", 1, "Avocado", {"tr": "Avokado", "de": "Avocado", "es": "Aguacate", "fr": "Avocat", "ru": "Авокадо", "uk": "Авокадо"}),
        ("olive", 1, "Olive", {"tr": "Zeytin", "de": "Olive", "es": "Aceituna", "fr": "Olive", "ru": "Оливка", "uk": "Оливка"}),
        ("corn", 1, "Corn", {"tr": "Mısır", "de": "Mais", "es": "Maíz", "fr": "Maïs", "ru": "Кукуруза", "uk": "Кукурудза"}),
        ("pepper_veg", 1, "Bell pepper", {"tr": "Dolmalık biber", "de": "Paprika", "es": "Pimiento", "fr": "Poivron", "ru": "Перец", "uk": "Перець"}),
        ("lettuce", 1, "Lettuce", {"tr": "Marul", "de": "Salat", "es": "Lechuga", "fr": "Laitue", "ru": "Салат", "uk": "Салат"}),
        ("spinach", 1, "Spinach", {"tr": "Ispanak", "de": "Spinat", "es": "Espinaca", "fr": "Épinard", "ru": "Шpinat", "uk": "Шpinach"}),
        ("cauliflower", 1, "Cauliflower", {"tr": "Karnabahar", "de": "Blumenkohl", "es": "Coliflor", "fr": "Chou-fleur", "ru": "Цветная капуста", "uk": "Цвітна капуста"}),
        ("cabbage", 1, "Cabbage", {"tr": "Lahana", "de": "Kohl", "es": "Repollo", "fr": "Chou", "ru": "Капуста", "uk": "Капуста"}),
        ("eggplant", 1, "Eggplant", {"tr": "Patlıcan", "de": "Aubergine", "es": "Berenjena", "fr": "Aubergine", "ru": "Баклажан", "uk": "Баклажан"}),
        ("zucchini", 1, "Zucchini", {"tr": "Kabak", "de": "Zucchini", "es": "Calabacín", "fr": "Courgette", "ru": "Кабачок", "uk": "Кабачок"}),
        ("pumpkin", 1, "Pumpkin", {"tr": "Balkabağı", "de": "Kürbis", "es": "Calabaza", "fr": "Citrouille", "ru": "Тыква", "uk": "Гарбуз"}),
        ("garlic", 1, "Garlic", {"tr": "Sarımsak", "de": "Knoblauch", "es": "Ajo", "fr": "Ail", "ru": "Чеснок", "uk": "Часник"}),
        ("ginger", 1, "Ginger", {"tr": "Zencefil", "de": "Ingwer", "es": "Jengibre", "fr": "Gingembre", "ru": "Имбирь", "uk": "Імбир"}),
        ("mushroom", 1, "Mushroom", {"tr": "Mantar", "de": "Pilz", "es": "Champiñón", "fr": "Champignon", "ru": "Гриб", "uk": "Гриб"}),
        ("peanut", 1, "Peanut", {"tr": "Fıstık", "de": "Erdnuss", "es": "Cacahuete", "fr": "Cacahuète", "ru": "Арахис", "uk": "Арахіс"}),
        ("almond", 1, "Almond", {"tr": "Badem", "de": "Mandel", "es": "Almendra", "fr": "Amande", "ru": "Миндаль", "uk": "Мigдаль"}),
        ("walnut", 1, "Walnut", {"tr": "Ceviz", "de": "Walnuss", "es": "Nuez", "fr": "Noix", "ru": "Грецкий орех", "uk": "Горіх"}),
        ("hazelnut", 1, "Hazelnut", {"tr": "Fındık", "de": "Haselnuss", "es": "Avellana", "fr": "Noisette", "ru": "Фундук", "uk": "Фундук"}),
        ("pistachio", 1, "Pistachio", {"tr": "Antep fıstığı", "de": "Pistazie", "es": "Pistacho", "fr": "Pistache", "ru": "Фисташка", "uk": "Фістashka"}),
        ("cashew", 1, "Cashew", {"tr": "Kaju", "de": "Cashew", "es": "Anacardo", "fr": "Noix de cajou", "ru": "Cashew", "uk": "Cashew"}),
        ("date_fruit", 1, "Date", {"tr": "Hurma", "de": "Dattel", "es": "Dátil", "fr": "Datte", "ru": "Финик", "uk": "Фінік"}),
        ("raisin", 1, "Raisin", {"tr": "Kuru üzüm", "de": "Rosine", "es": "Pasa", "fr": "Raisin sec", "ru": "Изюм", "uk": "Rodzynka"}),
        ("cranberry", 1, "Cranberry", {"tr": "Kızılcık", "de": "Cranberry", "es": "Arándano rojo", "fr": "Canneberge", "ru": "Cranberry", "uk": "Cranberry"}),
        ("grapefruit", 1, "Grapefruit", {"tr": "Greyfurt", "de": "Grapefruit", "es": "Pomelo", "fr": "Pamplemousse", "ru": "Грейпфрут", "uk": "Грейпфрут"}),
        ("tangerine", 1, "Tangerine", {"tr": "Mandalina", "de": "Mandarine", "es": "Mandarina", "fr": "Mandarine", "ru": "Мandarин", "uk": "Мandarин"}),
        ("lime_f", 1, "Lime", {"tr": "Misket limonu", "de": "Limette", "es": "Lima", "fr": "Citron vert", "ru": "Лайм", "uk": "Лайм"}),
        ("starfruit", 2, "Starfruit", {"tr": "Yıldız meyvesi", "de": "Sternfrucht", "es": "Carambola", "fr": "Carambole", "ru": "Starfruit", "uk": "Starfruit"}),
    ])

    bulk_literal("vehicles", [
        ("suv", 1, "SUV", {"tr": "SUV", "de": "SUV", "es": "SUV", "fr": "SUV", "ru": "SUV", "uk": "SUV"}),
        ("van", 1, "Van", {"tr": "Minibüs", "de": "Van", "es": "Furgoneta", "fr": "Fourgonnette", "ru": "Фургон", "uk": "Фургон"}),
        ("pickup", 1, "Pickup truck", {"tr": "Kamyonet", "de": "Pick-up", "es": "Camioneta", "fr": "Pick-up", "ru": "Пикап", "uk": "Пікап"}),
        ("limousine", 1, "Limousine", {"tr": "Limuzin", "de": "Limousine", "es": "Limusina", "fr": "Limousine", "ru": "Лимузин", "uk": "Лімузин"}),
        ("convertible", 1, "Convertible", {"tr": "Cabrio", "de": "Cabrio", "es": "Descapotable", "fr": "Cabriolet", "ru": "Кабриолет", "uk": "Кабріолет"}),
        ("sports_car", 1, "Sports car", {"tr": "Spor araba", "de": "Sportwagen", "es": "Coche deportivo", "fr": "Voiture de sport", "ru": "Спорткар", "uk": "Спорткар"}),
        ("electric_car", 1, "Electric car", {"tr": "Elektrikli araba", "de": "Elektroauto", "es": "Coche eléctrico", "fr": "Voiture électrique", "ru": "Электромобиль", "uk": "Електромобіль"}),
        ("hybrid_car", 2, "Hybrid car", {"tr": "Hibrit araba", "de": "Hybridauto", "es": "Coche híbrido", "fr": "Voiture hybride", "ru": "Гибрид", "uk": "Гібрид"}),
        ("race_car", 1, "Race car", {"tr": "Yarış arabası", "de": "Rennwagen", "es": "Coche de carreras", "fr": "Voiture de course", "ru": "Гоночный автомобиль", "uk": "Гоночний автомобіль"}),
        ("formula_one", 2, "Formula 1 car", {"tr": "Formula 1 aracı", "de": "Formel-1-Wagen", "es": "Fórmula 1", "fr": "Formule 1", "ru": "Формула-1", "uk": "Формула-1"}),
        ("monster_truck", 1, "Monster truck", {"tr": "Canavar kamyon", "de": "Monstertruck", "es": "Monster truck", "fr": "Monster truck", "ru": "Monster truck", "uk": "Monster truck"}),
        ("garbage_truck", 1, "Garbage truck", {"tr": "Çöp kamyonu", "de": "Müllwagen", "es": "Camión de basura", "fr": "Camion poubelle", "ru": "Мусоровоз", "uk": "Мусоровоз"}),
        ("delivery_truck", 1, "Delivery truck", {"tr": "Kargo kamyonu", "de": "Lieferwagen", "es": "Camión de reparto", "fr": "Camion de livraison", "ru": "Грузовик доставки", "uk": "Вантажівка доставки"}),
        ("school_bus_v", 1, "School bus", {"tr": "Okul servisi", "de": "Schulbus", "es": "Autobús escolar", "fr": "Bus scolaire", "ru": "Школьный автобус", "uk": "Шкільний автобус"}),
        ("double_decker", 1, "Double-decker bus", {"tr": "Çift katlı otobüs", "de": "Doppeldeckerbus", "es": "Autobús de dos pisos", "fr": "Bus à impériale", "ru": "Двухэтажный автобус", "uk": "Двоповерховий автобус"}),
        ("tram", 1, "Tram", {"tr": "Tramvay", "de": "Straßenbahn", "es": "Tranvía", "fr": "Tramway", "ru": "Трамвай", "uk": "Трамвай"}),
        ("monorail", 2, "Monorail", {"tr": "Monoray", "de": "Einschienenbahn", "es": "Monorriel", "fr": "Monorail", "ru": "Monorail", "uk": "Monorail"}),
        ("bullet_train", 1, "Bullet train", {"tr": "Hızlı tren", "de": "Hochgeschwindigkeitszug", "es": "Tren bala", "fr": "Train à grande vitesse", "ru": "Скоростной поезд", "uk": "Швидкісний поїзд"}),
        ("freight_train", 1, "Freight train", {"tr": "Yük treni", "de": "Güterzug", "es": "Tren de carga", "fr": "Train de marchandises", "ru": "Грузовой поезд", "uk": "Вантажний поїзд"}),
        ("sailboat", 1, "Sailboat", {"tr": "Yelkenli", "de": "Segelboot", "es": "Velero", "fr": "Voilier", "ru": "Парусник", "uk": "Вітрильник"}),
        ("yacht", 1, "Yacht", {"tr": "Yat", "de": "Yacht", "es": "Yate", "fr": "Yacht", "ru": "Яхта", "uk": "Яхта"}),
        ("cruise_ship", 1, "Cruise ship", {"tr": "Gemi turu", "de": "Kreuzfahrtschiff", "es": "Crucero", "fr": "Paquebot", "ru": "Круизный лайнер", "uk": "Круїзний лайнер"}),
        ("submarine_v", 1, "Submarine", {"tr": "Denizaltı", "de": "U-Boot", "es": "Submarino", "fr": "Sous-marin", "ru": "Подлодка", "uk": "Підводний човен"}),
        ("canoe_v", 1, "Canoe", {"tr": "Kano", "de": "Kanu", "es": "Canoa", "fr": "Canoë", "ru": "Каноэ", "uk": "Кanoe"}),
        ("kayak_v", 1, "Kayak", {"tr": "Kayak", "de": "Kajak", "es": "Kayak", "fr": "Kayak", "ru": "Кayak", "uk": "Кayak"}),
        ("jet_ski", 1, "Jet ski", {"tr": "Jet ski", "de": "Jet-Ski", "es": "Moto acuática", "fr": "Jet-ski", "ru": "Jet ski", "uk": "Jet ski"}),
        ("hang_glider", 2, "Hang glider", {"tr": "Yelken kanat", "de": "Hängegleiter", "es": "Ala delta", "fr": "Deltaplane", "ru": "Hang glider", "uk": "Hang glider"}),
        ("parachute_v", 1, "Parachute", {"tr": "Paraşüt", "de": "Fallschirm", "es": "Paracaídas", "fr": "Parachute", "ru": "Парашют", "uk": "Парашут"}),
        ("space_shuttle", 2, "Space shuttle", {"tr": "Uzay mekiği", "de": "Space Shuttle", "es": "Transbordador espacial", "fr": "Navette spatiale", "ru": "Space shuttle", "uk": "Space shuttle"}),
        ("satellite_v", 1, "Satellite", {"tr": "Uydu", "de": "Satellit", "es": "Satélite", "fr": "Satellite", "ru": "Спутник", "uk": "Супутник"}),
        ("segway", 2, "Segway", {"tr": "Segway", "de": "Segway", "es": "Segway", "fr": "Segway", "ru": "Segway", "uk": "Segway"}),
        ("unicycle", 2, "Unicycle", {"tr": "Tek tekerlekli bisiklet", "de": "Einrad", "es": "Monociclo", "fr": "Monocycle", "ru": "Unicycle", "uk": "Unicycle"}),
        ("golf_cart", 1, "Golf cart", {"tr": "Golf arabası", "de": "Golfwagen", "es": "Carrito de golf", "fr": "Voiturette de golf", "ru": "Golf cart", "uk": "Golf cart"}),
        ("snowmobile", 1, "Snowmobile", {"tr": "Kar aracı", "de": "Schneemobil", "es": "Moto de nieve", "fr": "Motoneige", "ru": "Snowmobile", "uk": "Snowmobile"}),
        ("sled", 1, "Sled", {"tr": "Kızak", "de": "Schlitten", "es": "Trineo", "fr": "Luge", "ru": "Сani", "uk": "Сani"}),
        ("wheelchair_v", 1, "Wheelchair", {"tr": "Tekerlekli sandalye", "de": "Rollstuhl", "es": "Silla de ruedas", "fr": "Fauteuil roulant", "ru": "Инвалидная коляска", "uk": "Інвалідна коляска"}),
        ("stroller_v", 1, "Stroller", {"tr": "Bebek arabası", "de": "Kinderwagen", "es": "Cochecito", "fr": "Poussette", "ru": "Коляска", "uk": "Коляска"}),
        ("forklift", 2, "Forklift", {"tr": "Forklift", "de": "Gabelstapler", "es": "Montacargas", "fr": "Chariot élévateur", "ru": "Погрузчик", "uk": "Нavantazhuvach"}),
        ("bulldozer", 1, "Bulldozer", {"tr": "Buldozer", "de": "Bulldozer", "es": "Bulldozer", "fr": "Bulldozer", "ru": "Bulldozer", "uk": "Bulldozer"}),
        ("excavator", 1, "Excavator", {"tr": "Ekskavatör", "de": "Bagger", "es": "Excavadora", "fr": "Excavatrice", "ru": "Excavator", "uk": "Excavator"}),
        ("crane_v", 1, "Crane", {"tr": "Vinç", "de": "Kran", "es": "Grúa", "fr": "Grue", "ru": "Кран", "uk": "Кран"}),
    ])

    NEW["football"] = adapt_list("fb", 21, [
        ("Corner flag", {"tr": "Korner bayrağı", "de": "Eckfahne", "es": "Bandera de córner", "fr": "Drapeau de corner", "ar": "Corner flag", "ru": "Угловой флаг", "uk": "Corner flag"}),
        ("Crossbar", {"tr": "Direk", "de": "Latte", "es": "Travesaño", "fr": "Barre transversale", "ar": "Crossbar", "ru": "Crossbar", "uk": "Crossbar"}),
        ("Goal net", {"tr": "Kale filesi", "de": "Tornetz", "es": "Red de la portería", "fr": "Filet de but", "ar": "Goal net", "ru": "Goal net", "uk": "Goal net"}),
        ("Substitute", {"tr": "Yedek oyuncu", "de": "Einwechselspieler", "es": "Suplente", "fr": "Remplaçant", "ar": "Substitute", "ru": "Substitute", "uk": "Substitute"}),
        ("Captain armband", {"tr": "Kaptanlık bandı", "de": "Kapitänsbinde", "es": "Brazalete de capitán", "fr": "Brassard de capitaine", "ar": "Captain armband", "ru": "Captain armband", "uk": "Captain armband"}),
        ("Penalty shootout", {"tr": "Penaltı atışları", "de": "Elfmeterschießen", "es": "Tanda de penaltis", "fr": "Tirs au but", "ar": "Penalty shootout", "ru": "Penalty shootout", "uk": "Penalty shootout"}),
        ("Free kick wall", {"tr": "Baraj", "de": "Mauer", "es": "Barrera", "fr": "Mur", "ar": "Free kick wall", "ru": "Free kick wall", "uk": "Free kick wall"}),
        ("Slide tackle", {"tr": "Kayarak müdahale", "de": "Grätsche", "es": "Entrada", "fr": "Tacle glissé", "ar": "Slide tackle", "ru": "Slide tackle", "uk": "Slide tackle"}),
        ("Nut meg", {"tr": "Bacak arası", "de": "Beinschuss", "es": "Caño", "fr": "Petit pont", "ar": "Nut meg", "ru": "Nut meg", "uk": "Nut meg"}),
        ("Bicycle kick", {"tr": "Rabona / bisiklet", "de": "Fallrückzieher", "es": "Chilena", "fr": "Retourné acrobatique", "ar": "Bicycle kick", "ru": "Bicycle kick", "uk": "Bicycle kick"}),
        ("Golden Boot", {"tr": "Altın Ayakkabı", "de": "Goldener Schuh", "es": "Bota de Oro", "fr": "Soulier d'or", "ar": "Golden Boot", "ru": "Golden Boot", "uk": "Golden Boot"}),
        ("Europa League", {"tr": "Avrupa Ligi", "de": "Europa League", "es": "Europa League", "fr": "Ligue Europa", "ar": "Europa League", "ru": "Europa League", "uk": "Europa League"}),
        ("Super Cup", {"tr": "Süper Kupa", "de": "Superpokal", "es": "Supercopa", "fr": "Supercoupe", "ar": "Super Cup", "ru": "Super Cup", "uk": "Super Cup"}),
        ("Derby match", {"tr": "Derbi", "de": "Derby", "es": "Derbi", "fr": "Derby", "ar": "Derby match", "ru": "Derby match", "uk": "Derby match"}),
        ("Extra time", {"tr": "Uzatma", "de": "Verlängerung", "es": "Prórroga", "fr": "Prolongations", "ar": "Extra time", "ru": "Extra time", "uk": "Extra time"}),
        ("Stoppage time", {"tr": "Uzatma dakikası", "de": "Nachspielzeit", "es": "Tiempo añadido", "fr": "Temps additionnel", "ar": "Stoppage time", "ru": "Stoppage time", "uk": "Stoppage time"}),
        ("Clean sheet", {"tr": "Gol yememe", "de": "Zu-Null-Spiel", "es": "Portería a cero", "fr": "Clean sheet", "ar": "Clean sheet", "ru": "Clean sheet", "uk": "Clean sheet"}),
        ("Assist", {"tr": "Asist", "de": "Vorlage", "es": "Asistencia", "fr": "Passe décisive", "ar": "Assist", "ru": "Assist", "uk": "Assist"}),
        ("Through ball", {"tr": "Ara pas", "de": "Steilpass", "es": "Pase filtrado", "fr": "Passe en profondeur", "ar": "Through ball", "ru": "Through ball", "uk": "Through ball"}),
        ("Cross", {"tr": "Orta", "de": "Flanke", "es": "Centro", "fr": "Centre", "ar": "Cross", "ru": "Cross", "uk": "Cross"}),
        ("Volley", {"tr": "Vole", "de": "Volley", "es": "Volea", "fr": "Volée", "ar": "Volley", "ru": "Volley", "uk": "Volley"}),
        ("Chip shot", {"tr": "Aşırtma", "de": "Lob", "es": "Vaselina", "fr": "Lob", "ar": "Chip shot", "ru": "Chip shot", "uk": "Chip shot"}),
        ("Tackle", {"tr": "Müdahale", "de": "Tackling", "es": "Entrada", "fr": "Tacle", "ar": "Tackle", "ru": "Tackle", "uk": "Tackle"}),
        ("Save", {"tr": "Kurtarış", "de": "Parade", "es": "Parada", "fr": "Arrêt", "ar": "Save", "ru": "Save", "uk": "Save"}),
        ("Referee whistle", {"tr": "Hakem düdüğü", "de": "Schiedsrichter pfeift", "es": "Silbato del árbitro", "fr": "Sifflet de l'arbitre", "ar": "Referee whistle", "ru": "Referee whistle", "uk": "Referee whistle"}),
        ("Fourth official", {"tr": "Dördüncü hakem", "de": "Vierter Offizieller", "es": "Cuarto árbitro", "fr": "Quatrième arbitre", "ar": "Fourth official", "ru": "Fourth official", "uk": "Fourth official"}),
        ("Fan scarf", {"tr": "Taraftar atkısı", "de": "Fan-Schal", "es": "Bufanda de aficionado", "fr": "Écharpe de supporter", "ar": "Fan scarf", "ru": "Fan scarf", "uk": "Fan scarf"}),
        ("Pitch invasion", {"tr": "Saha invasion", "de": "Platzsturm", "es": "Invasión de campo", "fr": "Invasion de terrain", "ar": "Pitch invasion", "ru": "Pitch invasion", "uk": "Pitch invasion"}),
        ("Training cone", {"tr": "Antrenman hunisi", "de": "Trainingskegel", "es": "Cono de entrenamiento", "fr": "Cône d'entraînement", "ar": "Training cone", "ru": "Training cone", "uk": "Training cone"}),
        ("Shin guards", {"tr": "Tekmelik", "de": "Schienbeinschoner", "es": "Espinilleras", "fr": "Protège-tibias", "ar": "Shin guards", "ru": "Shin guards", "uk": "Shin guards"}),
        ("Captain's speech", {"tr": "Kaptan konuşması", "de": "Kapitänsrede", "es": "Discurso del capitán", "fr": "Discours du capitaine", "ar": "Captain's speech", "ru": "Captain's speech", "uk": "Captain's speech"}),
        ("Tunnel walk", {"tr": "Tünel yürüyüşü", "de": "Tunnelgang", "es": "Salida al campo", "fr": "Sortie du tunnel", "ar": "Tunnel walk", "ru": "Tunnel walk", "uk": "Tunnel walk"}),
        ("Ball boy", {"tr": "Top çocuğu", "de": "Balljunge", "es": "Recogepelotas", "fr": "Ramasseur de balles", "ar": "Ball boy", "ru": "Ball boy", "uk": "Ball boy"}),
        ("Goal celebration", {"tr": "Gol sevinci", "de": "Torjubel", "es": "Celebración de gol", "fr": "Célébration de but", "ar": "Goal celebration", "ru": "Goal celebration", "uk": "Goal celebration"}),
        ("Manager", {"tr": "Teknik direktör", "de": "Trainer", "es": "Entrenador", "fr": "Entraîneur", "ar": "Manager", "ru": "Manager", "uk": "Manager"}),
        ("Transfer window", {"tr": "Transfer dönemi", "de": "Transferfenster", "es": "Mercado de fichajes", "fr": "Mercato", "ar": "Transfer window", "ru": "Transfer window", "uk": "Transfer window"}),
        ("Youth academy", {"tr": "Altyapı", "de": "Jugendakademie", "es": "Cantera", "fr": "Centre de formation", "ar": "Youth academy", "ru": "Youth academy", "uk": "Youth academy"}),
        ("Trophy lift", {"tr": "Kupa kaldırma", "de": "Pokal heben", "es": "Levantar el trofeo", "fr": "Soulever le trophée", "ar": "Trophy lift", "ru": "Trophy lift", "uk": "Trophy lift"}),
        ("National anthem", {"tr": "Milli marş", "de": "Nationalhymne", "es": "Himno nacional", "fr": "Hymne national", "ar": "National anthem", "ru": "National anthem", "uk": "National anthem"}),
        ("Fan chant", {"tr": "Taraftar tezahüratı", "de": "Fan-Gesang", "es": "Cántico de aficionados", "fr": "Chant de supporters", "ar": "Fan chant", "ru": "Fan chant", "uk": "Fan chant"}),
        ("Wall pass", {"tr": "Duvar pası", "de": "Doppelpass", "es": "Pared", "fr": "Une-deux", "ar": "Wall pass", "ru": "Wall pass", "uk": "Wall pass"}),
    ])

    # basketball, olympics, combat, extreme, fitness - literal
    bulk_literal("basketball", [
        ("dunk_s", 1, "Slam dunk", {"tr": "Smaç", "de": "Dunk", "es": "Mate", "fr": "Dunk", "ru": "Дunk", "uk": "Дunk"}),
        ("layup", 1, "Layup", {"tr": "Turnike", "de": "Lay-up", "es": "Bandeja", "fr": "Lay-up", "ru": "Layup", "uk": "Layup"}),
        ("fadeaway", 2, "Fadeaway shot", {"tr": "Fadeaway", "de": "Fadeaway", "es": "Fadeaway", "fr": "Fadeaway", "ru": "Fadeaway", "uk": "Fadeaway"}),
        ("crossover", 1, "Crossover dribble", {"tr": "Crossover", "de": "Crossover", "es": "Crossover", "fr": "Crossover", "ru": "Crossover", "uk": "Crossover"}),
        ("pick_and_roll", 2, "Pick and roll", {"tr": "Pick and roll", "de": "Pick and Roll", "es": "Pick and roll", "fr": "Pick and roll", "ru": "Pick and roll", "uk": "Pick and roll"}),
        ("fast_break", 1, "Fast break", {"tr": "Hızlı hücum", "de": "Fast Break", "es": "Contraataque", "fr": "Contre-attaque", "ru": "Fast break", "uk": "Fast break"}),
        ("full_court_press", 2, "Full court press", {"tr": "Full court press", "de": "Full-Court-Press", "es": "Presión a toda cancha", "fr": "Pressing", "ru": "Full court press", "uk": "Full court press"}),
        ("shot_clock", 1, "Shot clock", {"tr": "Atış saati", "de": "Shot Clock", "es": "Reloj de posesión", "fr": "Chrono des 24 secondes", "ru": "Shot clock", "uk": "Shot clock"}),
        ("technical_foul", 1, "Technical foul", {"tr": "Teknik faul", "de": "Technisches Foul", "es": "Falta técnica", "fr": "Faute technique", "ru": "Technical foul", "uk": "Technical foul"}),
        ("and_one", 1, "And-one", {"tr": "And-one", "de": "And-one", "es": "And-one", "fr": "And-one", "ru": "And-one", "uk": "And-one"}),
        ("giannis", 1, "Giannis Antetokounmpo", {"tr": "Giannis Antetokounmpo", "de": "Giannis Antetokounmpo", "es": "Giannis Antetokounmpo", "fr": "Giannis Antetokounmpo", "ru": "Giannis Antetokounmpo", "uk": "Giannis Antetokounmpo"}),
        ("kobe", 1, "Kobe Bryant", {"tr": "Kobe Bryant", "de": "Kobe Bryant", "es": "Kobe Bryant", "fr": "Kobe Bryant", "ru": "Kobe Bryant", "uk": "Kobe Bryant"}),
        ("shaq", 1, "Shaquille O'Neal", {"tr": "Shaquille O'Neal", "de": "Shaquille O'Neal", "es": "Shaquille O'Neal", "fr": "Shaquille O'Neal", "ru": "Shaquille O'Neal", "uk": "Shaquille O'Neal"}),
        ("durant", 1, "Kevin Durant", {"tr": "Kevin Durant", "de": "Kevin Durant", "es": "Kevin Durant", "fr": "Kevin Durant", "ru": "Kevin Durant", "uk": "Kevin Durant"}),
        ("luka", 1, "Luka Dončić", {"tr": "Luka Dončić", "de": "Luka Dončić", "es": "Luka Dončić", "fr": "Luka Dončić", "ru": "Luka Dončić", "uk": "Luka Dončić"}),
        ("jokic", 1, "Nikola Jokić", {"tr": "Nikola Jokić", "de": "Nikola Jokić", "es": "Nikola Jokić", "fr": "Nikola Jokić", "ru": "Nikola Jokić", "uk": "Nikola Jokić"}),
        ("tatum", 1, "Jayson Tatum", {"tr": "Jayson Tatum", "de": "Jayson Tatum", "es": "Jayson Tatum", "fr": "Jayson Tatum", "ru": "Jayson Tatum", "uk": "Jayson Tatum"}),
        ("wnba", 1, "WNBA", {"tr": "WNBA", "de": "WNBA", "es": "WNBA", "fr": "WNBA", "ru": "WNBA", "uk": "WNBA"}),
        ("streetball", 1, "Streetball", {"tr": "Sokak basketbolu", "de": "Streetball", "es": "Streetball", "fr": "Streetball", "ru": "Streetball", "uk": "Streetball"}),
        ("three_point_contest", 1, "Three-point contest", {"tr": "Üçlük yarışması", "de": "Dreierwettbewerb", "es": "Concurso de triples", "fr": "Concours à 3 points", "ru": "Three-point contest", "uk": "Three-point contest"}),
        ("coach_timeout", 1, "Coach timeout", {"tr": "Mola", "de": "Auszeit", "es": "Tiempo muerto", "fr": "Temps mort", "ru": "Coach timeout", "uk": "Coach timeout"}),
        ("jump_ball", 1, "Jump ball", {"tr": "Hava atışı", "de": "Sprungball", "es": "Salto entre dos", "fr": "Engagement", "ru": "Jump ball", "uk": "Jump ball"}),
        ("euroleague", 1, "EuroLeague", {"tr": "EuroLeague", "de": "EuroLeague", "es": "Euroliga", "fr": "Euroligue", "ru": "EuroLeague", "uk": "EuroLeague"}),
        ("backboard", 1, "Backboard", {"tr": "Pano", "de": "Backboard", "es": "Tablero", "fr": "Panneau", "ru": "Backboard", "uk": "Backboard"}),
        ("swish", 1, "Swish", {"tr": "Swish", "de": "Swish", "es": "Swish", "fr": "Swish", "ru": "Swish", "uk": "Swish"}),
        ("air_ball", 1, "Air ball", {"tr": "Hava topu", "de": "Airball", "es": "Air ball", "fr": "Air ball", "ru": "Air ball", "uk": "Air ball"}),
        ("traveling", 1, "Traveling violation", {"tr": "Yürüme", "de": "Lauf-Schritt", "es": "Pasos", "fr": "Marcher", "ru": "Traveling", "uk": "Traveling"}),
        ("double_dribble", 1, "Double dribble", {"tr": "Çift dribling", "de": "Doppel dribbeln", "es": "Doble regate", "fr": "Double dribble", "ru": "Double dribble", "uk": "Double dribble"}),
        ("charge", 1, "Charging foul", {"tr": "Hücum faulü", "de": "Offensivfoul", "es": "Carga", "fr": "Charge", "ru": "Charge", "uk": "Charge"}),
        ("steal", 1, "Steal", {"tr": "Top çalma", "de": "Steal", "es": "Robo", "fr": "Interception", "ru": "Steal", "uk": "Steal"}),
        ("turnover", 1, "Turnover", {"tr": "Top kaybı", "de": "Turnover", "es": "Pérdida", "fr": "Turnover", "ru": "Turnover", "uk": "Turnover"}),
        ("box_out", 1, "Box out", {"tr": "Box out", "de": "Box out", "es": "Box out", "fr": "Box out", "ru": "Box out", "uk": "Box out"}),
        ("post_up", 1, "Post up", {"tr": "Post oyunu", "de": "Post-up", "es": "Juego de poste", "fr": "Post-up", "ru": "Post up", "uk": "Post up"}),
        ("no_look_pass", 2, "No-look pass", {"tr": "Bakmadan pas", "de": "No-look Pass", "es": "Pase sin mirar", "fr": "Passe sans regarder", "ru": "No-look pass", "uk": "No-look pass"}),
        ("behind_back", 2, "Behind-the-back pass", {"tr": "Sırt pası", "de": "Rückwärtspass", "es": "Pase por detrás", "fr": "Passe dans le dos", "ru": "Behind-the-back pass", "uk": "Behind-the-back pass"}),
        ("spin_move", 1, "Spin move", {"tr": "Dönerek geçiş", "de": "Spin Move", "es": "Giro", "fr": "Spin move", "ru": "Spin move", "uk": "Spin move"}),
        ("euro_step", 2, "Euro step", {"tr": "Euro step", "de": "Euro Step", "es": "Euro step", "fr": "Euro step", "ru": "Euro step", "uk": "Euro step"}),
        ("finger_roll", 2, "Finger roll", {"tr": "Finger roll", "de": "Finger Roll", "es": "Finger roll", "fr": "Finger roll", "ru": "Finger roll", "uk": "Finger roll"}),
        ("championship_ring", 1, "Championship ring", {"tr": "Şampiyonluk yüzüğü", "de": "Meisterschaftsring", "es": "Anillo de campeón", "fr": "Bague de champion", "ru": "Championship ring", "uk": "Championship ring"}),
        ("finals_mvp", 1, "Finals MVP", {"tr": "Final MVP", "de": "Finals MVP", "es": "MVP de las Finales", "fr": "MVP des finales", "ru": "Finals MVP", "uk": "Finals MVP"}),
        ("court_lines", 1, "Court lines", {"tr": "Saha çizgileri", "de": "Spielfeldlinien", "es": "Líneas de la cancha", "fr": "Lignes du terrain", "ru": "Court lines", "uk": "Court lines"}),
    ])

    # Remaining: olympics, combat, extreme, fitness, footballers, space, inventions, historyFigures, famousWomen, mythology, science, books, body
    from _build_all_decks_ext4 import extend4
    extend4(NEW, lit, lit_list, adapt, adapt_list, fill, card, sc, t, bulk_literal)
