"""Extension part 2 for remaining literal/adapt decks."""


def extend2(NEW, lit, lit_list, adapt, adapt_list, fill, card, sc, t):
    NEW["fairyTales"] = adapt_list("ft", 21, [
        ("Pinocchio", {"tr": "Pinokyo", "de": "Pinocchio", "es": "Pinocho", "fr": "Pinocchio", "ar": "بينوكيو", "ru": "Буратино", "uk": "Буратino"}),
        ("Aladdin", {"tr": "Alaaddin", "de": "Aladdin", "es": "Aladdín", "fr": "Aladdin", "ar": "علاء الدين", "ru": "Аладдин", "uk": "Аладдін"}),
        ("Ali Baba", {"tr": "Ali Baba", "de": "Ali Baba", "es": "Alí Babá", "fr": "Ali Baba", "ar": "علي بaba", "ru": "Ali Baba", "uk": "Ali Baba"}),
        ("Sinbad", {"tr": "Sindbad", "de": "Sindbad", "es": "Simbad", "fr": "Sindbad", "ar": "Sinbad", "ru": "Sinbad", "uk": "Sinbad"}),
        ("Rapunzel", {"tr": "Rapunzel", "de": "Rapunzel", "es": "Rapunzel", "fr": "Raiponce", "ar": "Rapunzel", "ru": "Рapunzel", "uk": "Рapunzel"}),
        ("Sleeping Beauty", {"tr": "Uyuyan Güzel", "de": "Dornröschen", "es": "La Bella Durmiente", "fr": "La Belle au bois dormant", "ar": "الجمال النائم", "ru": "Спящая красавица", "uk": "Спляча красуня"}),
        ("The Frog Prince", {"tr": "Kurbağa Prensi", "de": "Der Froschkönig", "es": "El príncipe rana", "fr": "Le Roi grenouille", "ar": "الأمير الضفدع", "ru": "Царевна-лягушка", "uk": "Царівна-жаба"}),
        ("Hansel and Gretel", {"tr": "Hansel ve Gretel", "de": "Hänsel und Gretel", "es": "Hansel y Gretel", "fr": "Hansel et Gretel", "ar": "Hansel and Gretel", "ru": "Hansel and Gretel", "uk": "Hansel and Gretel"}),
        ("Rumpelstiltskin", {"tr": "Tom Thumb", "de": "Rumpelstilzchen", "es": "Rumpelstiltskin", "fr": "Le Petit Poucet", "ar": "Rumpelstiltskin", "ru": "Rumpelstiltskin", "uk": "Rumpelstiltskin"}),
        ("The Ugly Duckling", {"tr": "Çirkin Ördek Yavrusu", "de": "Das hässliche Entlein", "es": "El patito feo", "fr": "Le Vilain Petit Canard", "ar": "The Ugly Duckling", "ru": "The Ugly Duckling", "uk": "The Ugly Duckling"}),
        ("The Emperor's New Clothes", {"tr": "Kralın Yeni Elbiseleri", "de": "Des Kaisers neue Kleider", "es": "El traje nuevo del emperador", "fr": "Les Habits neufs de l'empereur", "ar": "The Emperor's New Clothes", "ru": "The Emperor's New Clothes", "uk": "The Emperor's New Clothes"}),
        ("The Pied Piper", {"tr": "Flütçü", "de": "Der Rattenfänger", "es": "El flautista", "fr": "Le Joueur de flûte", "ar": "The Pied Piper", "ru": "The Pied Piper", "uk": "The Pied Piper"}),
        ("Jack and the Beanstalk", {"tr": "Jack ve Fasulye Sırığı", "de": "Hans und die Bohnenranke", "es": "Jack y las habichuelas mágicas", "fr": "Jack et le Haricot magique", "ar": "Jack and the Beanstalk", "ru": "Jack and the Beanstalk", "uk": "Jack and the Beanstalk"}),
        ("Goldilocks", {"tr": "Goldilocks", "de": "Goldilocks", "es": "Ricitos de oro", "fr": "Boucle d'Or", "ar": "Goldilocks", "ru": "Goldilocks", "uk": "Goldilocks"}),
        ("The Three Billy Goats Gruff", {"tr": "The Three Billy Goats Gruff", "de": "The Three Billy Goats Gruff", "es": "Los tres cabritos", "fr": "Les Trois Boucs", "ar": "The Three Billy Goats Gruff", "ru": "The Three Billy Goats Gruff", "uk": "The Three Billy Goats Gruff"}),
        ("The Princess and the Pea", {"tr": "The Princess and the Pea", "de": "Die Prinzessin auf der Erbse", "es": "La princesa y el guisante", "fr": "La Princesse au petit pois", "ar": "The Princess and the Pea", "ru": "The Princess and the Pea", "uk": "The Princess and the Pea"}),
        ("The Snow Queen", {"tr": "Kar Kraliçesi", "de": "Die Schneekönigin", "es": "La reina de las nieves", "fr": "La Reine des neiges", "ar": "The Snow Queen", "ru": "Сnezhnaya koroleva", "uk": "Снігова королева"}),
        ("The Little Match Girl", {"tr": "Kibritçi Kız", "de": "Das Mädchen mit den Schwefelhölzern", "es": "La vendedora de cerillas", "fr": "La Petite Match girl", "ar": "The Little Match Girl", "ru": "The Little Match Girl", "uk": "The Little Match Girl"}),
        ("Thumbelina", {"tr": "Tom Thumb", "de": "Däumelinchen", "es": "Pulgarcita", "fr": "La Poulette", "ar": "Thumbelina", "ru": "Thumbelina", "uk": "Thumbelina"}),
        ("The Steadfast Tin Soldier", {"tr": "The Steadfast Tin Soldier", "de": "Der standhafte Zinnsoldat", "es": "El soldadito de plomo", "fr": "Le Soldat de plomb", "ar": "The Steadfast Tin Soldier", "ru": "The Steadfast Tin Soldier", "uk": "The Steadfast Tin Soldier"}),
        ("The Nightingale", {"tr": "The Nightingale", "de": "Die Nachtigall", "es": "El ruiseñor", "fr": "Le Rossignol", "ar": "The Nightingale", "ru": "The Nightingale", "uk": "The Nightingale"}),
        ("The Wild Swans", {"tr": "The Wild Swans", "de": "Die wilden Schwäne", "es": "Los cisnes salvajes", "fr": "Les Cygnes sauvages", "ar": "The Wild Swans", "ru": "The Wild Swans", "uk": "The Wild Swans"}),
        ("The Twelve Dancing Princesses", {"tr": "The Twelve Dancing Princesses", "de": "Die zwölf tanzenden Prinzessinnen", "es": "Las doce princesas bailarinas", "fr": "Les Douze Princesses dansantes", "ar": "The Twelve Dancing Princesses", "ru": "The Twelve Dancing Princesses", "uk": "The Twelve Dancing Princesses"}),
        ("The Elves and the Shoemaker", {"tr": "The Elves and the Shoemaker", "de": "Die Wichtelmänner", "es": "Los duendecillos", "fr": "Les Lutins", "ar": "The Elves and the Shoemaker", "ru": "The Elves and the Shoemaker", "uk": "The Elves and the Shoemaker"}),
        ("The Fisherman and His Wife", {"tr": "The Fisherman and His Wife", "de": "Vom Fischer und seiner Frau", "es": "El pescador y su mujer", "fr": "Le Pêcheur et sa femme", "ar": "The Fisherman and His Wife", "ru": "The Fisherman and His Wife", "uk": "The Fisherman and His Wife"}),
        ("The Bremen Town Musicians", {"tr": "The Bremen Town Musicians", "de": "Die Bremer Stadtmusikanten", "es": "Los músicos de Bremen", "fr": "Les Musiciens de Brême", "ar": "The Bremen Town Musicians", "ru": "The Bremen Town Musicians", "uk": "The Bremen Town Musicians"}),
        ("The Brave Little Tailor", {"tr": "The Brave Little Tailor", "de": "Das tapfere Schneiderlein", "es": "El sastrecillo valiente", "fr": "Le Vaillant Petit Tailleur", "ar": "The Brave Little Tailor", "ru": "The Brave Little Tailor", "uk": "The Brave Little Tailor"}),
        ("The Golden Goose", {"tr": "The Golden Goose", "de": "Die goldene Gans", "es": "El ganso de oro", "fr": "L'Oie d'or", "ar": "The Golden Goose", "ru": "The Golden Goose", "uk": "The Golden Goose"}),
        ("The Magic Porridge Pot", {"tr": "The Magic Porridge Pot", "de": "Der süße Brei", "es": "La olla mágica", "fr": "La Marmite magique", "ar": "The Magic Porridge Pot", "ru": "The Magic Porridge Pot", "uk": "The Magic Porridge Pot"}),
        ("The Wolf and the Seven Kids", {"tr": "The Wolf and the Seven Kids", "de": "Der Wolf und die sieben Geißlein", "es": "El lobo y las siete cabritas", "fr": "Le Loup et les sept chevreaux", "ar": "The Wolf and the Seven Kids", "ru": "The Wolf and the Seven Kids", "uk": "The Wolf and the Seven Kids"}),
        ("The Town Mouse and the Country Mouse", {"tr": "The Town Mouse and the Country Mouse", "de": "Stadtmaus und Landmaus", "es": "El ratón de ciudad y el ratón de campo", "fr": "La Souris de ville et la Souris des champs", "ar": "The Town Mouse and the Country Mouse", "ru": "The Town Mouse and the Country Mouse", "uk": "The Town Mouse and the Country Mouse"}),
        ("The Ant and the Grasshopper", {"tr": "The Ant and the Grasshopper", "de": "Die Ameise und die Grille", "es": "La hormiga y la cigarra", "fr": "La Cigale et la Fourmi", "ar": "The Ant and the Grasshopper", "ru": "The Ant and the Grasshopper", "uk": "The Ant and the Grasshopper"}),
        ("The Boy Who Cried Wolf", {"tr": "The Boy Who Cried Wolf", "de": "Der Junge, der Wolf rief", "es": "El pastorcito mentiroso", "fr": "Le Garçon qui criait au loup", "ar": "The Boy Who Cried Wolf", "ru": "The Boy Who Cried Wolf", "uk": "The Boy Who Cried Wolf"}),
        ("The Lion and the Mouse", {"tr": "The Lion and the Mouse", "de": "Der Löwe und die Maus", "es": "El león y el ratón", "fr": "Le Lion et le Rat", "ar": "The Lion and the Mouse", "ru": "The Lion and the Mouse", "uk": "The Lion and the Mouse"}),
        ("The Fox and the Grapes", {"tr": "The Fox and the Grapes", "de": "Der Fuchs und die Trauben", "es": "La zorra y las uvas", "fr": "Le Renard et les Raisins", "ar": "The Fox and the Grapes", "ru": "The Fox and the Grapes", "uk": "The Fox and the Grapes"}),
        ("The Crow and the Pitcher", {"tr": "The Crow and the Pitcher", "de": "Der Rabe und der Krug", "es": "El cuervo y la jarra", "fr": "Le Corbeau et la Cruche", "ar": "The Crow and the Pitcher", "ru": "The Crow and the Pitcher", "uk": "The Crow and the Pitcher"}),
        ("The North Wind and the Sun", {"tr": "The North Wind and the Sun", "de": "Der Nordwind und die Sonne", "es": "El viento del norte y el sol", "fr": "Le Vent du nord et le Soleil", "ar": "The North Wind and the Sun", "ru": "The North Wind and the Sun", "uk": "The North Wind and the Sun"}),
        ("The Milkmaid and Her Pail", {"tr": "The Milkmaid and Her Pail", "de": "Die Milchfrau", "es": "La lechera", "fr": "La Laitière", "ar": "The Milkmaid and Her Pail", "ru": "The Milkmaid and Her Pail", "uk": "The Milkmaid and Her Pail"}),
        ("The Goose That Laid Golden Eggs", {"tr": "The Goose That Laid Golden Eggs", "de": "Die Gans mit den goldenen Eiern", "es": "El ganso de los huevos de oro", "fr": "L'Oie aux œufs d'or", "ar": "The Goose That Laid Golden Eggs", "ru": "The Goose That Laid Golden Eggs", "uk": "The Goose That Laid Golden Eggs"}),
        ("The Shoemaker and the Elves", {"tr": "The Shoemaker and the Elves", "de": "Die Wichtelmänner", "es": "Los duendecillos", "fr": "Les Lutins", "ar": "The Shoemaker and the Elves", "ru": "The Shoemaker and the Elves", "uk": "The Shoemaker and the Elves"}),
    ])

    NEW["toys"] = lit_list([
        ("lego", 1, "LEGO", {}), ("barbie", 1, "Barbie", {}), ("hot_wheels", 1, "Hot Wheels", {}),
        ("nerf", 1, "Nerf blaster", {"tr": "Nerf tabancası", "de": "Nerf-Blaster", "es": "Lanzador Nerf", "fr": "Pistolet Nerf", "ru": "Nerf бластер", "uk": "Nerf бластер"}),
        ("rubiks", 1, "Rubik's Cube", {"tr": "Rubik Küp", "de": "Zauberwürfel", "es": "Cubo de Rubik", "fr": "Rubik's Cube", "ru": "Кубик Рубика", "uk": "Кубик Рубика"}),
        ("yo_yo", 1, "Yo-yo", {"tr": "Yo-yo", "de": "Jo-Jo", "es": "Yo-yo", "fr": "Yo-yo", "ru": "Yo-yo", "uk": "Yo-yo"}),
        ("kite", 1, "Kite", {"tr": "Uçurtma", "de": "Drachen", "ar": "طائرة ورقية", "es": "Cometa", "fr": "Cerf-volant", "ru": "Воздушный змей", "uk": "Повітряний змій"}),
        ("dollhouse", 1, "Dollhouse", {"tr": "Bebek evi", "de": "Puppenhaus", "es": "Casa de muñecas", "fr": "Maison de poupée", "ru": "Кукольный домик", "uk": "Ляльковий будинок"}),
        ("action_figure", 1, "Action figure", {"tr": "Aksiyon figürü", "de": "Actionfigur", "es": "Figura de acción", "fr": "Figurine", "ru": "Фигурка", "uk": "Фігурка"}),
        ("puzzle", 1, "Jigsaw puzzle", {"tr": "Yapboz", "de": "Puzzle", "es": "Rompecabezas", "fr": "Puzzle", "ru": "Пазл", "uk": "Пазл"}),
        ("board_game", 1, "Board game", {"tr": "Kutu oyunu", "de": "Brettspiel", "es": "Juego de mesa", "fr": "Jeu de société", "ru": "Настольная игра", "uk": "Настільна гра"}),
        ("chess_toy", 2, "Chess", {"tr": "Satranç", "de": "Schach", "es": "Ajedrez", "fr": "Échecs", "ru": "Шахматы", "uk": "Шахи"}),
        ("checkers", 1, "Checkers", {"tr": "Dama", "de": "Dame", "es": "Damas", "fr": "Dames", "ru": "Шашки", "uk": "Шашки"}),
        ("dominoes", 1, "Dominoes", {"tr": "Domino", "de": "Domino", "es": "Dominó", "fr": "Dominos", "ru": "Домино", "uk": "Доміно"}),
        ("marbles", 1, "Marbles", {"tr": "Bilye", "de": "Murmeln", "es": "Canicas", "fr": "Billes", "ru": "Шарики", "uk": "Кульки"}),
        ("jump_rope_t", 1, "Jump rope", {"tr": "İp atlama", "de": "Springseil", "es": "Comba", "fr": "Corde à sauter", "ru": "Скакалка", "uk": "Скakалка"}),
        ("hula_hoop", 1, "Hula hoop", {"tr": "Hula hoop", "de": "Hula-Hoop", "es": "Hula hoop", "fr": "Hula hoop", "ru": "Hula hoop", "uk": "Hula hoop"}),
        ("frisbee", 1, "Frisbee", {"tr": "Frisbee", "de": "Frisbee", "es": "Frisbee", "fr": "Frisbee", "ru": "Frisbee", "uk": "Frisbee"}),
        ("slime", 1, "Slime", {"tr": "Slime", "de": "Schleim", "es": "Slime", "fr": "Slime", "ru": "Slime", "uk": "Slime"}),
        ("playdough", 1, "Play-Doh", {"tr": "Oyun hamuru", "de": "Knete", "es": "Plastilina", "fr": "Pâte à modeler", "ru": "Play-Doh", "uk": "Play-Doh"}),
        ("rc_car", 1, "Remote control car", {"tr": "Uzaktan kumandalı araba", "de": "Ferngesteuertes Auto", "es": "Coche teledirigido", "fr": "Voiture télécommandée", "ru": "Машинка на пульте", "uk": "Машинка на пульті"}),
        ("train_set", 1, "Toy train set", {"tr": "Oyuncak tren", "de": "Modelleisenbahn", "es": "Tren de juguete", "fr": "Train électrique", "ru": "Игрушечная железная дорога", "uk": "Іграшкова залізниця"}),
        ("stuffed_animal", 1, "Stuffed animal", {"tr": "Pelüş oyuncak", "de": "Stofftier", "es": "Peluche", "fr": "Peluche", "ru": "Плюшевая игрушка", "uk": "М'яка іграшка"}),
        ("robot_toy", 1, "Toy robot", {"tr": "Oyuncak robot", "de": "Spielzeugroboter", "es": "Robot de juguete", "fr": "Robot jouet", "ru": "Игрушечный робот", "uk": "Іграшковий робот"}),
        ("dinosaur_toy", 1, "Toy dinosaur", {"tr": "Oyuncak dinozor", "de": "Spielzeugdino", "es": "Dinosaurio de juguete", "fr": "Dinosaure jouet", "ru": "Игрушечный динозавр", "uk": "Іграшковий динозавр"}),
        ("water_gun", 1, "Water gun", {"tr": "Su tabancası", "de": "Wasserpistole", "es": "Pistola de agua", "fr": "Pistolet à eau", "ru": "Водный пистолет", "uk": "Водяний пістолет"}),
        ("bubble_wand", 1, "Bubble wand", {"tr": "Baloncuk sopası", "de": "Seifenblasen", "es": "Varita de burbujas", "fr": "Baguette à bulles", "ru": "Мыльные пузыри", "uk": "Мильні бульбашки"}),
        ("sandbox", 1, "Sandbox", {"tr": "Kum havuzu", "de": "Sandkasten", "es": "Arenero", "fr": "Bac à sable", "ru": "Песочница", "uk": "Пісочниця"}),
        ("swing_set", 1, "Swing set", {"tr": "Salıncak", "de": "Schaukel", "es": "Columpio", "fr": "Balançoire", "ru": "Качели", "uk": "Гойдалка"}),
        ("slide_toy", 1, "Playground slide", {"tr": "Kaydırak", "de": "Rutsche", "es": "Tobogán", "fr": "Toboggan", "ru": "Горка", "uk": "Гірка"}),
        ("see_saw", 1, "See-saw", {"tr": "Tahterevalli", "de": "Wippe", "es": "Balancín", "fr": "Balançoire à bascule", "ru": "Качели-качалка", "uk": "Гойдалка"}),
        ("trampoline_t", 1, "Trampoline", {"tr": "Trambolin", "de": "Trampolin", "es": "Trampolín", "fr": "Trampoline", "ru": "Батут", "uk": "Батут"}),
        ("scooter_t", 1, "Scooter", {"tr": "Scooter", "de": "Roller", "es": "Patinete", "fr": "Trottinette", "ru": "Самокат", "uk": "Самокат"}),
        ("skateboard_t", 1, "Skateboard", {"tr": "Kaykay", "de": "Skateboard", "es": "Monopatín", "fr": "Skateboard", "ru": "Скейтboard", "uk": "Скейтboard"}),
        ("roller_skates", 1, "Roller skates", {"tr": "Paten", "de": "Rollschuhe", "es": "Patines", "fr": "Roller", "ru": "Ролики", "uk": "Ролики"}),
        ("bicycle_t", 1, "Bicycle", {"tr": "Bisiklet", "de": "Fahrrad", "es": "Bicicleta", "fr": "Vélo", "ru": "Велосипед", "uk": "Велосипед"}),
        ("tricycle", 1, "Tricycle", {"tr": "Üç tekerlekli bisiklet", "de": "Dreirad", "es": "Triciclo", "fr": "Tricycle", "ru": "Трехколесный велосипед", "uk": "Трицикл"}),
        ("video_game_t", 1, "Video game", {"tr": "Video oyunu", "de": "Videospiel", "es": "Videojuego", "fr": "Jeu vidéo", "ru": "Видеоигра", "uk": "Відеогра"}),
        ("card_game_t", 1, "Card game", {"tr": "Kart oyunu", "de": "Kartenspiel", "es": "Juego de cartas", "fr": "Jeu de cartes", "ru": "Карточная игра", "uk": "Карткова гра"}),
        ("magic_kit", 2, "Magic kit", {"tr": "Sihir seti", "de": "Zauberkasten", "es": "Kit de magia", "fr": "Kit de magie", "ru": "Набор фокусника", "uk": "Набір фokusника"}),
        ("science_kit", 2, "Science kit", {"tr": "Bilim seti", "de": "Experimentierkasten", "es": "Kit de ciencia", "fr": "Kit scientifique", "ru": "Научный набор", "uk": "Науковий набір"}),
    ])

    NEW["colorsShapes"] = lit_list([
        ("purple", 1, "Purple", {"tr": "Mor", "de": "Lila", "ar": "بنفسجي", "es": "Morado", "fr": "Violet", "ru": "Фиолетовый", "uk": "Фіолетовий"}),
        ("pink", 1, "Pink", {"tr": "Pembe", "de": "Rosa", "ar": "وردي", "es": "Rosa", "fr": "Rose", "ru": "Розовый", "uk": "Рожевий"}),
        ("brown", 1, "Brown", {"tr": "Kahverengi", "de": "Braun", "ar": "بني", "es": "Marrón", "fr": "Marron", "ru": "Коричневый", "uk": "Коричневий"}),
        ("gray", 1, "Gray", {"tr": "Gri", "de": "Grau", "ar": "رمادي", "es": "Gris", "fr": "Gris", "ru": "Серый", "uk": "Сірий"}),
        ("black", 1, "Black", {"tr": "Siyah", "de": "Schwarz", "ar": "أسود", "es": "Negro", "fr": "Noir", "ru": "Чёрный", "uk": "Чорний"}),
        ("white", 1, "White", {"tr": "Beyaz", "de": "Weiß", "ar": "أبيض", "es": "Blanco", "fr": "Blanc", "ru": "Белый", "uk": "Білий"}),
        ("gold_c", 1, "Gold", {"tr": "Altın", "de": "Gold", "ar": "ذهبي", "es": "Dorado", "fr": "Or", "ru": "Золотой", "uk": "Золотий"}),
        ("silver_c", 1, "Silver", {"tr": "Gümüş", "de": "Silber", "ar": "فضي", "es": "Plateado", "fr": "Argent", "ru": "Серебряный", "uk": "Срібний"}),
        ("rainbow", 1, "Rainbow", {"tr": "Gökkuşağı", "de": "Regenbogen", "ar": "قوس قزح", "es": "Arcoíris", "fr": "Arc-en-ciel", "ru": "Радуга", "uk": "Веселка"}),
        ("circle", 1, "Circle", {"tr": "Daire", "de": "Kreis", "ar": "دائرة", "es": "Círculo", "fr": "Cercle", "ru": "Круг", "uk": "Коло"}),
        ("square", 1, "Square", {"tr": "Kare", "de": "Quadrat", "ar": "مربع", "es": "Cuadrado", "fr": "Carré", "ru": "Квадрат", "uk": "Квадрат"}),
        ("triangle", 1, "Triangle", {"tr": "Üçgen", "de": "Dreieck", "ar": "مثلث", "es": "Triángulo", "fr": "Triangle", "ru": "Треугольник", "uk": "Трикутник"}),
        ("rectangle", 1, "Rectangle", {"tr": "Dikdörtgen", "de": "Rechteck", "ar": "مستطيل", "es": "Rectángulo", "fr": "Rectangle", "ru": "Прямоугольник", "uk": "Прямокутник"}),
        ("oval", 1, "Oval", {"tr": "Oval", "de": "Oval", "ar": "بيضاوي", "es": "Óvalo", "fr": "Ovale", "ru": "Овал", "uk": "Овал"}),
        ("star_shape", 1, "Star shape", {"tr": "Yıldız", "de": "Stern", "ar": "نجمة", "es": "Estrella", "fr": "Étoile", "ru": "Звезда", "uk": "Зірка"}),
        ("heart_shape", 1, "Heart shape", {"tr": "Kalp", "de": "Herz", "ar": "قلب", "es": "Corazón", "fr": "Cœur", "ru": "Сердце", "uk": "Серце"}),
        ("diamond_shape", 1, "Diamond shape", {"tr": "Elmas", "de": "Raute", "ar": "معين", "es": "Rombo", "fr": "Losange", "ru": "Ромб", "uk": "Ромб"}),
        ("pentagon", 2, "Pentagon", {"tr": "Beşgen", "de": "Fünfeck", "ar": "Pentagon", "es": "Pentágono", "fr": "Pentagone", "ru": "Пятиугольник", "uk": "П'ятикутник"}),
        ("hexagon", 2, "Hexagon", {"tr": "Altıgen", "de": "Sechseck", "ar": "Hexagon", "es": "Hexágono", "fr": "Hexagone", "ru": "Шестиугольник", "uk": "Шестикутник"}),
        ("octagon", 2, "Octagon", {"tr": "Sekizgen", "de": "Achteck", "ar": "Octagon", "es": "Octágono", "fr": "Octogone", "ru": "Восьмиугольник", "uk": "Восьмикутник"}),
        ("sphere", 1, "Sphere", {"tr": "Küre", "de": "Kugel", "ar": "Sphere", "es": "Esfera", "fr": "Sphère", "ru": "Сфера", "uk": "Сфера"}),
        ("cube", 1, "Cube", {"tr": "Küp", "de": "Würfel", "ar": "Cube", "es": "Cubo", "fr": "Cube", "ru": "Куб", "uk": "Куб"}),
        ("cylinder", 2, "Cylinder", {"tr": "Silindir", "de": "Zylinder", "ar": "Cylinder", "es": "Cilindro", "fr": "Cylindre", "ru": "Цилиндр", "uk": "Циліндр"}),
        ("cone", 2, "Cone", {"tr": "Koni", "de": "Kegel", "ar": "Cone", "es": "Cono", "fr": "Cône", "ru": "Конус", "uk": "Конус"}),
        ("pyramid", 2, "Pyramid", {"tr": "Piramit", "de": "Pyramide", "ar": "Pyramid", "es": "Pirámide", "fr": "Pyramide", "ru": "Пирамида", "uk": "Піраміда"}),
        ("spiral", 2, "Spiral", {"tr": "Spiral", "de": "Spirale", "ar": "Spiral", "es": "Espiral", "fr": "Spirale", "ru": "Спираль", "uk": "Спіраль"}),
        ("zigzag", 1, "Zigzag", {"tr": "Zigzag", "de": "Zickzack", "ar": "Zigzag", "es": "Zigzag", "fr": "Zigzag", "ru": "Zigzag", "uk": "Zigzag"}),
        ("line", 1, "Line", {"tr": "Çizgi", "de": "Linie", "ar": "Line", "es": "Línea", "fr": "Ligne", "ru": "Линия", "uk": "Лінія"}),
        ("dot", 1, "Dot", {"tr": "Nokta", "de": "Punkt", "ar": "Dot", "es": "Punto", "fr": "Point", "ru": "Точка", "uk": "Крапка"}),
        ("big", 1, "Big", {"tr": "Büyük", "de": "Groß", "ar": "Big", "es": "Grande", "fr": "Grand", "ru": "Большой", "uk": "Великий"}),
        ("small", 1, "Small", {"tr": "Küçük", "de": "Klein", "ar": "Small", "es": "Pequeño", "fr": "Petit", "ru": "Маленький", "uk": "Маленький"}),
        ("long", 1, "Long", {"tr": "Uzun", "de": "Lang", "ar": "Long", "es": "Largo", "fr": "Long", "ru": "Длинный", "uk": "Довгий"}),
        ("short", 1, "Short", {"tr": "Kısa", "de": "Kurz", "ar": "Short", "es": "Corto", "fr": "Court", "ru": "Короткий", "uk": "Короткий"}),
        ("wide", 1, "Wide", {"tr": "Geniş", "de": "Breit", "ar": "Wide", "es": "Ancho", "fr": "Large", "ru": "Широкий", "uk": "Широкий"}),
        ("narrow", 1, "Narrow", {"tr": "Dar", "de": "Schmal", "ar": "Narrow", "es": "Estrecho", "fr": "Étroit", "ru": "Узкий", "uk": "Вузький"}),
        ("thick", 1, "Thick", {"tr": "Kalın", "de": "Dick", "ar": "Thick", "es": "Grueso", "fr": "Épais", "ru": "Толстый", "uk": "Товстий"}),
        ("thin", 1, "Thin", {"tr": "İnce", "de": "Dünn", "ar": "Thin", "es": "Delgado", "fr": "Fin", "ru": "Тонкий", "uk": "Тонкий"}),
        ("light_color", 1, "Light color", {"tr": "Açık renk", "de": "Helle Farbe", "ar": "Light color", "es": "Color claro", "fr": "Couleur claire", "ru": "Светлый цвет", "uk": "Світлий колір"}),
        ("dark_color", 1, "Dark color", {"tr": "Koyu renk", "de": "Dunkle Farbe", "ar": "Dark color", "es": "Color oscuro", "fr": "Couleur foncée", "ru": "Тёмный цвет", "uk": "Темний колір"}),
        ("mix_colors", 1, "Mix colors", {"tr": "Renkleri karıştır", "de": "Farben mischen", "ar": "Mix colors", "es": "Mezclar colores", "fr": "Mélanger les couleurs", "ru": "Смешать цвета", "uk": "Змішати кольори"}),
    ])

    # school, dinosaurs, animalSounds, fruits, vehicles - compact literal decks
    def bulk_literal(deck, items):
        NEW[deck] = lit_list(items)

    bulk_literal("school", [
        ("backpack", 1, "Backpack", {"tr": "Sırt çantası", "de": "Rucksack", "es": "Mochila", "fr": "Sac à dos", "ru": "Рюкзак", "uk": "Рюкзак"}),
        ("textbook", 1, "Textbook", {"tr": "Ders kitabı", "de": "Lehrbuch", "es": "Libro de texto", "fr": "Manuel", "ru": "Учебник", "uk": "Підручник"}),
        ("highlighter", 1, "Highlighter", {"tr": "Fosforlu kalem", "de": "Textmarker", "es": "Rotulador", "fr": "Surligneur", "ru": "Маркер", "uk": "Маркер"}),
        ("stapler", 1, "Stapler", {"tr": "Zımba", "de": "Heftgerät", "es": "Grapadora", "fr": "Agrafeuse", "ru": "Степлер", "uk": "Степлер"}),
        ("paper_clip", 1, "Paper clip", {"tr": "Ataç", "de": "Büroklammer", "es": "Clip", "fr": "Trombone", "ru": "Скрепка", "uk": "Скрепка"}),
        ("whiteboard", 1, "Whiteboard", {"tr": "Beyaz tahta", "de": "Whiteboard", "es": "Pizarra blanca", "fr": "Tableau blanc", "ru": "Белая доска", "uk": "Біла дошка"}),
        ("projector", 1, "Projector", {"tr": "Projeksiyon", "de": "Projektor", "es": "Proyector", "fr": "Projecteur", "ru": "Проектор", "uk": "Проектор"}),
        ("library", 1, "Library", {"tr": "Kütüphane", "de": "Bibliothek", "es": "Biblioteca", "fr": "Bibliothèque", "ru": "Библиотека", "uk": "Бібліотека"}),
        ("cafeteria", 1, "Cafeteria", {"tr": "Yemekhane", "de": "Mensa", "es": "Cafetería", "fr": "Cantine", "ru": "Столовая", "uk": "Їдальня"}),
        ("gym_class", 1, "Gym class", {"tr": "Beden eğitimi", "de": "Sportunterricht", "es": "Educación física", "fr": "EPS", "ru": "Физкультура", "uk": "Фізкультура"}),
        ("art_class", 1, "Art class", {"tr": "Resim dersi", "de": "Kunstunterricht", "es": "Clase de arte", "fr": "Arts plastiques", "ru": "Урок рисования", "uk": "Урок малювання"}),
        ("music_class", 1, "Music class", {"tr": "Müzik dersi", "de": "Musikunterricht", "es": "Clase de música", "fr": "Cours de musique", "ru": "Урок музыки", "uk": "Урок музики"}),
        ("science_class", 1, "Science class", {"tr": "Fen dersi", "de": "Naturwissenschaft", "es": "Clase de ciencias", "fr": "Sciences", "ru": "Урок науки", "uk": "Урок науки"}),
        ("math_class", 1, "Math class", {"tr": "Matematik dersi", "de": "Matheunterricht", "es": "Clase de matemáticas", "fr": "Mathématiques", "ru": "Урок математики", "uk": "Урок математики"}),
        ("history_class", 1, "History class", {"tr": "Tarih dersi", "de": "Geschichtsunterricht", "es": "Clase de historia", "fr": "Histoire", "ru": "Урок истории", "uk": "Урок історії"}),
        ("field_trip", 1, "Field trip", {"tr": "Gezi", "de": "Exkursion", "es": "Excursión", "fr": "Sortie scolaire", "ru": "Экскурсия", "uk": "Екскурсія"}),
        ("assembly", 1, "School assembly", {"tr": "Okul töreni", "de": "Schulversammlung", "es": "Asamblea escolar", "fr": "Assemblée", "ru": "Линейка", "uk": "Лінійка"}),
        ("detention", 2, "Detention", {"tr": "Ceza", "de": "Nachsitzen", "es": "Castigo", "fr": "Retenue", "ru": "Задержание", "uk": "Затримання"}),
        ("graduation", 1, "Graduation", {"tr": "Mezuniyet", "de": "Abschluss", "es": "Graduación", "fr": "Remise des diplômes", "ru": "Выпускной", "uk": "Випускний"}),
        ("diploma", 1, "Diploma", {"tr": "Diploma", "de": "Diplom", "es": "Diploma", "fr": "Diplôme", "ru": "Диплом", "uk": "Диплом"}),
        ("principal", 1, "Principal", {"tr": "Müdür", "de": "Schulleiter", "es": "Director", "fr": "Directeur", "ru": "Директор", "uk": "Директор"}),
        ("classroom", 1, "Classroom", {"tr": "Sınıf", "de": "Klassenzimmer", "es": "Aula", "fr": "Salle de classe", "ru": "Класс", "uk": "Клас"}),
        ("locker", 1, "Locker", {"tr": "Dolap", "de": "Spind", "es": "Taquilla", "fr": "Casier", "ru": "Шкафчик", "uk": "Шафка"}),
        ("hallway", 1, "Hallway", {"tr": "Koridor", "de": "Flur", "es": "Pasillo", "fr": "Couloir", "ru": "Коридор", "uk": "Коридор"}),
        ("playground", 1, "Playground", {"tr": "Oyun alanı", "de": "Spielplatz", "es": "Patio", "fr": "Cour de récréation", "ru": "Площадка", "uk": "Майданчик"}),
        ("permission_slip", 2, "Permission slip", {"tr": "İzin kağıdı", "de": "Erlaubniszettel", "es": "Permiso", "fr": "Autorisation", "ru": "Разрешение", "uk": "Дозвіл"}),
        ("report_card", 1, "Report card", {"tr": "Karne", "de": "Zeugnis", "es": "Boletín", "fr": "Bulletin", "ru": "Табель", "uk": "Табель"}),
        ("group_project", 1, "Group project", {"tr": "Grup projesi", "de": "Gruppenprojekt", "es": "Proyecto grupal", "fr": "Projet de groupe", "ru": "Групповой проект", "uk": "Груповий проєкт"}),
        ("presentation", 2, "Presentation", {"tr": "Sunum", "de": "Präsentation", "es": "Presentación", "fr": "Présentation", "ru": "Презентация", "uk": "Презентація"}),
        ("pop_quiz", 1, "Pop quiz", {"tr": "Sürpriz sınav", "de": "Überraschungstest", "es": "Examen sorpresa", "fr": "Interro surprise", "ru": "Внезапный тест", "uk": "Неспodivаний тест"}),
        ("study_hall", 1, "Study hall", {"tr": "Etüt", "de": "Lernzeit", "es": "Hora de estudio", "fr": "Étude", "ru": "Study hall", "uk": "Study hall"}),
        ("school_bus_s", 1, "School bus", {"tr": "Okul servisi", "de": "Schulbus", "es": "Autobús escolar", "fr": "Bus scolaire", "ru": "Школьный автобус", "uk": "Шкільний автобус"}),
        ("uniform", 1, "School uniform", {"tr": "Okul forması", "de": "Schuluniform", "es": "Uniforme escolar", "fr": "Uniforme scolaire", "ru": "Школьная форма", "uk": "Шкільна форма"}),
        ("tardy", 1, "Late to class", {"tr": "Derse geç kalmak", "de": "Zu spät kommen", "es": "Llegar tarde", "fr": "En retard", "ru": "Опоздание", "uk": "Запізнення"}),
        ("raise_hand_s", 1, "Raise your hand", {"tr": "El kaldır", "de": "Hand heben", "es": "Levantar la mano", "fr": "Lever la main", "ru": "Поднять руку", "uk": "Підняти руку"}),
        ("answer_question", 1, "Answer a question", {"tr": "Soruyu cevapla", "de": "Frage beantworten", "es": "Responder", "fr": "Répondre", "ru": "Ответить на вопрос", "uk": "Відповісти на питання"}),
        ("take_notes", 1, "Take notes", {"tr": "Not al", "de": "Notizen machen", "es": "Tomar apuntes", "fr": "Prendre des notes", "ru": "Записывать", "uk": "Записувати"}),
        ("pack_lunch_s", 1, "Pack lunch", {"tr": "Beslenme hazırla", "de": "Brotdose packen", "es": "Preparar lonchera", "fr": "Préparer le goûter", "ru": "Собрать обед", "uk": "Зібрати обід"}),
        ("fire_drill", 1, "Fire drill", {"tr": "Yangın tatbikatı", "de": "Feueralarm", "es": "Simulacro de incendio", "fr": "Exercice incendie", "ru": "Пожарная тревога", "uk": "Пожежна тривога"}),
        ("school_supplies", 1, "School supplies", {"tr": "Okul malzemeleri", "de": "Schulbedarf", "es": "Útiles escolares", "fr": "Fournitures scolaires", "ru": "Школьные принадлежности", "uk": "Шкільне приладдя"}),
        ("student_council", 2, "Student council", {"tr": "Öğrenci konseyi", "de": "Schülerrat", "es": "Consejo estudiantil", "fr": "Conseil des élèves", "ru": "Student council", "uk": "Student council"}),
    ])

    bulk_literal("dinosaurs", [
        ("giganotosaurus", 2, "Giganotosaurus", {"tr": "Giganotosaurus", "ru": "Гiganotosaurus", "uk": "Giganotosaurus"}),
        ("therizinosaurus", 2, "Therizinosaurus", {"tr": "Therizinosaurus", "ru": "Therizinosaurus", "uk": "Therizinosaurus"}),
        ("utahraptor", 2, "Utahraptor", {"tr": "Utahraptor", "ru": "Utahraptor", "uk": "Utahraptor"}),
        ("pachycephalosaurus", 2, "Pachycephalosaurus", {"tr": "Pachycephalosaurus", "ru": "Pachycephalosaurus", "uk": "Pachycephalosaurus"}),
        ("argentinosaurus", 2, "Argentinosaurus", {"tr": "Argentinosaurus", "ru": "Argentinosaurus", "uk": "Argentinosaurus"}),
        ("brontosaurus", 1, "Brontosaurus", {"tr": "Brontosaurus", "ru": "Brontosaurus", "uk": "Brontosaurus"}),
        ("apatosaurus", 2, "Apatosaurus", {"tr": "Apatosaurus", "ru": "Apatosaurus", "uk": "Apatosaurus"}),
        ("carnotaurus_d", 1, "Carnotaurus", {"tr": "Carnotaurus", "ru": "Carnotaurus", "uk": "Carnotaurus"}),
        ("baryonyx", 2, "Baryonyx", {"tr": "Baryonyx", "ru": "Baryonyx", "uk": "Baryonyx"}),
        ("compsognathus", 2, "Compsognathus", {"tr": "Compsognathus", "ru": "Compsognathus", "uk": "Compsognathus"}),
        ("gallimimus", 2, "Gallimimus", {"tr": "Gallimimus", "ru": "Gallimimus", "uk": "Gallimimus"}),
        ("pteranodon", 1, "Pteranodon", {"tr": "Pteranodon", "ru": "Pteranodon", "uk": "Pteranodon"}),
        ("quetzalcoatlus", 2, "Quetzalcoatlus", {"tr": "Quetzalcoatlus", "ru": "Quetzalcoatlus", "uk": "Quetzalcoatlus"}),
        ("dimorphodon", 2, "Dimorphodon", {"tr": "Dimorphodon", "ru": "Dimorphodon", "uk": "Dimorphodon"}),
        ("microraptor", 2, "Microraptor", {"tr": "Microraptor", "ru": "Microraptor", "uk": "Microraptor"}),
        ("deinonychus", 2, "Deinonychus", {"tr": "Deinonychus", "ru": "Deinonychus", "uk": "Deinonychus"}),
        ("ceratosaurus", 2, "Ceratosaurus", {"tr": "Ceratosaurus", "ru": "Ceratosaurus", "uk": "Ceratosaurus"}),
        ("maiasaura", 2, "Maiasaura", {"tr": "Maiasaura", "ru": "Maiasaura", "uk": "Maiasaura"}),
        ("protoceratops", 2, "Protoceratops", {"tr": "Protoceratops", "ru": "Protoceratops", "uk": "Protoceratops"}),
        ("kentrosaurus", 2, "Kentrosaurus", {"tr": "Kentrosaurus", "ru": "Kentrosaurus", "uk": "Kentrosaurus"}),
        ("euoplocephalus", 2, "Euoplocephalus", {"tr": "Euoplocephalus", "ru": "Euoplocephalus", "uk": "Euoplocephalus"}),
        ("corythosaurus", 2, "Corythosaurus", {"tr": "Corythosaurus", "ru": "Corythosaurus", "uk": "Corythosaurus"}),
        ("ouranosaurus", 2, "Ouranosaurus", {"tr": "Ouranosaurus", "ru": "Ouranosaurus", "uk": "Ouranosaurus"}),
        ("spinosaurus_d", 1, "Spinosaurus", {"tr": "Spinosaurus", "ru": "Spinosaurus", "uk": "Spinosaurus"}),
        ("meteor_extinction", 1, "Meteor extinction", {"tr": "Meteor yok oluşu", "de": "Meteor-Aussterben", "es": "Extinción por meteorito", "fr": "Extinction météorite", "ru": "Вымирание от метеорита", "uk": "Вимирання від метеорита"}),
        ("paleontologist", 2, "Paleontologist", {"tr": "Paleontolog", "de": "Paläontologe", "es": "Paleontólogo", "fr": "Paléontologue", "ru": "Палеontolog", "uk": "Палеontolog"}),
        ("dig_site", 1, "Fossil dig site", {"tr": "Kazı alanı", "de": "Grabungsstätte", "es": "Yacimiento", "fr": "Site de fouilles", "ru": "Раскопки", "uk": "Розкопки"}),
        ("dino_footprint", 1, "Dinosaur footprint", {"tr": "Dinozor ayak izi", "de": "Dinosaurier-Fußabdruck", "es": "Huella de dinosaurio", "fr": "Empreinte de dinosaure", "ru": "След динозавра", "uk": "Слід динозавра"}),
        ("dino_roar", 1, "Dinosaur roar", {"tr": "Dinozor kükremesi", "de": "Dinosaurier brüllt", "es": "Rugido de dinosaurio", "fr": "Rugissement", "ru": "Рёв динозавра", "uk": "Рев динозавра"}),
        ("herbivore", 1, "Herbivore dinosaur", {"tr": "Otçul dinozor", "de": "Pflanzenfresser", "es": "Herbívoro", "fr": "Herbivore", "ru": "Травоядный", "uk": "Травоїдний"}),
        ("carnivore", 1, "Carnivore dinosaur", {"tr": "Etçil dinozor", "de": "Fleischfresser", "es": "Carnívoro", "fr": "Carnivore", "ru": "Хищник", "uk": "Хижak"}),
        ("jurassic", 1, "Jurassic Period", {"tr": "Jura Dönemi", "de": "Jura", "es": "Jurásico", "fr": "Jurassique", "ru": "Юрский период", "uk": "Юрський період"}),
        ("cretaceous", 1, "Cretaceous Period", {"tr": "Kretase Dönemi", "de": "Kreidezeit", "es": "Cretácico", "fr": "Crétacé", "ru": "Меловой период", "uk": "Крейдовий період"}),
        ("triassic", 2, "Triassic Period", {"tr": "Trias Dönemi", "de": "Trias", "es": "Triásico", "fr": "Trias", "ru": "Triassic", "uk": "Triassic"}),
        ("dino_nest", 1, "Dinosaur nest", {"tr": "Dinozor yuvası", "de": "Dinosauriernest", "es": "Nido de dinosaurio", "fr": "Nid de dinosaure", "ru": "Гнездо динозавра", "uk": "Гніздо динозавра"}),
        ("amber", 2, "Amber fossil", {"tr": "Kehribar fosili", "de": "Bernstein", "es": "Ámbar", "fr": "Ambre", "ru": "Янтарь", "uk": "Бурштин"}),
        ("museum_dino", 1, "Dinosaur museum", {"tr": "Dinozor müzesi", "de": "Dino-Museum", "es": "Museo de dinosaurios", "fr": "Musée des dinosaures", "ru": "Музей динозавров", "uk": "Музей динозаврів"}),
        ("dino_skeleton", 1, "Dinosaur skeleton", {"tr": "Dinozor iskeleti", "de": "Dinosaurierskelett", "es": "Esqueleto de dinosaurio", "fr": "Squelette de dinosaure", "ru": "Скелет динозавра", "uk": "Скелет динозавра"}),
        ("volcano_dino", 1, "Volcano in dinosaur era", {"tr": "Volkan", "de": "Vulkan", "es": "Volcán", "fr": "Volcan", "ru": "Вулкан", "uk": "Volkan"}),
        ("prehistoric_plant", 1, "Prehistoric plant", {"tr": "Prehistorik bitki", "de": "Urzeitpflanze", "es": "Planta prehistórica", "fr": "Plante préhistorique", "ru": "Prehistoric plant", "uk": "Prehistoric plant"}),
    ])

    # Continue with animalSounds, fruits, vehicles, sports, knowledge decks...
    from _build_all_decks_ext3 import extend3
    extend3(NEW, lit, lit_list, adapt, adapt_list, fill, card, sc, t, bulk_literal)
