"""Extension deck data for _build_all_decks.py"""


def extend(NEW, lit, lit_list, adapt, adapt_list, fill, card, sc, t):
    # singers sg_21-60
    NEW["singers"] = adapt_list("sg", 21, [
        ("Shakira", {"tr": "Hadise", "de": "Shirin David", "es": "Shakira", "fr": "Angèle", "ar": "نانسي عجرم", "ru": "Полина Гагарина", "uk": "KAZKA"}),
        ("Adele", {"tr": "Gülşen", "de": "Lena", "es": "Aitana", "fr": "Louane", "ar": "Elissa", "ru": "Алла Пугачёва", "uk": "Софія Ротaru"}),
        ("Ed Sheeran", {"tr": "Edis", "de": "Tim Bendzko", "es": "Alejandro Sanz", "fr": "Vianney", "ar": "Amr Diab", "ru": "Мот", "uk": "Monatik"}),
        ("Lady Gaga", {"tr": "Sertab Erener", "de": "Helene Fischer", "es": "Rosalía", "fr": "Pomme", "ar": "Sherine", "ru": "Бузова", "uk": "Tina Karol"}),
        ("Kendrick Lamar", {"tr": "Ezhel", "de": "Apache 207", "es": "Bad Bunny", "fr": "Stromae", "ar": "Wegz", "ru": "Oxxxymiron", "uk": "Alyona Alyona"}),
        ("Eminem", {"tr": "Ceza", "de": "Sido", "es": "Residente", "fr": "Nekfeu", "ar": "Lege-Cy", "ru": "Баста", "uk": "Skofka"}),
        ("Katy Perry", {"tr": "Simge", "de": "Lena", "es": "Aitana", "fr": "Angèle", "ar": "Balqees", "ru": "IOWA", "uk": "Tina Karol"}),
        ("Usher", {"tr": "Tarkan", "de": "Xavier Naidoo", "es": "Enrique Iglesias", "fr": "Slimane", "ar": "Mohamed Hamaki", "ru": "Дима Бilan", "uk": "Monatik"}),
        ("Chris Brown", {"tr": "Murda", "de": "Cro", "es": "Maluma", "fr": "Gims", "ar": "Amr Diab", "ru": "Егор Кrid", "uk": "Wellboy"}),
        ("Lana Del Rey", {"tr": "Melike Şahin", "de": "AnnenMayKantereit", "es": "Amaia", "fr": "Clara Luciani", "ar": "Elissa", "ru": "Монетochka", "uk": "KAZKA"}),
        ("Travis Scott", {"tr": "Ezhel", "de": "RAF Camora", "es": "Bad Bunny", "fr": "Damso", "ar": "Wegz", "ru": "Скриптonit", "uk": "Kalush"}),
        ("Nicki Minaj", {"tr": "Gülşen", "de": "Shirin David", "es": "Rosalía", "fr": "Aya Nakamura", "ar": "Balqees", "ru": "IOWA", "uk": "Alyona Alyona"}),
        ("Jay-Z", {"tr": "Ceza", "de": "Kollegah", "es": "Residente", "fr": "Booba", "ar": "Lege-Cy", "ru": "Баста", "uk": "Skofka"}),
        ("Elton John", {"tr": "Barış Manço", "de": "Peter Maffay", "es": "Raphael", "fr": "Michel Polnareff", "ar": "Amr Diab", "ru": "Filipp Kirkorov", "uk": "VIA Gra"}),
        ("Whitney Houston", {"tr": "Sezen Aksu", "de": "Helene Fischer", "es": "Rocío Jurado", "fr": "Dalida", "ar": "Umm Kulthum", "ru": "Пугачёва", "uk": "Rotaru"}),
        ("Michael Jackson", {"tr": "Tarkan", "de": "Peter Maffay", "es": "Julio Iglesias", "fr": "Johnny Hallyday", "ar": "Amr Diab", "ru": "Filipp Kirkorov", "uk": "Vakarchuk"}),
        ("Madonna", {"tr": "Ajda Pekkan", "de": "Nena", "es": "Mónica Naranjo", "fr": "Patricia Kaas", "ar": "Samira Said", "ru": "Алла Пугачёva", "uk": "Rotaru"}),
        ("Prince", {"tr": "Barış Manço", "de": "Udo Lindenberg", "es": "Alejandro Sanz", "fr": "Johnny Hallyday", "ar": "Amr Diab", "ru": "Цой", "uk": "Vakarchuk"}),
        ("Bob Marley", {"tr": "Moğollar", "de": "Seeed", "es": "Manu Chao", "fr": "Manu Chao", "ar": "Cheb Khaled", "ru": "Lumen", "uk": "Okean Elzy"}),
        ("Frank Sinatra", {"tr": "Zeki Müren", "de": "Udo Jürgens", "es": "Luis Miguel", "fr": "Charles Aznavour", "ar": "Abdel Halim", "ru": "Окудjava", "uk": "Ivasiuk"}),
        ("Celine Dion", {"tr": "Sertab Erener", "de": "Helene Fischer", "es": "Rocío Jurado", "fr": "Céline Dion", "ar": "Fairuz", "ru": "Пугачёva", "uk": "Rotaru"}),
        ("Mariah Carey", {"tr": "Sertab Erener", "de": "Helene Fischer", "es": "Thalia", "fr": "Jenifer", "ar": "Elissa", "ru": "Валерия", "uk": "Tina Karol"}),
        ("Stevie Wonder", {"tr": "Barış Manço", "de": "Xavier Naidoo", "es": "Alejandro Sanz", "fr": "Stromae", "ar": "Amr Diab", "ru": "Kirkorov", "uk": "Monatik"}),
        ("Bob Dylan", {"tr": "Cem Karaca", "de": "Udo Lindenberg", "es": "Joan Manuel Serrat", "fr": "Jacques Brel", "ar": "Marcel Khalife", "ru": "Vysotsky", "uk": "Vakarchuk"}),
        ("David Bowie", {"tr": "Barış Manço", "de": "Udo Lindenberg", "es": "Mecano", "fr": "Serge Gainsbourg", "ar": "Marcel Khalife", "ru": "Tsoy", "uk": "Vakarchuk"}),
        ("Freddie Mercury", {"tr": "Barış Manço", "de": "Udo Lindenberg", "es": "Mecano", "fr": "Johnny Hallyday", "ar": "Amr Diab", "ru": "Kirkorov", "uk": "Vakarchuk"}),
        ("Amy Winehouse", {"tr": "Melike Şahin", "de": "AnnenMayKantereit", "es": "Amaia", "fr": "Clara Luciani", "ar": "Sherine", "ru": "Monetochka", "uk": "KAZKA"}),
        ("George Michael", {"tr": "Tarkan", "de": "Peter Maffay", "es": "Alejandro Sanz", "fr": "Michel Polnareff", "ar": "Amr Diab", "ru": "Kirkorov", "uk": "Monatik"}),
        ("Sam Smith", {"tr": "Edis", "de": "Tim Bendzko", "es": "Pablo Alborán", "fr": "Vianney", "ar": "Mohamed Hamaki", "ru": "Mot", "uk": "Monatik"}),
        ("Lizzo", {"tr": "Gülşen", "de": "Shirin David", "es": "Rosalía", "fr": "Aya Nakamura", "ar": "Balqees", "ru": "IOWA", "uk": "Alyona Alyona"}),
        ("Dua Lipa", {"tr": "Simge", "de": "Nina Chuba", "es": "Aitana", "fr": "Angèle", "ar": "Balqees", "ru": "IOWA", "uk": "KAZKA"}),
        ("Harry Styles", {"tr": "Mert Demir", "de": "Tim Bendzko", "es": "Aitana", "fr": "Vianney", "ar": "Mohamed Hamaki", "ru": "Mot", "uk": "Monatik"}),
        ("Billie Eilish", {"tr": "Melike Şahin", "de": "Nina Chuba", "es": "Amaia", "fr": "Pomme", "ar": "Sherine", "ru": "Monetochka", "uk": "KAZKA"}),
        ("Olivia Rodrigo", {"tr": "Melike Şahin", "de": "Nina Chuba", "es": "Amaia", "fr": "Pomme", "ar": "Sherine", "ru": "Monetochka", "uk": "KAZKA"}),
        ("Sabrina Carpenter", {"tr": "Simge", "de": "Nina Chuba", "es": "Aitana", "fr": "Angèle", "ar": "Balqees", "ru": "IOWA", "uk": "KAZKA"}),
        ("Post Malone", {"tr": "Murda", "de": "Cro", "es": "Bad Bunny", "fr": "Gims", "ar": "Wegz", "ru": "Егор Кrid", "uk": "Wellboy"}),
        ("Bruno Mars", {"tr": "Edis", "de": "Nico Santos", "es": "Alejandro Sanz", "fr": "Vianney", "ar": "Amr Diab", "ru": "Mot", "uk": "Monatik"}),
        ("The Weeknd", {"tr": "Murda", "de": "Apache 207", "es": "Bad Bunny", "fr": "Gims", "ar": "Wegz", "ru": "Скриптonit", "uk": "Kalush"}),
        ("Drake", {"tr": "Ezhel", "de": "RAF Camora", "es": "Bad Bunny", "fr": "Damso", "ar": "Wegz", "ru": "Oxxxymiron", "uk": "Kalush"}),
    ])

    # bands bd_21-60
    NEW["bands"] = adapt_list("bd", 21, [
        ("Pink Floyd", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Mecano", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Led Zeppelin", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Téléphone", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Rolling Stones", {"tr": "MFÖ", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Téléphone", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("ABBA", {"tr": "Ajda Pekkan", "de": "Nena", "es": "Mecano", "fr": "Indochine", "ar": "Fairuz", "ru": "Lumen", "uk": "VIA Gra"}),
        ("The Doors", {"tr": "Erkin Koray", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Téléphone", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Guns N' Roses", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Aerosmith", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Bon Jovi", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Who", {"tr": "MFÖ", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Téléphone", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Beach Boys", {"tr": "MFÖ", "de": "Die Toten Hosen", "es": "Mecano", "fr": "Indochine", "ar": "Fairuz", "ru": "Lumen", "uk": "VIA Gra"}),
        ("The Clash", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Téléphone", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Cure", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Oasis", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Blur", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Killers", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Muse", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Strokes", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Arctic Monkeys", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Maroon 5", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("OneRepublic", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Imagine Dragons", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Fall Out Boy", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("My Chemical Romance", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Panic! at the Disco", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Chainsmokers", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Daft Punk", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Mecano", "fr": "Indochine", "ar": "Fairuz", "ru": "Lumen", "uk": "VIA Gra"}),
        ("The Prodigy", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Depeche Mode", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Mecano", "fr": "Indochine", "ar": "Fairuz", "ru": "Lumen", "uk": "VIA Gra"}),
        ("Rammstein", {"tr": "Duman", "de": "Rammstein", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("System of a Down", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Slipknot", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Kiss", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Eagles", {"tr": "MFÖ", "de": "Die Toten Hosen", "es": "Mecano", "fr": "Indochine", "ar": "Fairuz", "ru": "Lumen", "uk": "VIA Gra"}),
        ("Fleetwood Mac", {"tr": "MFÖ", "de": "Die Toten Hosen", "es": "Mecano", "fr": "Indochine", "ar": "Fairuz", "ru": "Lumen", "uk": "VIA Gra"}),
        ("The Police", {"tr": "MFÖ", "de": "Die Toten Hosen", "es": "Mecano", "fr": "Indochine", "ar": "Fairuz", "ru": "Lumen", "uk": "VIA Gra"}),
        ("U2", {"tr": "Duman", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The Smiths", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Radiohead", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("Coldplay", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
        ("The 1975", {"tr": "Mor ve Ötesi", "de": "Die Toten Hosen", "es": "Héroes del Silencio", "fr": "Indochine", "ar": "Cairokee", "ru": "Kino", "uk": "Okean Elzy"}),
    ])

    # lyrics ly_21-60 (Artist - Song format for en)
    NEW["lyrics"] = adapt_list("ly", 21, [
        ("Bohemian Rhapsody", {"tr": "Tarkan - Şımarık", "de": "Queen - Bohemian Rhapsody", "es": "Queen - Bohemian Rhapsody", "fr": "Queen - Bohemian Rhapsody", "ar": "أم كلثوم - أنت عمري", "ru": "Queen - Bohemian Rhapsody", "uk": "Queen - Bohemian Rhapsody"}),
        ("Imagine", {"tr": "Barış Manço - Dönence", "de": "John Lennon - Imagine", "es": "John Lennon - Imagine", "fr": "John Lennon - Imagine", "ar": "Fairuz - Saalouny", "ru": "John Lennon - Imagine", "uk": "John Lennon - Imagine"}),
        ("Hotel California", {"tr": "Sezen Aksu - Gülümse", "de": "Eagles - Hotel California", "es": "Eagles - Hotel California", "fr": "Eagles - Hotel California", "ar": "Amr Diab - Tamally Maak", "ru": "Eagles - Hotel California", "uk": "Eagles - Hotel California"}),
        ("Stairway to Heaven", {"tr": "Barış Manço - Gülpembe", "de": "Led Zeppelin - Stairway to Heaven", "es": "Led Zeppelin - Stairway to Heaven", "fr": "Led Zeppelin - Stairway to Heaven", "ar": "Fairuz - Bint El Shalabiya", "ru": "Led Zeppelin - Stairway to Heaven", "uk": "Led Zeppelin - Stairway to Heaven"}),
        ("Smells Like Teen Spirit", {"tr": "Duman - Seni Kendime Sakladım", "de": "Nirvana - Smells Like Teen Spirit", "es": "Nirvana - Smells Like Teen Spirit", "fr": "Nirvana - Smells Like Teen Spirit", "ar": "Cairokee - Matloob Zaeem", "ru": "Nirvana - Smells Like Teen Spirit", "uk": "Nirvana - Smells Like Teen Spirit"}),
        ("Wonderwall", {"tr": "Mor ve Ötesi - Cambaz", "de": "Oasis - Wonderwall", "es": "Oasis - Wonderwall", "fr": "Oasis - Wonderwall", "ar": "Cairokee - Matloob Zaeem", "ru": "Oasis - Wonderwall", "uk": "Oasis - Wonderwall"}),
        ("Hey Jude", {"tr": "MFÖ - Ele Güne Karşı", "de": "The Beatles - Hey Jude", "es": "The Beatles - Hey Jude", "fr": "The Beatles - Hey Jude", "ar": "Fairuz - Saalouny", "ru": "The Beatles - Hey Jude", "uk": "The Beatles - Hey Jude"}),
        ("Yesterday", {"tr": "Ajda Pekkan - Petrol", "de": "The Beatles - Yesterday", "es": "The Beatles - Yesterday", "fr": "The Beatles - Yesterday", "ar": "Fairuz - Bint El Shalabiya", "ru": "The Beatles - Yesterday", "uk": "The Beatles - Yesterday"}),
        ("Thriller", {"tr": "Tarkan - Kuzu Kuzu", "de": "Michael Jackson - Thriller", "es": "Michael Jackson - Thriller", "fr": "Michael Jackson - Thriller", "ar": "Amr Diab - Tamally Maak", "ru": "Michael Jackson - Thriller", "uk": "Michael Jackson - Thriller"}),
        ("Billie Jean", {"tr": "Tarkan - Dudu", "de": "Michael Jackson - Billie Jean", "es": "Michael Jackson - Billie Jean", "fr": "Michael Jackson - Billie Jean", "ar": "Amr Diab - Nour El Ein", "ru": "Michael Jackson - Billie Jean", "uk": "Michael Jackson - Billie Jean"}),
        ("Like a Prayer", {"tr": "Sertab Erener - Everyway That I Can", "de": "Madonna - Like a Prayer", "es": "Madonna - Like a Prayer", "fr": "Madonna - Like a Prayer", "ar": "Sherine - Ana Kteer", "ru": "Madonna - Like a Prayer", "uk": "Madonna - Like a Prayer"}),
        ("I Will Survive", {"tr": "Sezen Aksu - Fırtına", "de": "Gloria Gaynor - I Will Survive", "es": "Gloria Gaynor - I Will Survive", "fr": "Gloria Gaynor - I Will Survive", "ar": "Umm Kulthum - Enta Omri", "ru": "Gloria Gaynor - I Will Survive", "uk": "Gloria Gaynor - I Will Survive"}),
        ("My Heart Will Go On", {"tr": "Sertab Erener - Everyway That I Can", "de": "Celine Dion - My Heart Will Go On", "es": "Celine Dion - My Heart Will Go On", "fr": "Celine Dion - My Heart Will Go On", "ar": "Fairuz - Saalouny", "ru": "Celine Dion - My Heart Will Go On", "uk": "Celine Dion - My Heart Will Go On"}),
        ("Eye of the Tiger", {"tr": "Barış Manço - Dağlar Dağlar", "de": "Survivor - Eye of the Tiger", "es": "Survivor - Eye of the Tiger", "fr": "Survivor - Eye of the Tiger", "ar": "Amr Diab - Tamally Maak", "ru": "Survivor - Eye of the Tiger", "uk": "Survivor - Eye of the Tiger"}),
        ("Livin' on a Prayer", {"tr": "Duman - Seni Kendime Sakladım", "de": "Bon Jovi - Livin' on a Prayer", "es": "Bon Jovi - Livin' on a Prayer", "fr": "Bon Jovi - Livin' on a Prayer", "ar": "Cairokee - Matloob Zaeem", "ru": "Bon Jovi - Livin' on a Prayer", "uk": "Bon Jovi - Livin' on a Prayer"}),
        ("Sweet Child O' Mine", {"tr": "Duman - Seni Kendime Sakladım", "de": "Guns N' Roses - Sweet Child O' Mine", "es": "Guns N' Roses - Sweet Child O' Mine", "fr": "Guns N' Roses - Sweet Child O' Mine", "ar": "Cairokee - Matloob Zaeem", "ru": "Guns N' Roses - Sweet Child O' Mine", "uk": "Guns N' Roses - Sweet Child O' Mine"}),
        ("Purple Rain", {"tr": "Barış Manço - Gülpembe", "de": "Prince - Purple Rain", "es": "Prince - Purple Rain", "fr": "Prince - Purple Rain", "ar": "Amr Diab - Nour El Ein", "ru": "Prince - Purple Rain", "uk": "Prince - Purple Rain"}),
        ("Hallelujah", {"tr": "Sezen Aksu - Gülümse", "de": "Leonard Cohen - Hallelujah", "es": "Leonard Cohen - Hallelujah", "fr": "Leonard Cohen - Hallelujah", "ar": "Fairuz - Bint El Shalabiya", "ru": "Leonard Cohen - Hallelujah", "uk": "Leonard Cohen - Hallelujah"}),
        ("Rolling in the Deep", {"tr": "Gülşen - Bangır Bangır", "de": "Adele - Rolling in the Deep", "es": "Adele - Rolling in the Deep", "fr": "Adele - Rolling in the Deep", "ar": "Sherine - Ana Kteer", "ru": "Adele - Rolling in the Deep", "uk": "Adele - Rolling in the Deep"}),
        ("Someone Like You", {"tr": "Gülşen - Bangır Bangır", "de": "Adele - Someone Like You", "es": "Adele - Someone Like You", "fr": "Adele - Someone Like You", "ar": "Sherine - Ana Kteer", "ru": "Adele - Someone Like You", "uk": "Adele - Someone Like You"}),
        ("Shake It Off", {"tr": "Simge - Yankı", "de": "Taylor Swift - Shake It Off", "es": "Taylor Swift - Shake It Off", "fr": "Taylor Swift - Shake It Off", "ar": "Nancy Ajram - Ah W Noss", "ru": "Taylor Swift - Shake It Off", "uk": "Taylor Swift - Shake It Off"}),
        ("Bad Guy", {"tr": "Melike Şahin - Durma Yürüsene", "de": "Billie Eilish - Bad Guy", "es": "Billie Eilish - Bad Guy", "fr": "Billie Eilish - Bad Guy", "ar": "Sherine - Ana Kteer", "ru": "Billie Eilish - Bad Guy", "uk": "Billie Eilish - Bad Guy"}),
        ("Old Town Road", {"tr": "Ezhel - Geceler", "de": "Lil Nas X - Old Town Road", "es": "Lil Nas X - Old Town Road", "fr": "Lil Nas X - Old Town Road", "ar": "Wegz - Dorak Gai", "ru": "Lil Nas X - Old Town Road", "uk": "Lil Nas X - Old Town Road"}),
        ("Uptown Funk", {"tr": "Edis - Martılar", "de": "Bruno Mars - Uptown Funk", "es": "Bruno Mars - Uptown Funk", "fr": "Bruno Mars - Uptown Funk", "ar": "Amr Diab - Tamally Maak", "ru": "Bruno Mars - Uptown Funk", "uk": "Bruno Mars - Uptown Funk"}),
        ("Happy", {"tr": "Edis - Martılar", "de": "Pharrell Williams - Happy", "es": "Pharrell Williams - Happy", "fr": "Pharrell Williams - Happy", "ar": "Amr Diab - Nour El Ein", "ru": "Pharrell Williams - Happy", "uk": "Pharrell Williams - Happy"}),
        ("Despacito", {"tr": "Tarkan - Ölürüm Sana", "de": "Luis Fonsi - Despacito", "es": "Luis Fonsi - Despacito", "fr": "Luis Fonsi - Despacito", "ar": "Amr Diab - Tamally Maak", "ru": "Luis Fonsi - Despacito", "uk": "Luis Fonsi - Despacito"}),
        ("WAP", {"tr": "Simge - Yankı", "de": "Cardi B - WAP", "es": "Cardi B - WAP", "fr": "Cardi B - WAP", "ar": "Balqees - Hala Walla", "ru": "Cardi B - WAP", "uk": "Cardi B - WAP"}),
        ("Drivers License", {"tr": "Melike Şahin - Durma Yürüsene", "de": "Olivia Rodrigo - Drivers License", "es": "Olivia Rodrigo - Drivers License", "fr": "Olivia Rodrigo - Drivers License", "ar": "Sherine - Ana Kteer", "ru": "Olivia Rodrigo - Drivers License", "uk": "Olivia Rodrigo - Drivers License"}),
        ("Watermelon Sugar", {"tr": "Mert Demir - Antidepresan", "de": "Harry Styles - Watermelon Sugar", "es": "Harry Styles - Watermelon Sugar", "fr": "Harry Styles - Watermelon Sugar", "ar": "Mohamed Hamaki - Aady", "ru": "Harry Styles - Watermelon Sugar", "uk": "Harry Styles - Watermelon Sugar"}),
        ("Blinding Lights", {"tr": "Murda - Eh Baba", "de": "The Weeknd - Blinding Lights", "es": "The Weeknd - Blinding Lights", "fr": "The Weeknd - Blinding Lights", "ar": "Wegz - Dorak Gai", "ru": "The Weeknd - Blinding Lights", "uk": "The Weeknd - Blinding Lights"}),
        ("Shape of You", {"tr": "Edis - Martılar", "de": "Ed Sheeran - Shape of You", "es": "Ed Sheeran - Shape of You", "fr": "Ed Sheeran - Shape of You", "ar": "Amr Diab - Tamally Maak", "ru": "Ed Sheeran - Shape of You", "uk": "Ed Sheeran - Shape of You"}),
        ("Perfect", {"tr": "Edis - Martılar", "de": "Ed Sheeran - Perfect", "es": "Ed Sheeran - Perfect", "fr": "Ed Sheeran - Perfect", "ar": "Amr Diab - Nour El Ein", "ru": "Ed Sheeran - Perfect", "uk": "Ed Sheeran - Perfect"}),
        ("Shallow", {"tr": "Gülşen - Bangır Bangır", "de": "Lady Gaga - Shallow", "es": "Lady Gaga - Shallow", "fr": "Lady Gaga - Shallow", "ar": "Sherine - Ana Kteer", "ru": "Lady Gaga - Shallow", "uk": "Lady Gaga - Shallow"}),
        ("Poker Face", {"tr": "Gülşen - Bangır Bangır", "de": "Lady Gaga - Poker Face", "es": "Lady Gaga - Poker Face", "fr": "Lady Gaga - Poker Face", "ar": "Sherine - Ana Kteer", "ru": "Lady Gaga - Poker Face", "uk": "Lady Gaga - Poker Face"}),
        ("Toxic", {"tr": "Hadise - Dum Tek Tek", "de": "Britney Spears - Toxic", "es": "Britney Spears - Toxic", "fr": "Britney Spears - Toxic", "ar": "Nancy Ajram - Ah W Noss", "ru": "Britney Spears - Toxic", "uk": "Britney Spears - Toxic"}),
        ("Wrecking Ball", {"tr": "Simge - Yankı", "de": "Miley Cyrus - Wrecking Ball", "es": "Miley Cyrus - Wrecking Ball", "fr": "Miley Cyrus - Wrecking Ball", "ar": "Balqees - Hala Walla", "ru": "Miley Cyrus - Wrecking Ball", "uk": "Miley Cyrus - Wrecking Ball"}),
        ("Royals", {"tr": "Melike Şahin - Durma Yürüsene", "de": "Lorde - Royals", "es": "Lorde - Royals", "fr": "Lorde - Royals", "ar": "Sherine - Ana Kteer", "ru": "Lorde - Royals", "uk": "Lorde - Royals"}),
        ("Umbrella", {"tr": "Hadise - Dum Tek Tek", "de": "Rihanna - Umbrella", "es": "Rihanna - Umbrella", "fr": "Rihanna - Umbrella", "ar": "Nancy Ajram - Ah W Noss", "ru": "Rihanna - Umbrella", "uk": "Rihanna - Umbrella"}),
        ("Single Ladies", {"tr": "Hadise - Dum Tek Tek", "de": "Beyoncé - Single Ladies", "es": "Beyoncé - Single Ladies", "fr": "Beyoncé - Single Ladies", "ar": "Nancy Ajram - Ah W Noss", "ru": "Beyoncé - Single Ladies", "uk": "Beyoncé - Single Ladies"}),
        ("Hips Don't Lie", {"tr": "Hadise - Dum Tek Tek", "de": "Shakira - Hips Don't Lie", "es": "Shakira - Hips Don't Lie", "fr": "Shakira - Hips Don't Lie", "ar": "Nancy Ajram - Ah W Noss", "ru": "Shakira - Hips Don't Lie", "uk": "Shakira - Hips Don't Lie"}),
    ])

    # actors act_21-60
    NEW["actors"] = adapt_list("act", 21, [
        ("Leonardo DiCaprio", {"tr": "Kıvanç Tatlıtuğ", "de": "Daniel Brühl", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Данila Kozlovsky", "uk": "Dzidzio"}),
        ("Brad Pitt", {"tr": "Burak Özçivit", "de": "Til Schweiger", "es": "Javier Bardem", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Tom Cruise", {"tr": "Kenan İmirzalıoğlu", "de": "Tom Schilling", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Will Smith", {"tr": "Cem Yılmaz", "de": "Elyas M'Barek", "es": "Antonio Banderas", "fr": "Omar Sy", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Denzel Washington", {"tr": "Haluk Bilginer", "de": "Moritz Bleibtreu", "es": "Javier Bardem", "fr": "Omar Sy", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Morgan Freeman", {"tr": "Haluk Bilginer", "de": "Moritz Bleibtreu", "es": "Antonio Banderas", "fr": "Omar Sy", "ar": "Adel Imam", "ru": "Konstantin Khabensky", "uk": "Khabensky"}),
        ("Robert De Niro", {"tr": "Haluk Bilginer", "de": "Moritz Bleibtreu", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Adel Imam", "ru": "Konstantin Khabensky", "uk": "Khabensky"}),
        ("Al Pacino", {"tr": "Haluk Bilginer", "de": "Moritz Bleibtreu", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Adel Imam", "ru": "Konstantin Khabensky", "uk": "Khabensky"}),
        ("Scarlett Johansson", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Jennifer Aniston", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Angelina Jolie", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Julia Roberts", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Meryl Streep", {"tr": "Haluk Bilginer", "de": "Moritz Bleibtreu", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Yousra", "ru": "Chulpan Khamatova", "uk": "Khamatova"}),
        ("Tom Hanks", {"tr": "Cem Yılmaz", "de": "Elyas M'Barek", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Johnny Depp", {"tr": "Kıvanç Tatlıtuğ", "de": "Daniel Brühl", "es": "Javier Bardem", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Christian Bale", {"tr": "Kenan İmirzalıoğlu", "de": "Tom Schilling", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Matt Damon", {"tr": "Burak Özçivit", "de": "Til Schweiger", "es": "Javier Bardem", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("George Clooney", {"tr": "Kıvanç Tatlıtuğ", "de": "Daniel Brühl", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Samuel L. Jackson", {"tr": "Cem Yılmaz", "de": "Elyas M'Barek", "es": "Antonio Banderas", "fr": "Omar Sy", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Harrison Ford", {"tr": "Kenan İmirzalıoğlu", "de": "Tom Schilling", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Arnold Schwarzenegger", {"tr": "Cengiz Bozkurt", "de": "Elyas M'Barek", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Sylvester Stallone", {"tr": "Cengiz Bozkurt", "de": "Elyas M'Barek", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Jackie Chan", {"tr": "Cem Yılmaz", "de": "Elyas M'Barek", "es": "Antonio Banderas", "fr": "Omar Sy", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Dwayne Johnson", {"tr": "Cengiz Bozkurt", "de": "Elyas M'Barek", "es": "Antonio Banderas", "fr": "Omar Sy", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Chris Hemsworth", {"tr": "Burak Özçivit", "de": "Til Schweiger", "es": "Javier Bardem", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Chris Evans", {"tr": "Burak Özçivit", "de": "Til Schweiger", "es": "Javier Bardem", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Robert Downey Jr.", {"tr": "Kıvanç Tatlıtuğ", "de": "Daniel Brühl", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Idris Elba", {"tr": "Kenan İmirzalıoğlu", "de": "Tom Schilling", "es": "Antonio Banderas", "fr": "Omar Sy", "ar": "Ahmed Helmy", "ru": "Danila Kozlovsky", "uk": "Dzidzio"}),
        ("Natalie Portman", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Emma Watson", {"tr": "Afra Saraçoğlu", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Anne Hathaway", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Cate Blanchett", {"tr": "Haluk Bilginer", "de": "Moritz Bleibtreu", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Yousra", "ru": "Chulpan Khamatova", "uk": "Khamatova"}),
        ("Nicole Kidman", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Kate Winslet", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Halle Berry", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Charlize Theron", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Penélope Cruz", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Salma Hayek", {"tr": "Beren Saat", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Lupita Nyong'o", {"tr": "Afra Saraçoğlu", "de": "Nina Chuba", "es": "Penélope Cruz", "fr": "Marion Cotillard", "ar": "Mona Zaki", "ru": "Svetlana Khodchenkova", "uk": "Monatik"}),
        ("Daniel Day-Lewis", {"tr": "Haluk Bilginer", "de": "Moritz Bleibtreu", "es": "Antonio Banderas", "fr": "Vincent Cassel", "ar": "Adel Imam", "ru": "Konstantin Khabensky", "uk": "Khabensky"}),
    ])

    # kidsFirst
    NEW["kidsFirst"] = lit_list([
        ("baby", 1, "Baby", {"tr": "Bebek", "de": "Baby", "ar": "طفل", "es": "Bebé", "fr": "Bébé", "ru": "Малыш", "uk": "Малюк"}),
        ("bye", 1, "Bye-bye", {"tr": "Hoşça kal", "de": "Tschüss", "ar": "مع السلامة", "es": "Adiós", "fr": "Au revoir", "ru": "Пока", "uk": "Бувай"}),
        ("hello_k", 1, "Hello", {"tr": "Merhaba", "de": "Hallo", "ar": "مرحبا", "es": "Hola", "fr": "Bonjour", "ru": "Привет", "uk": "Привіт"}),
        ("please_k", 1, "Please", {"tr": "Lütfen", "de": "Bitte", "ar": "من فضلك", "es": "Por favor", "fr": "S'il te plaît", "ru": "Пожалуйста", "uk": "Будь ласка"}),
        ("thank_you_k", 1, "Thank you", {"tr": "Teşekkürler", "de": "Danke", "ar": "شكرا", "es": "Gracias", "fr": "Merci", "ru": "Спасибо", "uk": "Дякую"}),
        ("sorry_k", 1, "Sorry", {"tr": "Özür dilerim", "de": "Entschuldigung", "ar": "آسف", "es": "Lo siento", "fr": "Pardon", "ru": "Извини", "uk": "Вибач"}),
        ("yes_k", 1, "Yes", {"tr": "Evet", "de": "Ja", "ar": "نعم", "es": "Sí", "fr": "Oui", "ru": "Да", "uk": "Так"}),
        ("no_k", 1, "No", {"tr": "Hayır", "de": "Nein", "ar": "لا", "es": "No", "fr": "Non", "ru": "Нет", "uk": "Ні"}),
        ("more_k", 1, "More", {"tr": "Daha", "de": "Mehr", "ar": "المزيد", "es": "Más", "fr": "Encore", "ru": "Ещё", "uk": "Ще"}),
        ("eat_k", 1, "Eat", {"tr": "Ye", "de": "Essen", "ar": "كل", "es": "Comer", "fr": "Manger", "ru": "Есть", "uk": "Їсти"}),
        ("drink_k", 1, "Drink", {"tr": "İç", "de": "Trinken", "ar": "اشرب", "es": "Beber", "fr": "Boire", "ru": "Пить", "uk": "Пити"}),
        ("play_k", 1, "Play", {"tr": "Oyna", "de": "Spielen", "ar": "العب", "es": "Jugar", "fr": "Jouer", "ru": "Играть", "uk": "Грати"}),
        ("read_k", 1, "Read", {"tr": "Oku", "de": "Lesen", "ar": "اقرأ", "es": "Leer", "fr": "Lire", "ru": "Читать", "uk": "Читати"}),
        ("draw_k", 1, "Draw", {"tr": "Çiz", "de": "Malen", "ar": "ارسم", "es": "Dibujar", "fr": "Dessiner", "ru": "Рисовать", "uk": "Малювати"}),
        ("sing_k", 1, "Sing", {"tr": "Şarkı söyle", "de": "Singen", "ar": "غنّ", "es": "Cantar", "fr": "Chanter", "ru": "Петь", "uk": "Співати"}),
        ("dance_k", 1, "Dance", {"tr": "Dans et", "de": "Tanzen", "ar": "ارقص", "es": "Bailar", "fr": "Danser", "ru": "Танцевать", "uk": "Танцювати"}),
        ("walk_k", 1, "Walk", {"tr": "Yürü", "de": "Gehen", "ar": "امش", "es": "Caminar", "fr": "Marcher", "ru": "Ходить", "uk": "Ходити"}),
        ("sit_k", 1, "Sit", {"tr": "Otur", "de": "Sitzen", "ar": "اجلس", "es": "Sentarse", "fr": "S'asseoir", "ru": "Сидеть", "uk": "Сидіти"}),
        ("stand_k", 1, "Stand", {"tr": "Ayağa kalk", "de": "Stehen", "ar": "قف", "es": "Levantarse", "fr": "Se lever", "ru": "Вставать", "uk": "Вставати"}),
        ("clap_k", 1, "Clap", {"tr": "Alkışla", "de": "Klatschen", "ar": "صفّق", "es": "Aplaudir", "fr": "Applaudir", "ru": "Хлопать", "uk": "Плескати"}),
        ("wave_k", 1, "Wave", {"tr": "El salla", "de": "Winken", "ar": "لوّح", "es": "Saludar", "fr": "Saluer", "ru": "Махать", "uk": "Махати"}),
        ("kiss_k", 1, "Kiss", {"tr": "Öpücük", "de": "Kuss", "ar": "قبلة", "es": "Beso", "fr": "Bisou", "ru": "Поцелуй", "uk": "Поцілунок"}),
        ("toy_k", 1, "Toy", {"tr": "Oyuncak", "de": "Spielzeug", "ar": "لعبة", "es": "Juguete", "fr": "Jouet", "ru": "Игрушка", "uk": "Іграшка"}),
        ("bottle_k", 1, "Bottle", {"tr": "Biberon", "de": "Flasche", "ar": "زجاجة", "es": "Biberón", "fr": "Biberon", "ru": "Бутылочка", "uk": "Пляшечка"}),
        ("diaper_k", 1, "Diaper", {"tr": "Bez", "de": "Windel", "ar": "حفاض", "es": "Pañal", "fr": "Couche", "ru": "Подгузник", "uk": "Підгузок"}),
        ("stroller_k", 1, "Stroller", {"tr": "Bebek arabası", "de": "Kinderwagen", "ar": "عربة", "es": "Cochecito", "fr": "Poussette", "ru": "Коляска", "uk": "Коляска"}),
        ("pacifier_k", 1, "Pacifier", {"tr": "Emzik", "de": "Schnuller", "ar": "لهاية", "es": "Chupete", "fr": "Tétine", "ru": "Сosка", "uk": "Сosка"}),
        ("blanket_k", 1, "Blanket", {"tr": "Battaniye", "de": "Decke", "ar": "بطانية", "es": "Manta", "fr": "Couverture", "ru": "Одеяло", "uk": "Ковдра"}),
        ("teddy_k", 1, "Teddy bear", {"tr": "Oyuncak ayı", "de": "Teddybär", "ar": "دبدوب", "es": "Osito", "fr": "Nounours", "ru": "Плюшевый мишка", "uk": "Ведмедик"}),
        ("blocks_k", 1, "Building blocks", {"tr": "Bloklar", "de": "Bausteine", "ar": "مكعبات", "es": "Bloques", "fr": "Cubes", "ru": "Кубики", "uk": "Кубики"}),
        ("bath_k", 1, "Bath", {"tr": "Banyo", "de": "Bad", "ar": "حمام", "es": "Baño", "fr": "Bain", "ru": "Купание", "uk": "Купання"}),
        ("brush_teeth_k", 1, "Brush teeth", {"tr": "Diş fırçala", "de": "Zähne putzen", "ar": "نظف أسنانك", "es": "Cepillar dientes", "fr": "Se brosser les dents", "ru": "Чистить зубы", "uk": "Чистити зуби"}),
        ("grandma_k", 1, "Grandma", {"tr": "Babaanne", "de": "Oma", "ar": "جدة", "es": "Abuela", "fr": "Mamie", "ru": "Бабушка", "uk": "Бабуся"}),
        ("grandpa_k", 1, "Grandpa", {"tr": "Dedem", "de": "Opa", "ar": "جد", "es": "Abuelo", "fr": "Papi", "ru": "Дедушка", "uk": "Дідусь"}),
        ("sister_k", 1, "Sister", {"tr": "Kız kardeş", "de": "Schwester", "ar": "أخت", "es": "Hermana", "fr": "Sœur", "ru": "Сестра", "uk": "Сестра"}),
        ("brother_k", 1, "Brother", {"tr": "Erkek kardeş", "de": "Bruder", "ar": "أخ", "es": "Hermano", "fr": "Frère", "ru": "Брат", "uk": "Брат"}),
        ("friend_k", 1, "Friend", {"tr": "Arkadaş", "de": "Freund", "ar": "صديق", "es": "Amigo", "fr": "Ami", "ru": "Друг", "uk": "Друг"}),
        ("happy_k", 1, "Happy", {"tr": "Mutlu", "de": "Glücklich", "ar": "سعيد", "es": "Feliz", "fr": "Content", "ru": "Счастливый", "uk": "Щасливий"}),
        ("sad_k", 1, "Sad", {"tr": "Üzgün", "de": "Traurig", "ar": "حزين", "es": "Triste", "fr": "Triste", "ru": "Грустный", "uk": "Сумний"}),
        ("tired_k", 1, "Tired", {"tr": "Yorgun", "de": "Müde", "ar": "متعب", "es": "Cansado", "fr": "Fatigué", "ru": "Усталый", "uk": "Втомлений"}),
        ("hungry_k", 1, "Hungry", {"tr": "Aç", "de": "Hungrig", "ar": "جائع", "es": "Hambriento", "fr": "Affamé", "ru": "Голодный", "uk": "Голодний"}),
    ])

    # Import part 2 for remaining decks
    from _build_all_decks_ext2 import extend2
    extend2(NEW, lit, lit_list, adapt, adapt_list, fill, card, sc, t)
