#!/usr/bin/env python3
"""Append 40 new cards to partyFlirty, karaoke, bachelor, accents, celebImpressions."""
import json
from pathlib import Path

LOCALES = [
    "en", "tr", "de", "ar", "be", "ca", "cs", "da", "el", "es",
    "fi", "fil", "fr", "hr", "id", "it", "ms", "nb", "nl", "pl",
    "pt", "ro", "ru", "sv", "uk",
]

DECKS_DIR = Path(__file__).resolve().parent.parent / "Charades" / "Resources" / "Decks"


def card(key, difficulty, translations):
    assert set(translations.keys()) == set(LOCALES), f"{key}: got {set(translations.keys()) ^ set(LOCALES)}"
    return {"k": key, "d": difficulty, "t": {loc: translations[loc] for loc in LOCALES}}


def t(*args):
    return dict(zip(LOCALES, args))


def append_deck(deck_id, new_cards):
    path = DECKS_DIR / f"{deck_id}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    existing_keys = {c["k"] for c in data["cards"]}
    for c in new_cards:
        if c["k"] in existing_keys:
            raise ValueError(f"{deck_id}: duplicate key {c['k']}")
    data["cards"].extend(new_cards)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return len(data["cards"])


# ── partyFlirty (40) ──────────────────────────────────────────────────────────

PARTY_FLIRTY = [
    card("cheek_kiss", 1, t("Cheek kiss", "Yanaktan öpücük", "Wangenkuss", "قبلة على الخد", "Пацалунак у шчоку", "Petó a la galta", "Polibek na tvář", "Kindkys", "Φιλί στο μάγουλο", "Beso en la mejilla", "Poskipusu", "Halik sa pisngi", "Bisou sur la joue", "Poljubac na obraz", "Cium pipi", "Bacio sulla guancia", "Cium pipi", "Kinnkyss", "Wangenkus", "Pocałunek w policzek", "Beijo na bochecha", "Sărut pe obraz", "Поцелуй в щёку", "Kindpuss", "Поцілунок у щоку")),
    card("hand_kiss", 1, t("Kiss a hand", "Elden öp", "Hand küssen", "قبّل اليد", "Пацалаваць руку", "Besar la mà", "Políbit ruku", "Kysse en hånd", "Φίλησε το χέρι", "Besar la mano", "Suudella kättä", "Halikan ang kamay", "Baiser la main", "Poljubiti ruku", "Cium tangan", "Baciare la mano", "Cium tangan", "Kysse en hånd", "Hand kussen", "Pocałować dłoń", "Beijar a mão", "Sărută mâna", "Поцеловать руку", "Kyssa hand", "Поцілувати руку")),
    card("spin_in_arms", 1, t("Spin in arms", "Kollarında döndür", "Im Arm drehen", "دور في الذراعين", "Круціць на руках", "Girar als braços", "Točit v náručí", "Dreje i armene", "Γύρισε στα χέρια", "Girar en brazos", "Pyöritä sylissä", "Paikutin sa bisig", "Tourner dans les bras", "Okrenuti u naručju", "Putar di pelukan", "Girare tra le braccia", "Pusing dalam pelukan", "Svirre i armene", "Draaien in armen", "Obrócić w ramionach", "Girar nos braços", "Învârte în brațe", "Крутить на руках", "Snurra i famnen", "Крутити на руках")),
    card("whisper_secret", 1, t("Whisper a secret", "Kulağa sır fısılda", "Ein Geheimnis flüstern", "همس بسر", "Шапнуць сакрэт", "Xiuxiuejar un secret", "Zašeptat tajemství", "Hviske en hemmelighed", "Ψιθύρισε ένα μυστικό", "Susurrar un secreto", "Kuiskaa salaisuus", "Bulungan ng sikreto", "Chuchoter un secret", "Šapnuti tajnu", "Bisikkan rahasia", "Sussurrare un segreto", "Bisik rahsia", "Hviske en hemmelighet", "Een geheim fluisteren", "Szeptać sekret", "Sussurrar um segredo", "Șoptește un secret", "Шепнуть секрет", "Viska en hemlighet", "Шепнути секрет")),
    card("offer_jacket", 1, t("Offer your jacket", "Ceketini ver", "Jacke anbieten", "قدّم سترتك", "Прапанаваць куртку", "Oferir la jaqueta", "Nabídnout bundu", "Tilbyde sin jakke", "Πρόσφερε το σακάκι", "Ofrecer la chaqueta", "Tarjoa takkisi", "Ialok ang jacket", "Offrir son manteau", "Ponuditi jaknu", "Tawarkan jaket", "Offrire la giacca", "Tawarkan jaket", "Tilby jakka", "Jas aanbieden", "Zaoferować kurtkę", "Oferecer o casaco", "Oferă-ți jacheta", "Предложить куртку", "Erbjuda jacka", "Запропонувати куртку")),
    card("share_dessert", 1, t("Share dessert", "Tatlı paylaş", "Dessert teilen", "شارك الحلوى", "Падзяліць дэсерт", "Compartir un postre", "Sdílet dezert", "Dele dessert", "Μοιράσου επιδόρπιο", "Compartir postre", "Jakaa jälkiruoka", "Magbahagi ng dessert", "Partager un dessert", "Dijeliti desert", "Berbagi makanan penutup", "Condividere un dolce", "Kongsi pencuci mulut", "Dele dessert", "Dessert delen", "Dzielić się deserem", "Partilhar sobremesa", "Împarte desertul", "Поделиться десертом", "Dela efterrätt", "Поділитися десертом")),
    card("fix_tie", 1, t("Fix a tie", "Kravat düzelt", "Krawatte richten", "عدّل ربطة العنق", "Папраўляць крават", "Arreglar la corbata", "Upravit kravatu", "Rette slips", "Διόρθωσε γραβάτα", "Arreglar la corbata", "Oikaise solmio", "Ayusin ang kurbata", "Ajuster la cravate", "Popraviti kravatu", "Rapikan dasi", "Sistemare la cravatta", "Betulkan tali leher", "Rette slips", "Stropdas rechtzetten", "Poprawić krawat", "Arrumar a gravata", "Aranjează cravata", "Поправить галстук", "Rätta slips", "Виправити краватку")),
    card("toast_champagne", 1, t("Champagne toast", "Şampanya kadehi", "Champagner anstoßen", "نخب بالشمبانيا", "Тост шампанскім", "Brindar amb cava", "Přípití se šampaňským", "Skål med champagne", "Πρόποση με σαμπάνια", "Brindar con champán", "Samppanjapöytä", "Toast ng champagne", "Trinquer au champagne", "Čaša šampanjca", "Bersulang sampanye", "Brindisi con champagne", "Bersulang champagne", "Skål med champagne", "Proosten met champagne", "Toast szampanem", "Brinde com champanhe", "Toast cu șampanie", "Тост шампанским", "Skåla med champagne", "Тост шампанським")),
    card("playful_nudge", 1, t("Playful nudge", "Şakacı dirsek", "Verspielter Ellbogenstoß", "دفعة لطيفة", "Гульлівы падштурх", "Cop de colze juganer", "Hravé šťouchnutí", "Legende albue", "Παιχνιδιάρικο σπρώξιμο", "Codazo juguetón", "Leikkisä kyynärpää", "Kalmot na nakakatuwa", "Coup de coude taquin", "Razigrani lakat", "Sikutan playful", "Gomito giocoso", "Tolak playful", "Leken albue", "Speels elleboogstootje", "Figlarny szturchnięcie", "Cotovelada brincalhona", "Ghiont jucăuș", "Игривый локоть", "Lekfull armbåge", "Грайливий лікоть")),
    card("mirror_dance", 1, t("Mirror dance moves", "Aynı dans hareketleri", "Tanzbewegungen spiegeln", "قلّد حركات الرقص", "Паўтараць рухі танца", "Copiar els passos de ball", "Zrcadlit taneční kroky", "Spejle dansebevægelser", "Αντέγραψε χορευτικές κινήσεις", "Imitar pasos de baile", "Peilaa tanssiliikkeitä", "Gayahin ang sayaw", "Imiter les pas de danse", "Preslikati plesne pokrete", "Cerminkan gerakan tari", "Specchiare i passi di danza", "Cermin gerakan tarian", "Speile dansetrinn", "Dansbewegingen spiegelen", "Naśladować ruchy tańca", "Espelhar passos de dança", "Imită mișcările de dans", "Повторять танцевальные движения", "Spegla danssteg", "Дзеркалити танцювальні рухи")),
    card("draw_heart_hand", 1, t("Draw heart on hand", "Ele çiz kalp", "Herz auf die Hand malen", "ارسم قلباً على اليد", "Намаляваць сэрца на руцэ", "Dibuixar un cor a la mà", "Nakreslit srdce na ruku", "Tegne hjerte på hånd", "Ζωγράφισε καρδιά στο χέρι", "Dibujar corazón en la mano", "Piirrä sydän käteen", "Gumuhit ng puso sa kamay", "Dessiner un cœur sur la main", "Nacrtati srce na ruci", "Gambar hati di tangan", "Disegnare un cuore sulla mano", "Lukis hati di tangan", "Tegne hjerte på hånd", "Hart op hand tekenen", "Narysować serce na dłoni", "Desenhar coração na mão", "Desenează inimă pe mână", "Нарисовать сердце на руке", "Rita hjärta på hand", "Намалювати серце на руці")),
    card("clink_glasses", 1, t("Clink glasses", "Kadeh tokuştur", "Gläser anstoßen", "قرع الكؤوس", "Прыгнясці бакалы", "Brindar amb cop de copes", "Cinknout sklenicemi", "Skåle med glass", "Χτύπα ποτήρια", "Chocar copas", "Kilauttaa laseja", "Mag-tink ng baso", "Trinquer les verres", "Udariti čašama", "Bentur gelas", "Tintinnare i bicchieri", "Bentur gelas", "Skåle med glass", "Glazen tikken", "Stuknąć kieliszkami", "Brindar com copos", "Ciocni paharele", "Чокнуться бокалами", "Skåla med glas", "Дзвінко пляшками")),
    card("dance_request", 1, t("Ask to dance", "Dans teklif et", "Zum Tanzen auffordern", "ادعُ للرقص", "Запрасіць на танец", "Convidar a ballar", "Pozvat k tanci", "Invitere til dans", "Πρόσκληση για χορό", "Invitar a bailar", "Pyytää tanssiin", "Anyayahan sa sayaw", "Inviter à danser", "Pozvati na ples", "Ajakan menari", "Invitare a ballare", "Jemput menari", "Invitere til dans", "Uitnodigen om te dansen", "Zaprosić do tańca", "Convidar para dançar", "Invită la dans", "Пригласить на танец", "Bjuda upp till dans", "Запросити на танець")),
    card("forehead_kiss", 1, t("Forehead kiss", "Alından öpücük", "Stirnkuss", "قبلة على الجبين", "Пацалунак у лоб", "Petó al front", "Polibek na čelo", "Pandekys", "Φιλί στο μέτωπο", "Beso en la frente", "Otsasuukko", "Halik sa noo", "Bisou sur le front", "Poljubac na čelo", "Cium kening", "Bacio sulla fronte", "Cium dahi", "Pannekys", "Voorhoofdkus", "Pocałunek w czoło", "Beijo na testa", "Sărut pe frunte", "Поцелуй в лоб", "Pannpuss", "Поцілунок у чоло")),
    card("rose_in_teeth", 2, t("Rose between teeth", "Dişlerde gül", "Rose zwischen den Zähnen", "وردة بين الأسنان", "Ружа ў зубах", "Rosa entre les dents", "Růže mezi zuby", "Rose mellem tænderne", "Τριαντάφυλλο στα δόντια", "Rosa entre los dientes", "Ruusu hampaissa", "Rosas sa ngipin", "Rose entre les dents", "Ruža između zuba", "Mawar di gigi", "Rosa tra i denti", "Mawar di gigi", "Rose mellom tennene", "Roos tussen tanden", "Róża między zębami", "Rosa entre os dentes", "Trandafir între dinți", "Роза в зубах", "Ros mellan tänderna", "Троянда в зубах")),
    card("share_headphones", 1, t("Share headphones", "Kulaklık paylaş", "Kopfhörer teilen", "شارك السماعات", "Падзяліць навушнікі", "Compartir auriculars", "Sdílet sluchátka", "Dele hovedtelefoner", "Μοιράσου ακουστικά", "Compartir auriculares", "Jakaa kuulokkeet", "Magbahagi ng headphones", "Partager un casque", "Dijeliti slušalice", "Berbagi earphone", "Condividere le cuffie", "Kongsi fon telinga", "Dele hodetelefoner", "Koptelefoon delen", "Dzielić się słuchawkami", "Partilhar auscultadores", "Împarte căștile", "Поделиться наушниками", "Dela hörlurar", "Поділитися навушниками")),
    card("wave_from_crowd", 1, t("Wave from across the room", "Karşıdan el salla", "Aus der Ferne winken", "لوّح من بعيد", "Памахаць здалёку", "Fer un senyal des de lluny", "Zamávat z druhé strany", "Vinke på tværs af rummet", "Χαιρέτα από μακριά", "Saludar desde lejos", "Heiluttaa huoneen poikki", "Kumaway mula sa malayo", "Faire signe de loin", "Mахнути iz daljine", "Melambai dari jauh", "Salutare da lontano", "Lambai dari jauh", "Vinke på tvers av rommet", "Zwaaien van ver", "Pomachać z drugiej strony", "Acenar de longe", "Salută de departe", "Помахать издалека", "Vinka över rummet", "Помахати здалеку")),
    card("laugh_together", 1, t("Laugh together", "Birlikte gül", "Zusammen lachen", "اضحكوا معاً", "Разам смяяцца", "Riar junts", "Smát se spolu", "Grine sammen", "Γελάστε μαζί", "Reír juntos", "Nauraa yhdessä", "Magtawan nang sabay", "Rire ensemble", "Smijati se zajedno", "Tertawa bersama", "Ridere insieme", "Ketawa bersama", "Le sammen", "Samen lachen", "Śmiać się razem", "Rir juntos", "Râdeți împreună", "Смеяться вместе", "Skratta tillsammans", "Сміятися разом")),
    card("hand_on_waist", 1, t("Hand on waist", "Belde el", "Hand an der Taille", "يد على الخصر", "Рука на талii", "Mà a la cintura", "Ruka v pase", "Hånd på taljen", "Χέρι στη μέση", "Mano en la cintura", "Käsi vyötäröllä", "Kamay sa baywang", "Main sur la taille", "Ruka na struku", "Tangan di pinggang", "Mano in vita", "Tangan di pinggang", "Hånd på midjen", "Hand op taille", "Ręka na talii", "Mão na cintura", "Mână pe talie", "Рука на талии", "Hand på midjan", "Рука на талії")),
    card("lift_in_toast", 1, t("Lift partner in a toast", "Kaldır partneri", "Partner hochheben zum Anstoßen", "ارفع الشريك للنخب", "Падняць партнёра для тосту", "Aixecar el company per brindar", "Zvednout partnera na přípitek", "Løfte partner til skål", "Σήκωσε τον σύντροφο", "Levantar al compañero", "Nosta kumppani maljaan", "Itaas ang partner", "Soulever son partenaire", "Podignuti partnera", "Angkat pasangan", "Sollevare il partner", "Angkat pasangan", "Løfte partner", "Partner optillen", "Podnieść partnera", "Levantar o parceiro", "Ridică partenerul", "Поднять партнёра", "Lyfta partnern", "Підняти партнера")),
    card("eye_contact_toast", 1, t("Toast with eye contact", "Göz temaslı kadeh", "Anstoßen mit Blickkontakt", "نخب مع التواصل البصري", "Тост з зрокам", "Brindar amb contacte visual", "Přípití s očním kontaktem", "Skål med øjenkontakt", "Πρόποση με επαφή ματιών", "Brindar con contacto visual", "Malja silmäkontaktilla", "Toast na may eye contact", "Trinquer avec contact visuel", "Čaša uz kontakt očima", "Bersulang dengan kontak mata", "Brindisi con contatto visivo", "Bersulang dengan kontak mata", "Skål med øyekontakt", "Proosten met oogcontact", "Toast z kontaktem wzrokowym", "Brinde com contacto visual", "Toast cu contact vizual", "Тост с зрительным контактом", "Skåla med ögonkontakt", "Тост із зоровим контактом")),
    card("playful_chase", 1, t("Playful chase", "Şakacı kovalamaca", "Verspielte Verfolgung", "مطاردة لطيفة", "Гульлівая пагоня", "Persecució juganera", "Hravé honění", "Legende jagt", "Παιχνιδιάρικη καταδίωξη", "Persecución juguetona", "Leikkisä jahtaus", "Nakakatuwang habulan", "Course taquine", "Razigrana potjera", "Kejar-kejaran playful", "Inseguimento giocoso", "Kejar-kejaran playful", "Leken jakt", "Speelse achtervolging", "Figlarna pogoń", "Perseguição brincalhona", "Urmărire jucăușă", "Игривая погоня", "Lekfull jakt", "Грайлива погоня")),
    card("pin_corsage", 2, t("Pin a corsage", "Korsaj tak", "Corsage anstecken", "ثبّت زهرة", "Прикалываць бутоньерку", "Posar un ram", "Připnout korsáž", "Fastgøre corsage", "Καρφίτσωσε μπουκέτο", "Colocar un ramillete", "Kiinnitä korsetti", "Ikabit ang corsage", "Épingler un corsage", "Prikvačiti corsage", "Sematkan korsase", "Appuntare un corsage", "Pin korsase", "Fest corsage", "Corsage vastpinnen", "Przypiąć korsaż", "Prender corsage", "Prinde corsajul", "Приколоть бутоньерку", "Fästa corsage", "Прикріпити бутоньєрку")),
    card("feed_strawberry", 1, t("Feed a strawberry", "Çilek yedir", "Erdbeere füttern", "قدّم فراولة", "Пакорміць клубніцай", "Donar una maduixa", "Nakrmit jahodou", "Fodre med jordbær", "Δώσε φράουλα", "Dar una fresa", "Syötä mansikka", "Pakain ng strawberry", "Donner une fraise", "Hraniti jagodom", "Suapkan stroberi", "Dare una fragola", "Suapkan strawberi", "Mate jordbær", "Aardbei voeren", "Nakarmić truskawką", "Dar um morango", "Hrănește cu căpșună", "Угостить клубникой", "Mata jordgubbe", "Годувати полуницею")),
    card("share_scarf", 1, t("Share a scarf", "Atkı paylaş", "Schal teilen", "شارك وشاحاً", "Падзяліць шарф", "Compartir una bufanda", "Sdílet šálu", "Dele et tørklæde", "Μοιράσου κασκόλ", "Compartir bufanda", "Jakaa huivi", "Magbahagi ng scarf", "Partager une écharpe", "Dijeliti šal", "Berbagi syal", "Condividere una sciarpa", "Kongsi selendang", "Dele skjerf", "Sjaal delen", "Dzielić się szalikiem", "Partilhar cachecol", "Împarte eșarfa", "Поделиться шарфом", "Dela halsduk", "Поділитися шарфом")),
    card("photo_booth_kiss", 1, t("Photo booth kiss pose", "Foto kabin öpücük pozu", "Kuss-Pose im Fotobox", "وضعية قبلة في كشك الصور", "Паза пацалунку ў фотабудцы", "Posar un petó al fotomató", "Póza polibku ve fotobudce", "Kys-pose i fotoboks", "Πόζα φιλιού σε φωτογραφικό", "Pose de beso en cabina", "Suukko pose photoboothissa", "Kiss pose sa photo booth", "Pose bisou en cabine photo", "Poziranje poljupca u photo boothu", "Pose cium di photo booth", "Posa bacio nel photo booth", "Pose cium di photo booth", "Kys-pose i fotoboks", "Kuspose in fotohokje", "Poza pocałunku w photo booth", "Pose de beijo na cabine", "Poză sărut photo booth", "Поза поцелуя в фотобудке", "Kysspose i fotobås", "Поза поцілунку у фотобудці")),
    card("victory_dip", 1, t("Victory dip", "Zafer eğilmesi", "Siegestauch", "انحناء النصر", "Перамогны наклон", "Inclinació de victòria", "Vítězný dip", "Sejr-dip", "Νίκη dip", "Inclinación de victoria", "Voitto-dippi", "Victory dip", "Dip de victoire", "Pobjedni dip", "Victory dip", "Dip di vittoria", "Victory dip", "Seier-dip", "Overwinningsdip", "Zwycięski dip", "Dip de vitória", "Dip de victorie", "Победный наклон", "Seger-dip", "Переможний dip")),
    card("tie_shoelace", 1, t("Tie a shoelace", "Ayakkabı bağı bağla", "Schnürsenkel binden", "اربط الحذاء", "Завязаць шнурок", "Lligar una sabata", "Zavázat tkaničku", "Binde snørebånd", "Δέσε κορδόνι", "Atar un cordón", "Sido kengännauha", "Itali ang sintas", "Lacer une chaussure", "Vezati pertlu", "Ikat tali sepatu", "Allacciare una scarpa", "Ikat tali kasut", "Knyte sko", "Veters strikken", "Związać sznurówkę", "Atar um cadarço", "Leagă șiretul", "Завязать шнурок", "Knyta sko", "Зав'язати шнурок")),
    card("pick_up_spin", 1, t("Pick up and spin", "Kaldır ve döndür", "Hochheben und drehen", "ارفع وادر", "Падняць і круціць", "Aixecar i girar", "Zvednout a otočit", "Løfte og dreje", "Σήκωσε και γύρισε", "Levantar y girar", "Nosta ja pyöritä", "Buhatin at paikutin", "Soulever et tourner", "Podignuti i okrenuti", "Angkat dan putar", "Sollevare e girare", "Angkat dan pusing", "Løfte og snurre", "Optillen en draaien", "Podnieść i obrócić", "Levantar e girar", "Ridică și învârte", "Поднять и крутить", "Lyfta och snurra", "Підняти і крутити")),
    card("napkin_phone_number", 2, t("Write number on napkin", "Peçeteye numara yaz", "Nummer auf Serviette schreiben", "اكتب الرقم على منديل", "Напісаць нумар на сурвеце", "Escriure el número al tovalló", "Napsat číslo na ubrousek", "Skrive nummer på serviet", "Γράψε αριθμό σε χαρτομάντιλο", "Escribir número en servilleta", "Kirjoita numero lautasliinaan", "Isulat ang numero sa napkin", "Écrire un numéro sur une serviette", "Napisati broj na salveta", "Tulis nomor di serbet", "Scrivere il numero sul tovagliolo", "Tulis nombor di tisu", "Skrive nummer på serviett", "Nummer op servet schrijven", "Napisać numer na serwetce", "Escrever número no guardanapo", "Scrie numărul pe șervețel", "Написать номер на салфетке", "Skriva nummer på servett", "Написати номер на серветці")),
    card("steal_hat_flirt", 1, t("Steal a hat flirtatiously", "Şapka çal flört", "Verspielt einen Hut klauen", "سرق قبعة بلطف", "Украсці шапку з кокетствам", "Robar un barret coquetament", "Ukrást klobouk koketně", "Stjæle en hat flirtende", "Κλέψε καπέλο φλερτάροντας", "Robar un sombrero coquetamente", "Varasta hattu flirttaillen", "Magnakaw ng sombrero", "Voler un chapeau coquettement", "Ukrasti šešir koketno", "Curi topi dengan genit", "Rubare un cappello flirtando", "Curi topi genit", "Stjele en hatt flirtende", "Speels een hoed stelen", "Ukradnąć kapelusz zalotnie", "Roubar um chapéu flirtando", "Fură pălăria flirtez", "Украсть шляпу кокетливо", "Stjäla en hatt flirtigt", "Вкрасти капелюх кокетливо")),
    card("slow_dance_close", 1, t("Slow dance close", "Yakın yavaş dans", "Langsam eng tanzen", "رقص بطيء قريب", "Павольны блізкі танец", "Ballar a prop a poc a poc", "Pomalu tančit blízko", "Langsom dans tæt", "Αργός χορός κοντά", "Bailar lento cerca", "Hidas tanssi lähellä", "Mabagal na sayaw malapit", "Danser lent près l'un de l'autre", "Polagani ples blizu", "Dansa lambat dekat", "Ballo lento vicino", "Tarian perlahan dekat", "Langsom dans nær", "Langzaam dicht dansen", "Powolny taniec blisko", "Dança lenta perto", "Dans lent aproape", "Медленный близкий танец", "Långsam dans nära", "Повільний близький танець")),
    card("compliment_smile", 1, t("Compliment a smile", "Gülümsemeye iltifat", "Ein Lächeln loben", "أثنِ على الابتسامة", "Пахваліць усмешку", "Complimentar un somriure", "Pochválit úsměv", "Komplimentere et smil", "Κάνε κομπλιμέντο στο χαμόγελο", "Halagar una sonrisa", "Kehua hymyä", "Purihin ang ngiti", "Complimenter un sourire", "Komplimentirati osmijeh", "Puji senyum", "Complimentare un sorriso", "Puji senyuman", "Komplimentere et smil", "Een glimlach complimenteren", "Pochwalić uśmiech", "Elogiar um sorriso", "Complimentează zâmbetul", "Похвалить улыбку", "Komplimera ett leende", "Похвалити посмішку")),
    card("air_guitar_serenade", 1, t("Air guitar serenade", "Hava gitarı serenat", "Luftgitarren-Serenade", "سеренada بغيتار وهمي", "Сerenada на паветранай гітары", "Serenata amb guitarra invisible", "Serenáda na vzdušnou kytaru", "Luftguitar-serenade", "Σερενάτα με φανταστική κιθάρα", "Serenata con guitarra invisible", "Ilmakitariserenadi", "Air guitar serenade", "Sérénade à la guitare imaginaire", "Serenada na zračnu gitaru", "Serenade gitar udara", "Serenata con chitarra immaginaria", "Serenade gitar udara", "Luftgitar-serenade", "Luchtgitarenade", "Serenada na gitarze powietrznej", "Serenata com guitarra imaginária", "Serenadă cu chitară imaginară", "Сerenada на воображаемой гитаре", "Luftgitarrserenad", "Serenade на повітряній гітарі")),
    card("promise_ring", 2, t("Promise ring gesture", "Söz yüzüğü jesti", "Verlobungsring-Geste", "إيماءة خاتم الوعد", "Жэст кольца абяцання", "Gest d'anell de promesa", "Gesto prstenu slibu", "Løfte-ring gestus", "Χειρονομία δαχτυλίδι υπόσχεσης", "Gesto de anillo de promesa", "Lupaus-sormus ele", "Promise ring gesture", "Geste de bague de promesse", "Gesta prstena obećanja", "Gest cincin janji", "Gesto anello promessa", "Gerak cincin janji", "Løftering-gestus", "Belofte-ring gebaar", "Gest pierścionka obietnicy", "Gesto de anel de promessa", "Gest inel de promisiune", "Жест кольца обещания", "Löfte-ring gest", "Жест кільця обіцянки")),
    card("sunset_stroll", 1, t("Sunset stroll arm in arm", "Gün batımı yürüyüşü", "Spaziergang bei Sonnenuntergang", "نزهة عند الغروب", "Прагулка на заходе", "Passeig al capvespre", "Procházka při západu slunce", "Solnedgangstur arm i arm", "Περίπατος στο ηλιοβασίλεμα", "Paseo al atardecer", "Auringonlaskukävely", "Lakad sa sunset", "Promenade au coucher du soleil", "Šetnja pri zalasku", "Jalan-jalan saat senja", "Passeggiata al tramonto", "Berjalan waktu senja", "Solnedgangstur arm i arm", "Avondwandeling arm in arm", "Spacer o zachodzie", "Passeio ao pôr do sol", "Plimbare la apus", "Прогулка на закате", "Solnedgångspromenad", "Прогулянка на заході")),
    card("spin_the_bottle", 1, t("Spin the bottle", "Şişe çevir", "Flasche drehen", "أدر الزجاجة", "Круціць бутэлку", "Girar l'ampolla", "Točit láhev", "Dreje flasken", "Γύρισε το μπουκάλι", "Girar la botella", "Pyöritä pulloa", "Paikutin ang bote", "Tourner la bouteille", "Okrenuti bocu", "Putar botol", "Girare la bottiglia", "Pusing botol", "Snurr flasken", "Fles draaien", "Kręcić butelką", "Girar a garrafa", "Învârte sticla", "Крутить бутылку", "Snurra flaskan", "Крутити пляшку")),
    card("butterfly_kiss", 1, t("Butterfly kiss", "Kelebek öpücüğü", "Schmetterlingskuss", "قبلة الفراشة", "Матыльковы пацалунак", "Petó papallona", "Motýlí polibek", "Sommerfuglekys", "Φιλί πεταλούδα", "Beso mariposa", "Perhonen-suukko", "Butterfly kiss", "Bisou papillon", "Leptir poljubac", "Cium kupu-kupu", "Bacio farfalla", "Cium rama-rama", "Sommerfuglkys", "Vlinderkus", "Pocałunek motyla", "Beijo borboleta", "Sărut fluture", "Поцелуй-бабочка", "Fjäderkys", "Поцілунок-метелик")),
    card("hold_coat", 1, t("Hold a coat for someone", "Mont tut", "Mantel halten", "امسك المعطف", "Трымаць паліто", "Aguantar l'abric", "Držet kabát", "Holde frakke", "Κράτα παλτό", "Sujetar el abrigo", "Pitää takkia", "Hawakan ang coat", "Tenir le manteau", "Držati kaput", "Tahan mantel", "Tenere il cappotto", "Pegang jaket", "Holde frakk", "Jas vasthouden", "Trzymać płaszcz", "Segurar o casaco", "Ține paltonul", "Держать пальто", "Hålla kappa", "Тримати пальто")),
    card("link_arms", 1, t("Link arms", "Kol kola", "Arme verbinden", "تشابك الأذرع", "Звязаць рукі", "Enllaçar braços", "Propojit paže", "Arm i arm", "Πλέξε χέρια", "Entrelazar brazos", "Kainaloon", "Magkabit ang braso", "Se croiser les bras", "Ukrstiti ruke", "Gandeng lengan", "Intrecciare le braccia", "Gandeng lengan", "Arm i arm", "Armen schuiven", "Złączyć ramiona", "Entrelaçar braços", "Împleti brațele", "Переплести руки", "Länka armar", "Переплести руки")),
]

from expand_decks_batch2_data import BACHELOR, KARAOKE, ACCENTS, CELEB  # noqa: E402

DECKS = {
    "partyFlirty": PARTY_FLIRTY,
    "bachelor": BACHELOR,
    "karaoke": KARAOKE,
    "accents": ACCENTS,
    "celebImpressions": CELEB,
}


def main():
    counts = {}
    for deck_id, cards in DECKS.items():
        if len(cards) != 40:
            raise ValueError(f"{deck_id}: expected 40 cards, got {len(cards)}")
        counts[deck_id] = append_deck(deck_id, cards)
    for deck_id, n in counts.items():
        print(f"{deck_id}: {n} cards")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
