"""Remaining deck expansion data (batch 3 part 2)."""

NEW_CARDS = {
  "instruments": [
    {
      "k": "mandolin",
      "d": 1,
      "t": {
        "en": "Mandolin",
        "tr": "Mandolin",
        "de": "Mandoline",
        "ar": "ماندولين",
        "be": "Mandolin",
        "ca": "Mandolin",
        "cs": "Mandolin",
        "da": "Mandolin",
        "el": "Mandolin",
        "es": "Mandolina",
        "fi": "Mandolin",
        "fil": "Mandolin",
        "fr": "Mandoline",
        "hr": "Mandolin",
        "id": "Mandolin",
        "it": "Mandolin",
        "ms": "Mandolin",
        "nb": "Mandolin",
        "nl": "Mandolin",
        "pl": "Mandolin",
        "pt": "Mandolin",
        "ro": "Mandolin",
        "ru": "Мандолина",
        "sv": "Mandolin",
        "uk": "Мандоліна"
      }
    },
    {
      "k": "oboe",
      "d": 1,
      "t": {
        "en": "Oboe",
        "tr": "Obua",
        "de": "Oboe",
        "ar": "أوبوا",
        "be": "Oboe",
        "ca": "Oboe",
        "cs": "Oboe",
        "da": "Oboe",
        "el": "Oboe",
        "es": "Oboe",
        "fi": "Oboe",
        "fil": "Oboe",
        "fr": "Hautbois",
        "hr": "Oboe",
        "id": "Oboe",
        "it": "Oboe",
        "ms": "Oboe",
        "nb": "Oboe",
        "nl": "Oboe",
        "pl": "Oboe",
        "pt": "Oboe",
        "ro": "Oboe",
        "ru": "Гобой",
        "sv": "Oboe",
        "uk": "Гобой"
      }
    },
    {
      "k": "french_horn",
      "d": 1,
      "t": {
        "en": "French horn",
        "tr": "Korno",
        "de": "Waldhorn",
        "ar": "بوق فرنسي",
        "be": "French horn",
        "ca": "French horn",
        "cs": "French horn",
        "da": "French horn",
        "el": "French horn",
        "es": "Trompa",
        "fi": "French horn",
        "fil": "French horn",
        "fr": "Cor d'harmonie",
        "hr": "French horn",
        "id": "French horn",
        "it": "French horn",
        "ms": "French horn",
        "nb": "French horn",
        "nl": "French horn",
        "pl": "French horn",
        "pt": "French horn",
        "ro": "French horn",
        "ru": "Валторна",
        "sv": "French horn",
        "uk": "Валторна"
      }
    },
    {
      "k": "tuba",
      "d": 1,
      "t": {
        "en": "Tuba",
        "tr": "Tuba",
        "de": "Tuba",
        "ar": "تuba",
        "be": "Tuba",
        "ca": "Tuba",
        "cs": "Tuba",
        "da": "Tuba",
        "el": "Tuba",
        "es": "Tuba",
        "fi": "Tuba",
        "fil": "Tuba",
        "fr": "Tuba",
        "hr": "Tuba",
        "id": "Tuba",
        "it": "Tuba",
        "ms": "Tuba",
        "nb": "Tuba",
        "nl": "Tuba",
        "pl": "Tuba",
        "pt": "Tuba",
        "ro": "Tuba",
        "ru": "Тuba",
        "sv": "Tuba",
        "uk": "Тuba"
      }
    },
    {
      "k": "organ",
      "d": 1,
      "t": {
        "en": "Organ",
        "tr": "Org",
        "de": "Orgel",
        "ar": "أرgan",
        "be": "Organ",
        "ca": "Organ",
        "cs": "Organ",
        "da": "Organ",
        "el": "Organ",
        "es": "Órgano",
        "fi": "Organ",
        "fil": "Organ",
        "fr": "Orgue",
        "hr": "Organ",
        "id": "Organ",
        "it": "Organ",
        "ms": "Organ",
        "nb": "Organ",
        "nl": "Organ",
        "pl": "Organ",
        "pt": "Organ",
        "ro": "Organ",
        "ru": "Орган",
        "sv": "Organ",
        "uk": "Орган"
      }
    },
    {
      "k": "maracas",
      "d": 1,
      "t": {
        "en": "Maracas",
        "tr": "Marakas",
        "de": "Maracas",
        "ar": "مارacas",
        "be": "Maracas",
        "ca": "Maracas",
        "cs": "Maracas",
        "da": "Maracas",
        "el": "Maracas",
        "es": "Maracas",
        "fi": "Maracas",
        "fil": "Maracas",
        "fr": "Maracas",
        "hr": "Maracas",
        "id": "Maracas",
        "it": "Maracas",
        "ms": "Maracas",
        "nb": "Maracas",
        "nl": "Maracas",
        "pl": "Maracas",
        "pt": "Maracas",
        "ro": "Maracas",
        "ru": "Маракасы",
        "sv": "Maracas",
        "uk": "Маракаси"
      }
    },
    {
      "k": "castanets",
      "d": 1,
      "t": {
        "en": "Castanets",
        "tr": "Kastanyet",
        "de": "Kastagnetten",
        "ar": "كستانيت",
        "be": "Castanets",
        "ca": "Castanets",
        "cs": "Castanets",
        "da": "Castanets",
        "el": "Castanets",
        "es": "Castañuelas",
        "fi": "Castanets",
        "fil": "Castanets",
        "fr": "Castagnettes",
        "hr": "Castanets",
        "id": "Castanets",
        "it": "Castanets",
        "ms": "Castanets",
        "nb": "Castanets",
        "nl": "Castanets",
        "pl": "Castanets",
        "pt": "Castanets",
        "ro": "Castanets",
        "ru": "Кастañеты",
        "sv": "Castanets",
        "uk": "Кастañети"
      }
    },
    {
      "k": "conga",
      "d": 1,
      "t": {
        "en": "Conga drum",
        "tr": "Konga",
        "de": "Conga",
        "ar": "كونga",
        "be": "Conga drum",
        "ca": "Conga drum",
        "cs": "Conga drum",
        "da": "Conga drum",
        "el": "Conga drum",
        "es": "Conga",
        "fi": "Conga drum",
        "fil": "Conga drum",
        "fr": "Conga",
        "hr": "Conga drum",
        "id": "Conga drum",
        "it": "Conga drum",
        "ms": "Conga drum",
        "nb": "Conga drum",
        "nl": "Conga drum",
        "pl": "Conga drum",
        "pt": "Conga drum",
        "ro": "Conga drum",
        "ru": "Кonga",
        "sv": "Conga drum",
        "uk": "Кonga"
      }
    },
    {
      "k": "bongo",
      "d": 1,
      "t": {
        "en": "Bongo drums",
        "tr": "Bongo",
        "de": "Bongos",
        "ar": "بongo",
        "be": "Bongo drums",
        "ca": "Bongo drums",
        "cs": "Bongo drums",
        "da": "Bongo drums",
        "el": "Bongo drums",
        "es": "Bongós",
        "fi": "Bongo drums",
        "fil": "Bongo drums",
        "fr": "Bongos",
        "hr": "Bongo drums",
        "id": "Bongo drums",
        "it": "Bongo drums",
        "ms": "Bongo drums",
        "nb": "Bongo drums",
        "nl": "Bongo drums",
        "pl": "Bongo drums",
        "pt": "Bongo drums",
        "ro": "Bongo drums",
        "ru": "Бongos",
        "sv": "Bongo drums",
        "uk": "Бongos"
      }
    },
    {
      "k": "triangle_i",
      "d": 1,
      "t": {
        "en": "Triangle",
        "tr": "Üçgen",
        "de": "Triangel",
        "ar": "مثلث موسيقي",
        "be": "Triangle",
        "ca": "Triangle",
        "cs": "Triangle",
        "da": "Triangle",
        "el": "Triangle",
        "es": "Triángulo",
        "fi": "Triangle",
        "fil": "Triangle",
        "fr": "Triangle",
        "hr": "Triangle",
        "id": "Triangle",
        "it": "Triangle",
        "ms": "Triangle",
        "nb": "Triangle",
        "nl": "Triangle",
        "pl": "Triangle",
        "pt": "Triangle",
        "ro": "Triangle",
        "ru": "Треугольник",
        "sv": "Triangle",
        "uk": "Трикутник"
      }
    },
    {
      "k": "recorder",
      "d": 1,
      "t": {
        "en": "Recorder",
        "tr": "Blok flüt",
        "de": "Blockflöte",
        "ar": "مزمار",
        "be": "Recorder",
        "ca": "Recorder",
        "cs": "Recorder",
        "da": "Recorder",
        "el": "Recorder",
        "es": "Flauta dulce",
        "fi": "Recorder",
        "fil": "Recorder",
        "fr": "Flûte à bec",
        "hr": "Recorder",
        "id": "Recorder",
        "it": "Recorder",
        "ms": "Recorder",
        "nb": "Recorder",
        "nl": "Recorder",
        "pl": "Recorder",
        "pt": "Recorder",
        "ro": "Recorder",
        "ru": "Блокфлейта",
        "sv": "Recorder",
        "uk": "Сопілка"
      }
    },
    {
      "k": "pan_flute",
      "d": 1,
      "t": {
        "en": "Pan flute",
        "tr": "Pan flüt",
        "de": "Panflöte",
        "ar": "ناي pan",
        "be": "Pan flute",
        "ca": "Pan flute",
        "cs": "Pan flute",
        "da": "Pan flute",
        "el": "Pan flute",
        "es": "Flauta de pan",
        "fi": "Pan flute",
        "fil": "Pan flute",
        "fr": "Flûte de Pan",
        "hr": "Pan flute",
        "id": "Pan flute",
        "it": "Pan flute",
        "ms": "Pan flute",
        "nb": "Pan flute",
        "nl": "Pan flute",
        "pl": "Pan flute",
        "pt": "Pan flute",
        "ro": "Pan flute",
        "ru": "Пан-флейта",
        "sv": "Pan flute",
        "uk": "Пан-флейта"
      }
    },
    {
      "k": "didgeridoo",
      "d": 2,
      "t": {
        "en": "Didgeridoo",
        "tr": "Didgeridoo",
        "de": "Didgeridoo",
        "ar": "ديدجيرidoo",
        "be": "Didgeridoo",
        "ca": "Didgeridoo",
        "cs": "Didgeridoo",
        "da": "Didgeridoo",
        "el": "Didgeridoo",
        "es": "Didgeridoo",
        "fi": "Didgeridoo",
        "fil": "Didgeridoo",
        "fr": "Didgeridoo",
        "hr": "Didgeridoo",
        "id": "Didgeridoo",
        "it": "Didgeridoo",
        "ms": "Didgeridoo",
        "nb": "Didgeridoo",
        "nl": "Didgeridoo",
        "pl": "Didgeridoo",
        "pt": "Didgeridoo",
        "ro": "Didgeridoo",
        "ru": "Didgeridoo",
        "sv": "Didgeridoo",
        "uk": "Didgeridoo"
      }
    },
    {
      "k": "steel_drum",
      "d": 1,
      "t": {
        "en": "Steel drum",
        "tr": "Çelik davul",
        "de": "Steel Drum",
        "ar": "طبلة فولاذية",
        "be": "Steel drum",
        "ca": "Steel drum",
        "cs": "Steel drum",
        "da": "Steel drum",
        "el": "Steel drum",
        "es": "Steel drum",
        "fi": "Steel drum",
        "fil": "Steel drum",
        "fr": "Steel drum",
        "hr": "Steel drum",
        "id": "Steel drum",
        "it": "Steel drum",
        "ms": "Steel drum",
        "nb": "Steel drum",
        "nl": "Steel drum",
        "pl": "Steel drum",
        "pt": "Steel drum",
        "ro": "Steel drum",
        "ru": "Steel drum",
        "sv": "Steel drum",
        "uk": "Steel drum"
      }
    },
    {
      "k": "gong",
      "d": 1,
      "t": {
        "en": "Gong",
        "tr": "Gong",
        "de": "Gong",
        "ar": "Gong",
        "be": "Gong",
        "ca": "Gong",
        "cs": "Gong",
        "da": "Gong",
        "el": "Gong",
        "es": "Gong",
        "fi": "Gong",
        "fil": "Gong",
        "fr": "Gong",
        "hr": "Gong",
        "id": "Gong",
        "it": "Gong",
        "ms": "Gong",
        "nb": "Gong",
        "nl": "Gong",
        "pl": "Gong",
        "pt": "Gong",
        "ro": "Gong",
        "ru": "Gong",
        "sv": "Gong",
        "uk": "Gong"
      }
    },
    {
      "k": "cymbals",
      "d": 1,
      "t": {
        "en": "Cymbals",
        "tr": "Zil",
        "de": "Becken",
        "ar": "صنج",
        "be": "Cymbals",
        "ca": "Cymbals",
        "cs": "Cymbals",
        "da": "Cymbals",
        "el": "Cymbals",
        "es": "Platillos",
        "fi": "Cymbals",
        "fil": "Cymbals",
        "fr": "Cymbales",
        "hr": "Cymbals",
        "id": "Cymbals",
        "it": "Cymbals",
        "ms": "Cymbals",
        "nb": "Cymbals",
        "nl": "Cymbals",
        "pl": "Cymbals",
        "pt": "Cymbals",
        "ro": "Cymbals",
        "ru": "Тарелки",
        "sv": "Cymbals",
        "uk": "Тарелки"
      }
    },
    {
      "k": "marimba",
      "d": 2,
      "t": {
        "en": "Marimba",
        "tr": "Marimba",
        "de": "Marimba",
        "ar": "Marimba",
        "be": "Marimba",
        "ca": "Marimba",
        "cs": "Marimba",
        "da": "Marimba",
        "el": "Marimba",
        "es": "Marimba",
        "fi": "Marimba",
        "fil": "Marimba",
        "fr": "Marimba",
        "hr": "Marimba",
        "id": "Marimba",
        "it": "Marimba",
        "ms": "Marimba",
        "nb": "Marimba",
        "nl": "Marimba",
        "pl": "Marimba",
        "pt": "Marimba",
        "ro": "Marimba",
        "ru": "Marimba",
        "sv": "Marimba",
        "uk": "Marimba"
      }
    },
    {
      "k": "vibraphone",
      "d": 2,
      "t": {
        "en": "Vibraphone",
        "tr": "Vibraphone",
        "de": "Vibraphon",
        "ar": "Vibraphone",
        "be": "Vibraphone",
        "ca": "Vibraphone",
        "cs": "Vibraphone",
        "da": "Vibraphone",
        "el": "Vibraphone",
        "es": "Vibrafono",
        "fi": "Vibraphone",
        "fil": "Vibraphone",
        "fr": "Vibraphone",
        "hr": "Vibraphone",
        "id": "Vibraphone",
        "it": "Vibraphone",
        "ms": "Vibraphone",
        "nb": "Vibraphone",
        "nl": "Vibraphone",
        "pl": "Vibraphone",
        "pt": "Vibraphone",
        "ro": "Vibraphone",
        "ru": "Vibraphone",
        "sv": "Vibraphone",
        "uk": "Vibraphone"
      }
    },
    {
      "k": "double_bass",
      "d": 1,
      "t": {
        "en": "Double bass",
        "tr": "Kontrbas",
        "de": "Kontrabass",
        "ar": "كونtrabass",
        "be": "Double bass",
        "ca": "Double bass",
        "cs": "Double bass",
        "da": "Double bass",
        "el": "Double bass",
        "es": "Contrabajo",
        "fi": "Double bass",
        "fil": "Double bass",
        "fr": "Contrebasse",
        "hr": "Double bass",
        "id": "Double bass",
        "it": "Double bass",
        "ms": "Double bass",
        "nb": "Double bass",
        "nl": "Double bass",
        "pl": "Double bass",
        "pt": "Double bass",
        "ro": "Double bass",
        "ru": "Контрабас",
        "sv": "Double bass",
        "uk": "Контрабас"
      }
    },
    {
      "k": "electric_guitar",
      "d": 1,
      "t": {
        "en": "Electric guitar",
        "tr": "Elektro gitar",
        "de": "E-Gitarre",
        "ar": "جيتار كهربائي",
        "be": "Electric guitar",
        "ca": "Electric guitar",
        "cs": "Electric guitar",
        "da": "Electric guitar",
        "el": "Electric guitar",
        "es": "Guitarra eléctrica",
        "fi": "Electric guitar",
        "fil": "Electric guitar",
        "fr": "Guitare électrique",
        "hr": "Electric guitar",
        "id": "Electric guitar",
        "it": "Electric guitar",
        "ms": "Electric guitar",
        "nb": "Electric guitar",
        "nl": "Electric guitar",
        "pl": "Electric guitar",
        "pt": "Electric guitar",
        "ro": "Electric guitar",
        "ru": "Электрогитара",
        "sv": "Electric guitar",
        "uk": "Електрогітара"
      }
    },
    {
      "k": "keytar",
      "d": 2,
      "t": {
        "en": "Keytar",
        "tr": "Keytar",
        "de": "Keytar",
        "ar": "Keytar",
        "be": "Keytar",
        "ca": "Keytar",
        "cs": "Keytar",
        "da": "Keytar",
        "el": "Keytar",
        "es": "Keytar",
        "fi": "Keytar",
        "fil": "Keytar",
        "fr": "Keytar",
        "hr": "Keytar",
        "id": "Keytar",
        "it": "Keytar",
        "ms": "Keytar",
        "nb": "Keytar",
        "nl": "Keytar",
        "pl": "Keytar",
        "pt": "Keytar",
        "ro": "Keytar",
        "ru": "Keytar",
        "sv": "Keytar",
        "uk": "Keytar"
      }
    },
    {
      "k": "melodica",
      "d": 2,
      "t": {
        "en": "Melodica",
        "tr": "Melodika",
        "de": "Melodica",
        "ar": "Melodica",
        "be": "Melodica",
        "ca": "Melodica",
        "cs": "Melodica",
        "da": "Melodica",
        "el": "Melodica",
        "es": "Melódica",
        "fi": "Melodica",
        "fil": "Melodica",
        "fr": "Mélodica",
        "hr": "Melodica",
        "id": "Melodica",
        "it": "Melodica",
        "ms": "Melodica",
        "nb": "Melodica",
        "nl": "Melodica",
        "pl": "Melodica",
        "pt": "Melodica",
        "ro": "Melodica",
        "ru": "Melodica",
        "sv": "Melodica",
        "uk": "Melodica"
      }
    },
    {
      "k": "autoharp",
      "d": 2,
      "t": {
        "en": "Autoharp",
        "tr": "Autoharp",
        "de": "Autoharp",
        "ar": "Autoharp",
        "be": "Autoharp",
        "ca": "Autoharp",
        "cs": "Autoharp",
        "da": "Autoharp",
        "el": "Autoharp",
        "es": "Autoharp",
        "fi": "Autoharp",
        "fil": "Autoharp",
        "fr": "Autoharp",
        "hr": "Autoharp",
        "id": "Autoharp",
        "it": "Autoharp",
        "ms": "Autoharp",
        "nb": "Autoharp",
        "nl": "Autoharp",
        "pl": "Autoharp",
        "pt": "Autoharp",
        "ro": "Autoharp",
        "ru": "Autoharp",
        "sv": "Autoharp",
        "uk": "Autoharp"
      }
    },
    {
      "k": "zither",
      "d": 2,
      "t": {
        "en": "Zither",
        "tr": "Kanun",
        "de": "Zither",
        "ar": "Zither",
        "be": "Zither",
        "ca": "Zither",
        "cs": "Zither",
        "da": "Zither",
        "el": "Zither",
        "es": "Cítara",
        "fi": "Zither",
        "fil": "Zither",
        "fr": "Cithare",
        "hr": "Zither",
        "id": "Zither",
        "it": "Zither",
        "ms": "Zither",
        "nb": "Zither",
        "nl": "Zither",
        "pl": "Zither",
        "pt": "Zither",
        "ro": "Zither",
        "ru": "Цитра",
        "sv": "Zither",
        "uk": "Цитра"
      }
    },
    {
      "k": "sitar",
      "d": 2,
      "t": {
        "en": "Sitar",
        "tr": "Sitar",
        "de": "Sitar",
        "ar": "Sitar",
        "be": "Sitar",
        "ca": "Sitar",
        "cs": "Sitar",
        "da": "Sitar",
        "el": "Sitar",
        "es": "Sitar",
        "fi": "Sitar",
        "fil": "Sitar",
        "fr": "Sitar",
        "hr": "Sitar",
        "id": "Sitar",
        "it": "Sitar",
        "ms": "Sitar",
        "nb": "Sitar",
        "nl": "Sitar",
        "pl": "Sitar",
        "pt": "Sitar",
        "ro": "Sitar",
        "ru": "Сitar",
        "sv": "Sitar",
        "uk": "Сitar"
      }
    },
    {
      "k": "tabla",
      "d": 2,
      "t": {
        "en": "Tabla",
        "tr": "Tabla",
        "de": "Tabla",
        "ar": "Tabla",
        "be": "Tabla",
        "ca": "Tabla",
        "cs": "Tabla",
        "da": "Tabla",
        "el": "Tabla",
        "es": "Tabla",
        "fi": "Tabla",
        "fil": "Tabla",
        "fr": "Tabla",
        "hr": "Tabla",
        "id": "Tabla",
        "it": "Tabla",
        "ms": "Tabla",
        "nb": "Tabla",
        "nl": "Tabla",
        "pl": "Tabla",
        "pt": "Tabla",
        "ro": "Tabla",
        "ru": "Tabla",
        "sv": "Tabla",
        "uk": "Tabla"
      }
    },
    {
      "k": "djembe",
      "d": 1,
      "t": {
        "en": "Djembe",
        "tr": "Djembe",
        "de": "Djembe",
        "ar": "Djembe",
        "be": "Djembe",
        "ca": "Djembe",
        "cs": "Djembe",
        "da": "Djembe",
        "el": "Djembe",
        "es": "Djembe",
        "fi": "Djembe",
        "fil": "Djembe",
        "fr": "Djembé",
        "hr": "Djembe",
        "id": "Djembe",
        "it": "Djembe",
        "ms": "Djembe",
        "nb": "Djembe",
        "nl": "Djembe",
        "pl": "Djembe",
        "pt": "Djembe",
        "ro": "Djembe",
        "ru": "Djembe",
        "sv": "Djembe",
        "uk": "Djembe"
      }
    },
    {
      "k": "kazoo",
      "d": 1,
      "t": {
        "en": "Kazoo",
        "tr": "Kazoo",
        "de": "Kazoo",
        "ar": "Kazoo",
        "be": "Kazoo",
        "ca": "Kazoo",
        "cs": "Kazoo",
        "da": "Kazoo",
        "el": "Kazoo",
        "es": "Kazoo",
        "fi": "Kazoo",
        "fil": "Kazoo",
        "fr": "Kazoo",
        "hr": "Kazoo",
        "id": "Kazoo",
        "it": "Kazoo",
        "ms": "Kazoo",
        "nb": "Kazoo",
        "nl": "Kazoo",
        "pl": "Kazoo",
        "pt": "Kazoo",
        "ro": "Kazoo",
        "ru": "Kazoo",
        "sv": "Kazoo",
        "uk": "Kazoo"
      }
    },
    {
      "k": "whistle_m",
      "d": 1,
      "t": {
        "en": "Whistle",
        "tr": "Düdük",
        "de": "Pfeife",
        "ar": "صافرة",
        "be": "Whistle",
        "ca": "Whistle",
        "cs": "Whistle",
        "da": "Whistle",
        "el": "Whistle",
        "es": "Silbato",
        "fi": "Whistle",
        "fil": "Whistle",
        "fr": "Sifflet",
        "hr": "Whistle",
        "id": "Whistle",
        "it": "Whistle",
        "ms": "Whistle",
        "nb": "Whistle",
        "nl": "Whistle",
        "pl": "Whistle",
        "pt": "Whistle",
        "ro": "Whistle",
        "ru": "Свисток",
        "sv": "Whistle",
        "uk": "Свисток"
      }
    },
    {
      "k": "cowbell",
      "d": 1,
      "t": {
        "en": "Cowbell",
        "tr": "İnek çanı",
        "de": "Kuhglocke",
        "ar": "جرس البقر",
        "be": "Cowbell",
        "ca": "Cowbell",
        "cs": "Cowbell",
        "da": "Cowbell",
        "el": "Cowbell",
        "es": "Cencerro",
        "fi": "Cowbell",
        "fil": "Cowbell",
        "fr": "Cloche vache",
        "hr": "Cowbell",
        "id": "Cowbell",
        "it": "Cowbell",
        "ms": "Cowbell",
        "nb": "Cowbell",
        "nl": "Cowbell",
        "pl": "Cowbell",
        "pt": "Cowbell",
        "ro": "Cowbell",
        "ru": "Cowbell",
        "sv": "Cowbell",
        "uk": "Cowbell"
      }
    },
    {
      "k": "rainstick",
      "d": 2,
      "t": {
        "en": "Rainstick",
        "tr": "Rainstick",
        "de": "Rainstick",
        "ar": "Rainstick",
        "be": "Rainstick",
        "ca": "Rainstick",
        "cs": "Rainstick",
        "da": "Rainstick",
        "el": "Rainstick",
        "es": "Rainstick",
        "fi": "Rainstick",
        "fil": "Rainstick",
        "fr": "Rainstick",
        "hr": "Rainstick",
        "id": "Rainstick",
        "it": "Rainstick",
        "ms": "Rainstick",
        "nb": "Rainstick",
        "nl": "Rainstick",
        "pl": "Rainstick",
        "pt": "Rainstick",
        "ro": "Rainstick",
        "ru": "Rainstick",
        "sv": "Rainstick",
        "uk": "Rainstick"
      }
    },
    {
      "k": "theremin",
      "d": 2,
      "t": {
        "en": "Theremin",
        "tr": "Theremin",
        "de": "Theremin",
        "ar": "Theremin",
        "be": "Theremin",
        "ca": "Theremin",
        "cs": "Theremin",
        "da": "Theremin",
        "el": "Theremin",
        "es": "Theremin",
        "fi": "Theremin",
        "fil": "Theremin",
        "fr": "Thérémine",
        "hr": "Theremin",
        "id": "Theremin",
        "it": "Theremin",
        "ms": "Theremin",
        "nb": "Theremin",
        "nl": "Theremin",
        "pl": "Theremin",
        "pt": "Theremin",
        "ro": "Theremin",
        "ru": "Терemin",
        "sv": "Theremin",
        "uk": "Терemin"
      }
    },
    {
      "k": "synthesizer_pad",
      "d": 1,
      "t": {
        "en": "Synthesizer",
        "tr": "Sentezleyici",
        "de": "Synthesizer",
        "ar": "سynthesizer",
        "be": "Synthesizer",
        "ca": "Synthesizer",
        "cs": "Synthesizer",
        "da": "Synthesizer",
        "el": "Synthesizer",
        "es": "Sintetizador",
        "fi": "Synthesizer",
        "fil": "Synthesizer",
        "fr": "Synthétiseur",
        "hr": "Synthesizer",
        "id": "Synthesizer",
        "it": "Synthesizer",
        "ms": "Synthesizer",
        "nb": "Synthesizer",
        "nl": "Synthesizer",
        "pl": "Synthesizer",
        "pt": "Synthesizer",
        "ro": "Synthesizer",
        "ru": "Синтезатор",
        "sv": "Synthesizer",
        "uk": "Синтезатор"
      }
    },
    {
      "k": "drum_machine",
      "d": 1,
      "t": {
        "en": "Drum machine",
        "tr": "Drum makinesi",
        "de": "Drum Machine",
        "ar": "آلة الطبول",
        "be": "Drum machine",
        "ca": "Drum machine",
        "cs": "Drum machine",
        "da": "Drum machine",
        "el": "Drum machine",
        "es": "Caja de ritmos",
        "fi": "Drum machine",
        "fil": "Drum machine",
        "fr": "Boîte à rythmes",
        "hr": "Drum machine",
        "id": "Drum machine",
        "it": "Drum machine",
        "ms": "Drum machine",
        "nb": "Drum machine",
        "nl": "Drum machine",
        "pl": "Drum machine",
        "pt": "Drum machine",
        "ro": "Drum machine",
        "ru": "Дrum machine",
        "sv": "Drum machine",
        "uk": "Drum machine"
      }
    },
    {
      "k": "turntable",
      "d": 1,
      "t": {
        "en": "Turntable",
        "tr": "Pikap",
        "de": "Plattenspieler",
        "ar": "Turntable",
        "be": "Turntable",
        "ca": "Turntable",
        "cs": "Turntable",
        "da": "Turntable",
        "el": "Turntable",
        "es": "Tocadiscos",
        "fi": "Turntable",
        "fil": "Turntable",
        "fr": "Platine",
        "hr": "Turntable",
        "id": "Turntable",
        "it": "Turntable",
        "ms": "Turntable",
        "nb": "Turntable",
        "nl": "Turntable",
        "pl": "Turntable",
        "pt": "Turntable",
        "ro": "Turntable",
        "ru": "Turntable",
        "sv": "Turntable",
        "uk": "Turntable"
      }
    },
    {
      "k": "microphone_inst",
      "d": 1,
      "t": {
        "en": "Microphone",
        "tr": "Mikrofon",
        "de": "Mikrofon",
        "ar": "ميكrofon",
        "be": "Microphone",
        "ca": "Microphone",
        "cs": "Microphone",
        "da": "Microphone",
        "el": "Microphone",
        "es": "Micrófono",
        "fi": "Microphone",
        "fil": "Microphone",
        "fr": "Microphone",
        "hr": "Microphone",
        "id": "Microphone",
        "it": "Microphone",
        "ms": "Microphone",
        "nb": "Microphone",
        "nl": "Microphone",
        "pl": "Microphone",
        "pt": "Microphone",
        "ro": "Microphone",
        "ru": "Микрофон",
        "sv": "Microphone",
        "uk": "Мікрофон"
      }
    },
    {
      "k": "music_stand",
      "d": 1,
      "t": {
        "en": "Music stand",
        "tr": "Nota sehpası",
        "de": "Notenständer",
        "ar": "حامل موسيقى",
        "be": "Music stand",
        "ca": "Music stand",
        "cs": "Music stand",
        "da": "Music stand",
        "el": "Music stand",
        "es": "Atril",
        "fi": "Music stand",
        "fil": "Music stand",
        "fr": "Pupitre",
        "hr": "Music stand",
        "id": "Music stand",
        "it": "Music stand",
        "ms": "Music stand",
        "nb": "Music stand",
        "nl": "Music stand",
        "pl": "Music stand",
        "pt": "Music stand",
        "ro": "Music stand",
        "ru": "Пюпитр",
        "sv": "Music stand",
        "uk": "Пюпітр"
      }
    },
    {
      "k": "metronome",
      "d": 1,
      "t": {
        "en": "Metronome",
        "tr": "Metronom",
        "de": "Metronom",
        "ar": "Metronome",
        "be": "Metronome",
        "ca": "Metronome",
        "cs": "Metronome",
        "da": "Metronome",
        "el": "Metronome",
        "es": "Metrónomo",
        "fi": "Metronome",
        "fil": "Metronome",
        "fr": "Métronome",
        "hr": "Metronome",
        "id": "Metronome",
        "it": "Metronome",
        "ms": "Metronome",
        "nb": "Metronome",
        "nl": "Metronome",
        "pl": "Metronome",
        "pt": "Metronome",
        "ro": "Metronome",
        "ru": "Метronome",
        "sv": "Metronome",
        "uk": "Метronome"
      }
    },
    {
      "k": "pick_guitar",
      "d": 1,
      "t": {
        "en": "Guitar pick",
        "tr": "Pençe",
        "de": "Plektrum",
        "ar": "Pick",
        "be": "Guitar pick",
        "ca": "Guitar pick",
        "cs": "Guitar pick",
        "da": "Guitar pick",
        "el": "Guitar pick",
        "es": "Púa",
        "fi": "Guitar pick",
        "fil": "Guitar pick",
        "fr": "Médiator",
        "hr": "Guitar pick",
        "id": "Guitar pick",
        "it": "Guitar pick",
        "ms": "Guitar pick",
        "nb": "Guitar pick",
        "nl": "Guitar pick",
        "pl": "Guitar pick",
        "pt": "Guitar pick",
        "ro": "Guitar pick",
        "ru": "Мediator",
        "sv": "Guitar pick",
        "uk": "Мediator"
      }
    },
    {
      "k": "capo",
      "d": 2,
      "t": {
        "en": "Capo",
        "tr": "Kapo",
        "de": "Kapodaster",
        "ar": "Capo",
        "be": "Capo",
        "ca": "Capo",
        "cs": "Capo",
        "da": "Capo",
        "el": "Capo",
        "es": "Cejilla",
        "fi": "Capo",
        "fil": "Capo",
        "fr": "Capodastre",
        "hr": "Capo",
        "id": "Capo",
        "it": "Capo",
        "ms": "Capo",
        "nb": "Capo",
        "nl": "Capo",
        "pl": "Capo",
        "pt": "Capo",
        "ro": "Capo",
        "ru": "Capo",
        "sv": "Capo",
        "uk": "Capo"
      }
    }
  ]
}
