// Bu dosya üretiliyor — elle düzenlemeyin.
// Kaynak: Charades/Resources/Decks/*.json
// Yeniden üretmek için: python3 Scripts/generate_card_counts.py

import Foundation

/// Deste başına kart sayısı, içerik dosyalarından türetilmiş.
///
/// §01 §4 ızgaradaki kartın sağ alt köşesinde kart sayısını istiyor, §05 §5 ise
/// ana ekranda kelime dosyası okunmamasını. Sayı bu yüzden derleme zamanında
/// gömülüyor. Tabloda olmayan deste = içeriği henüz üretilmemiş deste.
enum DeckCardCounts {
    static func count(for deckID: String) -> Int? { table[deckID] }

    static let table: [String: Int] = [
        "accents": 60,
        "actors": 20,
        "animalSounds": 20,
        "animals": 60,
        "animalsAct": 60,
        "anime": 20,
        "bachelor": 60,
        "badHabits": 60,
        "bands": 20,
        "basketball": 20,
        "birds": 60,
        "body": 20,
        "books": 20,
        "brands": 60,
        "capitals": 60,
        "cars": 60,
        "cartoonMovies": 20,
        "celebImpressions": 60,
        "childhoodGames": 20,
        "chores": 60,
        "christmas": 20,
        "christmasMovies": 20,
        "cities": 64,
        "clothes": 60,
        "colorsShapes": 20,
        "combat": 20,
        "countries": 60,
        "dance": 60,
        "dares": 60,
        "dinosaurs": 20,
        "dogBreeds": 60,
        "drinks": 60,
        "eid": 20,
        "eighties": 20,
        "emotions": 60,
        "everyday": 60,
        "extreme": 20,
        "fairyTales": 20,
        "famousWomen": 20,
        "fitness": 20,
        "flags": 60,
        "food": 60,
        "football": 20,
        "footballers": 20,
        "fruits": 20,
        "genres": 20,
        "halloween": 20,
        "historyFigures": 20,
        "horror": 20,
        "household": 60,
        "icebreaker": 60,
        "instruments": 20,
        "inventions": 20,
        "jobs": 60,
        "karaoke": 60,
        "kidsFirst": 20,
        "kitchen": 60,
        "kpop": 20,
        "landmarks": 60,
        "lyrics": 20,
        "mobileGames": 20,
        "movieClassics": 63,
        "movieQuotes": 20,
        "mythology": 20,
        "newYear": 20,
        "nineties": 20,
        "olympics": 20,
        "party": 65,
        "partyFlirty": 60,
        "ramadan": 20,
        "retroTech": 20,
        "school": 20,
        "science": 20,
        "scifi": 20,
        "seaLife": 60,
        "singers": 20,
        "socialMedia": 20,
        "space": 20,
        "sportsAct": 60,
        "streaming": 20,
        "summer": 20,
        "superheroes": 20,
        "superpowers": 60,
        "techCompanies": 20,
        "toys": 20,
        "tvCartoons": 20,
        "tvSeries": 20,
        "twoThousands": 20,
        "valentine": 20,
        "vehicles": 20,
        "videoGames": 20,
        "villains": 20,
    ]
}
