// Bu dosya üretiliyor — elle düzenlemeyin.
// Kaynak: Charades/Resources/Decks/*.json
// Yeniden üretmek için: python3 Scripts/generate_card_counts.py

import Foundation

/// Deste başına kart sayısı, içerik dosyalarından türetilmiş.
///
/// §01 §4 ızgaradaki kartın sağ alt köşesinde kart sayısını istiyor, §05 §5 ise
/// ana ekranda kelime dosyası okunmamasını. Sayı bu yüzden derleme zamanında
/// gömülüyor. Tabloda olmayan deste = içeriği henüz üretilmemiş deste.
enum DeckCardCounts {
    static func count(for deckID: String) -> Int? { table[deckID] }

    static let table: [String: Int] = [
        "accents": 60,
        "actors": 60,
        "animalSounds": 60,
        "animals": 60,
        "animalsAct": 60,
        "anime": 60,
        "bachelor": 60,
        "badHabits": 60,
        "bands": 60,
        "basketball": 60,
        "birds": 60,
        "body": 60,
        "books": 60,
        "brands": 60,
        "capitals": 60,
        "cars": 60,
        "cartoonMovies": 60,
        "celebImpressions": 60,
        "childhoodGames": 60,
        "chores": 60,
        "christmas": 60,
        "christmasMovies": 60,
        "cities": 64,
        "clothes": 60,
        "colorsShapes": 60,
        "combat": 60,
        "countries": 60,
        "dance": 60,
        "dares": 60,
        "dinosaurs": 60,
        "dogBreeds": 60,
        "drinks": 60,
        "eid": 60,
        "eighties": 60,
        "emotions": 60,
        "everyday": 60,
        "extreme": 60,
        "fairyTales": 60,
        "famousWomen": 60,
        "fitness": 60,
        "flags": 60,
        "food": 60,
        "football": 60,
        "footballers": 60,
        "fruits": 60,
        "genres": 60,
        "halloween": 60,
        "historyFigures": 60,
        "horror": 60,
        "household": 60,
        "icebreaker": 60,
        "instruments": 60,
        "inventions": 60,
        "jobs": 60,
        "karaoke": 60,
        "kidsFirst": 60,
        "kitchen": 60,
        "kpop": 60,
        "landmarks": 60,
        "lyrics": 60,
        "mobileGames": 60,
        "movieClassics": 63,
        "movieQuotes": 60,
        "mythology": 60,
        "newYear": 60,
        "nineties": 60,
        "olympics": 60,
        "party": 65,
        "partyFlirty": 60,
        "ramadan": 60,
        "retroTech": 60,
        "school": 60,
        "science": 60,
        "scifi": 60,
        "seaLife": 60,
        "singers": 60,
        "socialMedia": 60,
        "space": 60,
        "sportsAct": 60,
        "streaming": 60,
        "summer": 60,
        "superheroes": 60,
        "superpowers": 60,
        "techCompanies": 60,
        "toys": 60,
        "tvCartoons": 60,
        "tvSeries": 60,
        "twoThousands": 60,
        "valentine": 60,
        "vehicles": 60,
        "videoGames": 60,
        "villains": 60,
    ]
}
