import json
import os
import sys

BASE = os.path.join(os.path.dirname(__file__), "..", "..", "Imposter", "Resources", "Localization")

REVEAL = {
    "de": {
        "reveal.turnOf": "Du bist dran, {name}",
        "reveal.holdTitle": "Deine Karte ist versiegelt",
        "reveal.holdHint": "Halte den Finger gedrückt, um sie zu öffnen — beim Loslassen versiegelt sie sofort",
        "reveal.releaseHint": "Loslassen und niemand kann sie sehen",
        "reveal.crewLabel": "Dein geheimes Wort",
        "reveal.crewBody": "Beschreibe es, ohne es zu sagen. Täusche den Betrüger.",
        "reveal.imposterTag": "DU BIST DER BETRÜGER",
        "reveal.imposterBody": "Tarne dich, bevor es jemand merkt.",
        "reveal.hint": "Flüstern: {hint}",
        "reveal.passNext": "Gib das Handy jetzt an {name} weiter",
        "reveal.startGame": "Alle haben es gesehen — los geht's",
    },
    "ar": {
        "reveal.turnOf": "دورك يا {name}",
        "reveal.holdTitle": "بطاقتك مختومة",
        "reveal.holdHint": "اضغط بإصبعك لفتحها — وتُختم فور رفع إصبعك",
        "reveal.releaseHint": "ارفع إصبعك ولن يراها أحد",
        "reveal.crewLabel": "كلمتك السرية",
        "reveal.crewBody": "صِفها دون أن تقولها. اخدع الدخيل.",
        "reveal.imposterTag": "أنت الدخيل",
        "reveal.imposterBody": "اندمج قبل أن ينتبه أحد.",
        "reveal.hint": "همسة: {hint}",
        "reveal.passNext": "الآن مرّر الهاتف إلى {name}",
        "reveal.startGame": "رآها الجميع — ابدأ",
    },
    "be": {
        "reveal.turnOf": "Твая чарга, {name}",
        "reveal.holdTitle": "Твая картка запячатана",
        "reveal.holdHint": "Трымай палец, каб адкрыць — яна зноў запячатаецца, як толькі адпусціш",
        "reveal.releaseHint": "Адпусці — і ніхто не ўбачыць",
        "reveal.crewLabel": "Тваё сакрэтнае слова",
        "reveal.crewBody": "Апішы яго, не называючы. Абдуры самазванца.",
        "reveal.imposterTag": "ТЫ САМАЗВАНЕЦ",
        "reveal.imposterBody": "Зліся з натоўпам, пакуль ніхто не заўважыў.",
        "reveal.hint": "Шэпт: {hint}",
        "reveal.passNext": "Цяпер перадай тэлефон {name}",
        "reveal.startGame": "Усе ўбачылі — пачынаем",
    },
    "da": {
        "reveal.turnOf": "Din tur, {name}",
        "reveal.holdTitle": "Dit kort er forseglet",
        "reveal.holdHint": "Hold fingeren nede for at åbne det — det forsegles igen, så snart du slipper",
        "reveal.releaseHint": "Slip, og ingen kan se det",
        "reveal.crewLabel": "Dit hemmelige ord",
        "reveal.crewBody": "Beskriv det uden at sige det. Narr bedrageren.",
        "reveal.imposterTag": "DU ER BEDRAGEREN",
        "reveal.imposterBody": "Smelt ind, før nogen opdager det.",
        "reveal.hint": "Hvisken: {hint}",
        "reveal.passNext": "Giv nu telefonen til {name}",
        "reveal.startGame": "Alle har set det — start",
    },
    "id": {
        "reveal.turnOf": "Giliranmu, {name}",
        "reveal.holdTitle": "Kartumu tersegel",
        "reveal.holdHint": "Tahan jarimu untuk membukanya — akan tersegel lagi begitu kamu lepas",
        "reveal.releaseHint": "Lepaskan, dan tak ada yang bisa melihatnya",
        "reveal.crewLabel": "Kata rahasiamu",
        "reveal.crewBody": "Jelaskan tanpa menyebutnya. Kelabui si penyusup.",
        "reveal.imposterTag": "KAMU SI PENYUSUP",
        "reveal.imposterBody": "Berbaurlah sebelum ada yang sadar.",
        "reveal.hint": "Bisikan: {hint}",
        "reveal.passNext": "Sekarang berikan ponsel ke {name}",
        "reveal.startGame": "Semua sudah lihat — mulai",
    },
    "fil": {
        "reveal.turnOf": "Iyong turn, {name}",
        "reveal.holdTitle": "Nakaselyo ang card mo",
        "reveal.holdHint": "Pindutin nang matagal para buksan — magsasara ulit pagbitaw mo",
        "reveal.releaseHint": "Bitawan mo at walang makakakita",
        "reveal.crewLabel": "Ang lihim mong salita",
        "reveal.crewBody": "Ilarawan nang hindi binibigkas. Lokohin ang imposter.",
        "reveal.imposterTag": "IKAW ANG IMPOSTER",
        "reveal.imposterBody": "Makisabay bago ka mahalata.",
        "reveal.hint": "Bulong: {hint}",
        "reveal.passNext": "Ipasa na ang telepono kay {name}",
        "reveal.startGame": "Nakita na ng lahat — simulan",
    },
    "fi": {
        "reveal.turnOf": "Sinun vuorosi, {name}",
        "reveal.holdTitle": "Korttisi on sinetöity",
        "reveal.holdHint": "Pidä sormea painettuna avataksesi — se sulkeutuu heti kun irrotat",
        "reveal.releaseHint": "Irrota, eikä kukaan näe sitä",
        "reveal.crewLabel": "Salainen sanasi",
        "reveal.crewBody": "Kuvaile sitä sanomatta sitä. Hämää huijaria.",
        "reveal.imposterTag": "SINÄ OLET HUIJARI",
        "reveal.imposterBody": "Sulaudu joukkoon ennen kuin kukaan huomaa.",
        "reveal.hint": "Kuiskaus: {hint}",
        "reveal.passNext": "Anna puhelin nyt pelaajalle {name}",
        "reveal.startGame": "Kaikki näkivät — aloita",
    },
    "fr": {
        "reveal.turnOf": "À toi, {name}",
        "reveal.holdTitle": "Ta carte est scellée",
        "reveal.holdHint": "Maintiens le doigt pour l'ouvrir — elle se rescelle dès que tu lâches",
        "reveal.releaseHint": "Lâche et personne ne la voit",
        "reveal.crewLabel": "Ton mot secret",
        "reveal.crewBody": "Décris-le sans le dire. Trompe l'imposteur.",
        "reveal.imposterTag": "TU ES L'IMPOSTEUR",
        "reveal.imposterBody": "Fonds-toi dans la masse avant qu'on te repère.",
        "reveal.hint": "Murmure : {hint}",
        "reveal.passNext": "Passe maintenant le téléphone à {name}",
        "reveal.startGame": "Tout le monde a vu — commencer",
    },
    "nl": {
        "reveal.turnOf": "Jouw beurt, {name}",
        "reveal.holdTitle": "Je kaart is verzegeld",
        "reveal.holdHint": "Houd je vinger vast om te openen — hij verzegelt weer zodra je loslaat",
        "reveal.releaseHint": "Laat los en niemand kan het zien",
        "reveal.crewLabel": "Jouw geheime woord",
        "reveal.crewBody": "Beschrijf het zonder het te zeggen. Misleid de bedrieger.",
        "reveal.imposterTag": "JIJ BENT DE BEDRIEGER",
        "reveal.imposterBody": "Ga op in de groep voordat iemand het merkt.",
        "reveal.hint": "Fluister: {hint}",
        "reveal.passNext": "Geef de telefoon nu aan {name}",
        "reveal.startGame": "Iedereen heeft het gezien — starten",
    },
    "hr": {
        "reveal.turnOf": "Tvoj red, {name}",
        "reveal.holdTitle": "Tvoja karta je zapečaćena",
        "reveal.holdHint": "Drži prst da je otvoriš — ponovno se pečati čim pustiš",
        "reveal.releaseHint": "Pusti i nitko je ne vidi",
        "reveal.crewLabel": "Tvoja tajna riječ",
        "reveal.crewBody": "Opiši je bez da je izgovoriš. Prevari varalicu.",
        "reveal.imposterTag": "TI SI VARALICA",
        "reveal.imposterBody": "Uklopi se prije nego što itko primijeti.",
        "reveal.hint": "Šapat: {hint}",
        "reveal.passNext": "Sada dodaj telefon igraču {name}",
        "reveal.startGame": "Svi su vidjeli — počni",
    },
    "ca": {
        "reveal.turnOf": "El teu torn, {name}",
        "reveal.holdTitle": "La teva carta està segellada",
        "reveal.holdHint": "Mantén el dit per obrir-la — es torna a segellar quan la deixes anar",
        "reveal.releaseHint": "Deixa-la anar i ningú la veurà",
        "reveal.crewLabel": "La teva paraula secreta",
        "reveal.crewBody": "Descriu-la sense dir-la. Enganya l'impostor.",
        "reveal.imposterTag": "ETS L'IMPOSTOR",
        "reveal.imposterBody": "Dissimula abans que algú se n'adoni.",
        "reveal.hint": "Murmuri: {hint}",
        "reveal.passNext": "Ara passa el telèfon a {name}",
        "reveal.startGame": "Tothom ho ha vist — comença",
    },
    "pl": {
        "reveal.turnOf": "Twoja kolej, {name}",
        "reveal.holdTitle": "Twoja karta jest zapieczętowana",
        "reveal.holdHint": "Przytrzymaj palec, aby ją otworzyć — zapieczętuje się, gdy tylko puścisz",
        "reveal.releaseHint": "Puść, a nikt jej nie zobaczy",
        "reveal.crewLabel": "Twoje tajne słowo",
        "reveal.crewBody": "Opisz je, nie wymawiając. Oszukaj oszusta.",
        "reveal.imposterTag": "JESTEŚ OSZUSTEM",
        "reveal.imposterBody": "Wtop się, zanim ktoś zauważy.",
        "reveal.hint": "Szept: {hint}",
        "reveal.passNext": "Teraz podaj telefon graczowi {name}",
        "reveal.startGame": "Wszyscy zobaczyli — zaczynamy",
    },
    "ms": {
        "reveal.turnOf": "Giliran kamu, {name}",
        "reveal.holdTitle": "Kad kamu dimeterai",
        "reveal.holdHint": "Tahan jari untuk membukanya — ia dimeterai semula sebaik saja kamu lepas",
        "reveal.releaseHint": "Lepaskan dan tiada siapa dapat melihatnya",
        "reveal.crewLabel": "Perkataan rahsia kamu",
        "reveal.crewBody": "Terangkan tanpa menyebutnya. Perdaya penyamar.",
        "reveal.imposterTag": "KAMU PENYAMARNYA",
        "reveal.imposterBody": "Sebati sebelum ada yang perasan.",
        "reveal.hint": "Bisikan: {hint}",
        "reveal.passNext": "Kini serahkan telefon kepada {name}",
        "reveal.startGame": "Semua dah lihat — mula",
    },
    "nb": {
        "reveal.turnOf": "Din tur, {name}",
        "reveal.holdTitle": "Kortet ditt er forseglet",
        "reveal.holdHint": "Hold fingeren nede for å åpne det — det forsegles igjen straks du slipper",
        "reveal.releaseHint": "Slipp, så kan ingen se det",
        "reveal.crewLabel": "Ditt hemmelige ord",
        "reveal.crewBody": "Beskriv det uten å si det. Lur bedrageren.",
        "reveal.imposterTag": "DU ER BEDRAGEREN",
        "reveal.imposterBody": "Smelt inn før noen merker det.",
        "reveal.hint": "Hvisking: {hint}",
        "reveal.passNext": "Gi nå telefonen til {name}",
        "reveal.startGame": "Alle har sett det — start",
    },
    "pt": {
        "reveal.turnOf": "A tua vez, {name}",
        "reveal.holdTitle": "A tua carta está selada",
        "reveal.holdHint": "Mantém o dedo para a abrir — sela-se de novo assim que largares",
        "reveal.releaseHint": "Larga e ninguém a vê",
        "reveal.crewLabel": "A tua palavra secreta",
        "reveal.crewBody": "Descreve-a sem a dizer. Engana o impostor.",
        "reveal.imposterTag": "TU ÉS O IMPOSTOR",
        "reveal.imposterBody": "Disfarça antes que alguém perceba.",
        "reveal.hint": "Sussurro: {hint}",
        "reveal.passNext": "Agora passa o telefone a {name}",
        "reveal.startGame": "Todos viram — começar",
    },
    "ro": {
        "reveal.turnOf": "E rândul tău, {name}",
        "reveal.holdTitle": "Cartea ta este sigilată",
        "reveal.holdHint": "Ține degetul apăsat ca s-o deschizi — se sigilează din nou când ridici degetul",
        "reveal.releaseHint": "Ridică degetul și nimeni nu o vede",
        "reveal.crewLabel": "Cuvântul tău secret",
        "reveal.crewBody": "Descrie-l fără să-l spui. Păcălește impostorul.",
        "reveal.imposterTag": "TU EȘTI IMPOSTORUL",
        "reveal.imposterBody": "Amestecă-te înainte să observe cineva.",
        "reveal.hint": "Șoaptă: {hint}",
        "reveal.passNext": "Acum dă telefonul lui {name}",
        "reveal.startGame": "Toți au văzut — începe",
    },
    "ru": {
        "reveal.turnOf": "Твой ход, {name}",
        "reveal.holdTitle": "Твоя карта запечатана",
        "reveal.holdHint": "Держи палец, чтобы открыть — она снова запечатается, как только отпустишь",
        "reveal.releaseHint": "Отпусти — и никто не увидит",
        "reveal.crewLabel": "Твоё секретное слово",
        "reveal.crewBody": "Опиши его, не называя. Обмани самозванца.",
        "reveal.imposterTag": "ТЫ САМОЗВАНЕЦ",
        "reveal.imposterBody": "Слейся с остальными, пока не заметили.",
        "reveal.hint": "Шёпот: {hint}",
        "reveal.passNext": "Теперь передай телефон {name}",
        "reveal.startGame": "Все увидели — начинаем",
    },
    "uk": {
        "reveal.turnOf": "Твоя черга, {name}",
        "reveal.holdTitle": "Твоя картка запечатана",
        "reveal.holdHint": "Тримай палець, щоб відкрити — вона знову запечатається, щойно відпустиш",
        "reveal.releaseHint": "Відпусти — і ніхто не побачить",
        "reveal.crewLabel": "Твоє таємне слово",
        "reveal.crewBody": "Опиши його, не називаючи. Обдури самозванця.",
        "reveal.imposterTag": "ТИ САМОЗВАНЕЦЬ",
        "reveal.imposterBody": "Злийся з іншими, поки ніхто не помітив.",
        "reveal.hint": "Шепіт: {hint}",
        "reveal.passNext": "Тепер передай телефон {name}",
        "reveal.startGame": "Усі побачили — почати",
    },
    "el": {
        "reveal.turnOf": "Η σειρά σου, {name}",
        "reveal.holdTitle": "Η κάρτα σου είναι σφραγισμένη",
        "reveal.holdHint": "Κράτα το δάχτυλο για να την ανοίξεις — σφραγίζεται ξανά μόλις το αφήσεις",
        "reveal.releaseHint": "Άφησέ το και κανείς δεν τη βλέπει",
        "reveal.crewLabel": "Η μυστική σου λέξη",
        "reveal.crewBody": "Περίγραψέ την χωρίς να την πεις. Ξεγέλασε τον απατεώνα.",
        "reveal.imposterTag": "ΕΙΣΑΙ Ο ΑΠΑΤΕΩΝΑΣ",
        "reveal.imposterBody": "Πέρνα απαρατήρητος πριν σε καταλάβουν.",
        "reveal.hint": "Ψίθυρος: {hint}",
        "reveal.passNext": "Τώρα δώσε το τηλέφωνο στον/στην {name}",
        "reveal.startGame": "Το είδαν όλοι — ξεκίνα",
    },
    "cs": {
        "reveal.turnOf": "Jsi na řadě, {name}",
        "reveal.holdTitle": "Tvoje karta je zapečetěná",
        "reveal.holdHint": "Podrž prst, abys ji otevřel — jakmile pustíš, znovu se zapečetí",
        "reveal.releaseHint": "Pusť a nikdo ji neuvidí",
        "reveal.crewLabel": "Tvoje tajné slovo",
        "reveal.crewBody": "Popiš ho, aniž bys ho řekl. Oklam podvodníka.",
        "reveal.imposterTag": "JSI PODVODNÍK",
        "reveal.imposterBody": "Splyň s ostatními, než si někdo všimne.",
        "reveal.hint": "Šepot: {hint}",
        "reveal.passNext": "Teď podej telefon hráči {name}",
        "reveal.startGame": "Všichni viděli — začni",
    },
    "es": {
        "reveal.turnOf": "Tu turno, {name}",
        "reveal.holdTitle": "Tu carta está sellada",
        "reveal.holdHint": "Mantén el dedo para abrirla — se vuelve a sellar en cuanto lo sueltas",
        "reveal.releaseHint": "Suelta y nadie podrá verla",
        "reveal.crewLabel": "Tu palabra secreta",
        "reveal.crewBody": "Descríbela sin decirla. Engaña al impostor.",
        "reveal.imposterTag": "ERES EL IMPOSTOR",
        "reveal.imposterBody": "Disimula antes de que alguien lo note.",
        "reveal.hint": "Susurro: {hint}",
        "reveal.passNext": "Ahora pasa el teléfono a {name}",
        "reveal.startGame": "Todos lo han visto — empezar",
    },
    "sv": {
        "reveal.turnOf": "Din tur, {name}",
        "reveal.holdTitle": "Ditt kort är förseglat",
        "reveal.holdHint": "Håll fingret för att öppna — det förseglas igen så fort du släpper",
        "reveal.releaseHint": "Släpp så kan ingen se det",
        "reveal.crewLabel": "Ditt hemliga ord",
        "reveal.crewBody": "Beskriv det utan att säga det. Lura bedragaren.",
        "reveal.imposterTag": "DU ÄR BEDRAGAREN",
        "reveal.imposterBody": "Smält in innan någon märker det.",
        "reveal.hint": "Viskning: {hint}",
        "reveal.passNext": "Ge nu telefonen till {name}",
        "reveal.startGame": "Alla har sett — starta",
    },
    "it": {
        "reveal.turnOf": "Tocca a te, {name}",
        "reveal.holdTitle": "La tua carta è sigillata",
        "reveal.holdHint": "Tieni premuto il dito per aprirla — si risigilla appena lasci",
        "reveal.releaseHint": "Lascia e nessuno potrà vederla",
        "reveal.crewLabel": "La tua parola segreta",
        "reveal.crewBody": "Descrivila senza dirla. Inganna l'impostore.",
        "reveal.imposterTag": "SEI L'IMPOSTORE",
        "reveal.imposterBody": "Mimetizzati prima che qualcuno se ne accorga.",
        "reveal.hint": "Sussurro: {hint}",
        "reveal.passNext": "Ora passa il telefono a {name}",
        "reveal.startGame": "Tutti hanno visto — inizia",
    },
}


def apply(table):
    changed = 0
    for lang, keys in table.items():
        path = os.path.join(BASE, lang + ".json")
        if not os.path.exists(path):
            print("MISSING", lang)
            continue
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        for k, v in keys.items():
            data[k] = v
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        changed += 1
    return changed


CLUE = {
    "de": {"clue.title": "Hinweisrunde", "clue.turnOf": "Du bist dran", "clue.instruction": "Gib einen Hinweis, ohne das Wort zu nennen — je cleverer, desto besser.", "clue.given": "Hinweis gegeben", "clue.toDiscussion": "Zur offenen Diskussion"},
    "ar": {"clue.title": "جولة التلميحات", "clue.turnOf": "دورك", "clue.instruction": "أعطِ تلميحًا واحدًا دون قول الكلمة — كلما كان أذكى كان أفضل.", "clue.given": "أعطيت تلميحي", "clue.toDiscussion": "إلى النقاش المفتوح"},
    "be": {"clue.title": "Раунд падказак", "clue.turnOf": "Твая чарга", "clue.instruction": "Дай адну падказку, не называючы слова — чым разумней, тым лепш.", "clue.given": "Я даў падказку", "clue.toDiscussion": "Да адкрытай дыскусіі"},
    "da": {"clue.title": "Hint-runde", "clue.turnOf": "Din tur", "clue.instruction": "Giv ét hint uden at sige ordet — jo klogere, jo bedre.", "clue.given": "Jeg gav mit hint", "clue.toDiscussion": "Til åben diskussion"},
    "id": {"clue.title": "Ronde petunjuk", "clue.turnOf": "Giliranmu", "clue.instruction": "Beri satu petunjuk tanpa menyebut katanya — makin cerdik makin baik.", "clue.given": "Aku sudah beri petunjuk", "clue.toDiscussion": "Ke diskusi terbuka"},
    "fil": {"clue.title": "Round ng clue", "clue.turnOf": "Iyong turn", "clue.instruction": "Magbigay ng isang clue nang hindi binibigkas ang salita — mas matalino, mas maganda.", "clue.given": "Nagbigay na ako ng clue", "clue.toDiscussion": "Sa bukas na talakayan"},
    "fi": {"clue.title": "Vihjekierros", "clue.turnOf": "Sinun vuorosi", "clue.instruction": "Anna yksi vihje sanomatta sanaa — mitä nokkelampi, sen parempi.", "clue.given": "Annoin vihjeeni", "clue.toDiscussion": "Avoimeen keskusteluun"},
    "fr": {"clue.title": "Tour d'indices", "clue.turnOf": "À toi", "clue.instruction": "Donne un indice sans dire le mot — plus c'est malin, mieux c'est.", "clue.given": "J'ai donné mon indice", "clue.toDiscussion": "Vers la discussion ouverte"},
    "nl": {"clue.title": "Hintronde", "clue.turnOf": "Jouw beurt", "clue.instruction": "Geef één hint zonder het woord te zeggen — hoe slimmer, hoe beter.", "clue.given": "Ik heb mijn hint gegeven", "clue.toDiscussion": "Naar open discussie"},
    "hr": {"clue.title": "Runda natuknica", "clue.turnOf": "Tvoj red", "clue.instruction": "Daj jednu natuknicu bez izgovaranja riječi — što pametnije, to bolje.", "clue.given": "Dao sam natuknicu", "clue.toDiscussion": "Na otvorenu raspravu"},
    "ca": {"clue.title": "Ronda de pistes", "clue.turnOf": "El teu torn", "clue.instruction": "Dona una pista sense dir la paraula — com més enginyosa, millor.", "clue.given": "He donat la meva pista", "clue.toDiscussion": "A la discussió oberta"},
    "pl": {"clue.title": "Runda wskazówek", "clue.turnOf": "Twoja kolej", "clue.instruction": "Podaj jedną wskazówkę, nie mówiąc słowa — im sprytniej, tym lepiej.", "clue.given": "Dałem wskazówkę", "clue.toDiscussion": "Do otwartej dyskusji"},
    "ms": {"clue.title": "Pusingan petunjuk", "clue.turnOf": "Giliran kamu", "clue.instruction": "Beri satu petunjuk tanpa menyebut perkataannya — makin bijak makin baik.", "clue.given": "Saya dah beri petunjuk", "clue.toDiscussion": "Ke perbincangan terbuka"},
    "nb": {"clue.title": "Hint-runde", "clue.turnOf": "Din tur", "clue.instruction": "Gi ett hint uten å si ordet — jo smartere, jo bedre.", "clue.given": "Jeg ga hintet mitt", "clue.toDiscussion": "Til åpen diskusjon"},
    "pt": {"clue.title": "Ronda de pistas", "clue.turnOf": "A tua vez", "clue.instruction": "Dá uma pista sem dizer a palavra — quanto mais esperta, melhor.", "clue.given": "Já dei a minha pista", "clue.toDiscussion": "Para a discussão aberta"},
    "ro": {"clue.title": "Runda de indicii", "clue.turnOf": "E rândul tău", "clue.instruction": "Dă un indiciu fără să spui cuvântul — cu cât mai isteț, cu atât mai bine.", "clue.given": "Mi-am dat indiciul", "clue.toDiscussion": "La discuția liberă"},
    "ru": {"clue.title": "Раунд подсказок", "clue.turnOf": "Твой ход", "clue.instruction": "Дай одну подсказку, не называя слово — чем хитрее, тем лучше.", "clue.given": "Я дал подсказку", "clue.toDiscussion": "К открытому обсуждению"},
    "uk": {"clue.title": "Раунд підказок", "clue.turnOf": "Твоя черга", "clue.instruction": "Дай одну підказку, не називаючи слово — що хитріше, то краще.", "clue.given": "Я дав підказку", "clue.toDiscussion": "До відкритого обговорення"},
    "el": {"clue.title": "Γύρος στοιχείων", "clue.turnOf": "Η σειρά σου", "clue.instruction": "Δώσε ένα στοιχείο χωρίς να πεις τη λέξη — όσο πιο έξυπνο, τόσο καλύτερα.", "clue.given": "Έδωσα το στοιχείο μου", "clue.toDiscussion": "Σε ανοιχτή συζήτηση"},
    "cs": {"clue.title": "Kolo nápověd", "clue.turnOf": "Jsi na řadě", "clue.instruction": "Dej jednu nápovědu, aniž bys řekl slovo — čím chytřejší, tím lepší.", "clue.given": "Dal jsem nápovědu", "clue.toDiscussion": "K otevřené diskuzi"},
    "es": {"clue.title": "Ronda de pistas", "clue.turnOf": "Tu turno", "clue.instruction": "Da una pista sin decir la palabra — cuanto más ingeniosa, mejor.", "clue.given": "Ya di mi pista", "clue.toDiscussion": "A la discusión abierta"},
    "sv": {"clue.title": "Ledtrådsrunda", "clue.turnOf": "Din tur", "clue.instruction": "Ge en ledtråd utan att säga ordet — ju smartare, desto bättre.", "clue.given": "Jag gav min ledtråd", "clue.toDiscussion": "Till öppen diskussion"},
    "it": {"clue.title": "Turno di indizi", "clue.turnOf": "Tocca a te", "clue.instruction": "Dai un indizio senza dire la parola — più è astuto, meglio è.", "clue.given": "Ho dato il mio indizio", "clue.toDiscussion": "Alla discussione aperta"},
}

DISCUSS = {
    "de": {"round.discussTitle": "Diskussion", "round.prompt1": "Wer ist zu still?", "round.prompt2": "Frag nach Details, treib sie in die Enge", "round.prompt3": "Wessen Hinweis war seltsam?", "round.prompt4": "Keine Eile — hör zu", "round.prompt5": "Bring den Verdächtigen zum Reden", "round.timeUp": "Zeit ist um!", "round.restartTimer": "Timer neu starten"},
    "ar": {"round.discussTitle": "النقاش", "round.prompt1": "من الهادئ أكثر من اللازم؟", "round.prompt2": "اطلب التفاصيل وحاصره", "round.prompt3": "تلميح مَن كان غريبًا؟", "round.prompt4": "لا تتعجل — استمع", "round.prompt5": "اجعل المشتبه به يتكلم", "round.timeUp": "انتهى الوقت!", "round.restartTimer": "إعادة تشغيل المؤقت"},
    "be": {"round.discussTitle": "Абмеркаванне", "round.prompt1": "Хто занадта ціхі?", "round.prompt2": "Прасі дэталі, заганяй у кут", "round.prompt3": "Чыя падказка была дзіўнай?", "round.prompt4": "Не спяшайся — слухай", "round.prompt5": "Прымусь падазронага гаварыць", "round.timeUp": "Час выйшаў!", "round.restartTimer": "Перазапусціць таймер"},
    "da": {"round.discussTitle": "Diskussion", "round.prompt1": "Hvem er lidt for stille?", "round.prompt2": "Bed om detaljer, træng dem op i en krog", "round.prompt3": "Hvis hint føltes forkert?", "round.prompt4": "Skynd dig ikke — lyt", "round.prompt5": "Få den mistænkte til at tale", "round.timeUp": "Tiden er gået!", "round.restartTimer": "Genstart timeren"},
    "id": {"round.discussTitle": "Diskusi", "round.prompt1": "Siapa yang terlalu diam?", "round.prompt2": "Minta detail, sudutkan dia", "round.prompt3": "Petunjuk siapa yang janggal?", "round.prompt4": "Jangan terburu — dengarkan", "round.prompt5": "Buat si tersangka bicara", "round.timeUp": "Waktu habis!", "round.restartTimer": "Mulai ulang pengatur waktu"},
    "fil": {"round.discussTitle": "Talakayan", "round.prompt1": "Sino ang sobrang tahimik?", "round.prompt2": "Humingi ng detalye, ipitin siya", "round.prompt3": "Kaninong clue ang kakaiba?", "round.prompt4": "Huwag magmadali — makinig", "round.prompt5": "Pagsalitain ang suspek", "round.timeUp": "Tapos na ang oras!", "round.restartTimer": "I-restart ang timer"},
    "fi": {"round.discussTitle": "Keskustelu", "round.prompt1": "Kuka on liian hiljainen?", "round.prompt2": "Kysy yksityiskohtia, ahdista nurkkaan", "round.prompt3": "Kenen vihje tuntui oudolta?", "round.prompt4": "Älä kiirehdi — kuuntele", "round.prompt5": "Saa epäilty puhumaan", "round.timeUp": "Aika loppui!", "round.restartTimer": "Käynnistä ajastin uudelleen"},
    "fr": {"round.discussTitle": "Discussion", "round.prompt1": "Qui est un peu trop silencieux ?", "round.prompt2": "Demande des détails, coince-le", "round.prompt3": "Quel indice sonnait faux ?", "round.prompt4": "Pas de précipitation — écoute", "round.prompt5": "Fais parler le suspect", "round.timeUp": "Temps écoulé !", "round.restartTimer": "Redémarrer le minuteur"},
    "nl": {"round.discussTitle": "Discussie", "round.prompt1": "Wie is iets te stil?", "round.prompt2": "Vraag om details, drijf ze in het nauw", "round.prompt3": "Wiens hint voelde vreemd?", "round.prompt4": "Geen haast — luister", "round.prompt5": "Laat de verdachte praten", "round.timeUp": "Tijd is om!", "round.restartTimer": "Timer opnieuw starten"},
    "hr": {"round.discussTitle": "Rasprava", "round.prompt1": "Tko je previše tih?", "round.prompt2": "Traži detalje, stjeraj ga u kut", "round.prompt3": "Čija je natuknica bila čudna?", "round.prompt4": "Bez žurbe — slušaj", "round.prompt5": "Natjeraj sumnjivca da progovori", "round.timeUp": "Vrijeme je isteklo!", "round.restartTimer": "Ponovno pokreni mjerač"},
    "ca": {"round.discussTitle": "Debat", "round.prompt1": "Qui està massa callat?", "round.prompt2": "Demana detalls, acorrala'l", "round.prompt3": "Quina pista sonava estranya?", "round.prompt4": "Sense pressa — escolta", "round.prompt5": "Fes parlar el sospitós", "round.timeUp": "S'ha acabat el temps!", "round.restartTimer": "Reinicia el temporitzador"},
    "pl": {"round.discussTitle": "Dyskusja", "round.prompt1": "Kto jest zbyt cichy?", "round.prompt2": "Pytaj o szczegóły, przyprzyj do muru", "round.prompt3": "Czyja wskazówka była dziwna?", "round.prompt4": "Bez pośpiechu — słuchaj", "round.prompt5": "Zmuś podejrzanego do mówienia", "round.timeUp": "Czas minął!", "round.restartTimer": "Zrestartuj minutnik"},
    "ms": {"round.discussTitle": "Perbincangan", "round.prompt1": "Siapa terlalu senyap?", "round.prompt2": "Minta butiran, sudutkan dia", "round.prompt3": "Petunjuk siapa yang pelik?", "round.prompt4": "Jangan tergesa — dengar", "round.prompt5": "Buat suspek bercakap", "round.timeUp": "Masa tamat!", "round.restartTimer": "Mula semula pemasa"},
    "nb": {"round.discussTitle": "Diskusjon", "round.prompt1": "Hvem er litt for stille?", "round.prompt2": "Be om detaljer, sett dem fast", "round.prompt3": "Hvems hint føltes rart?", "round.prompt4": "Ingen hast — lytt", "round.prompt5": "Få den mistenkte til å snakke", "round.timeUp": "Tiden er ute!", "round.restartTimer": "Start tidtakeren på nytt"},
    "pt": {"round.discussTitle": "Discussão", "round.prompt1": "Quem está calado demais?", "round.prompt2": "Pede detalhes, encurrala-o", "round.prompt3": "A pista de quem soou estranha?", "round.prompt4": "Sem pressa — ouve", "round.prompt5": "Faz o suspeito falar", "round.timeUp": "Acabou o tempo!", "round.restartTimer": "Reiniciar o cronómetro"},
    "ro": {"round.discussTitle": "Discuție", "round.prompt1": "Cine e prea tăcut?", "round.prompt2": "Cere detalii, încolțește-l", "round.prompt3": "Al cui indiciu a sunat ciudat?", "round.prompt4": "Nu te grăbi — ascultă", "round.prompt5": "Fă suspectul să vorbească", "round.timeUp": "Timpul a expirat!", "round.restartTimer": "Repornește cronometrul"},
    "ru": {"round.discussTitle": "Обсуждение", "round.prompt1": "Кто слишком тихий?", "round.prompt2": "Спроси детали, загони в угол", "round.prompt3": "Чья подсказка была странной?", "round.prompt4": "Не спеши — слушай", "round.prompt5": "Заставь подозреваемого говорить", "round.timeUp": "Время вышло!", "round.restartTimer": "Перезапустить таймер"},
    "uk": {"round.discussTitle": "Обговорення", "round.prompt1": "Хто занадто тихий?", "round.prompt2": "Проси деталі, притисни до стіни", "round.prompt3": "Чия підказка була дивною?", "round.prompt4": "Не поспішай — слухай", "round.prompt5": "Змусь підозрюваного говорити", "round.timeUp": "Час вийшов!", "round.restartTimer": "Перезапустити таймер"},
    "el": {"round.discussTitle": "Συζήτηση", "round.prompt1": "Ποιος είναι υπερβολικά σιωπηλός;", "round.prompt2": "Ζήτα λεπτομέρειες, στρίμωξέ τον", "round.prompt3": "Ποιανού το στοιχείο ήταν περίεργο;", "round.prompt4": "Μη βιάζεσαι — άκου", "round.prompt5": "Κάνε τον ύποπτο να μιλήσει", "round.timeUp": "Ο χρόνος τελείωσε!", "round.restartTimer": "Επανεκκίνηση χρονομέτρου"},
    "cs": {"round.discussTitle": "Diskuze", "round.prompt1": "Kdo je až moc potichu?", "round.prompt2": "Ptej se na detaily, zažeň ho do kouta", "round.prompt3": "Čí nápověda byla divná?", "round.prompt4": "Nespěchej — poslouchej", "round.prompt5": "Přinuť podezřelého mluvit", "round.timeUp": "Čas vypršel!", "round.restartTimer": "Restartovat časovač"},
    "es": {"round.discussTitle": "Debate", "round.prompt1": "¿Quién está demasiado callado?", "round.prompt2": "Pide detalles, acorrálalo", "round.prompt3": "¿Qué pista sonó rara?", "round.prompt4": "Sin prisa — escucha", "round.prompt5": "Haz hablar al sospechoso", "round.timeUp": "¡Se acabó el tiempo!", "round.restartTimer": "Reiniciar el temporizador"},
    "sv": {"round.discussTitle": "Diskussion", "round.prompt1": "Vem är lite för tyst?", "round.prompt2": "Be om detaljer, tränga in dem", "round.prompt3": "Vems ledtråd kändes fel?", "round.prompt4": "Ingen brådska — lyssna", "round.prompt5": "Få den misstänkte att prata", "round.timeUp": "Tiden är ute!", "round.restartTimer": "Starta om timern"},
    "it": {"round.discussTitle": "Discussione", "round.prompt1": "Chi è troppo silenzioso?", "round.prompt2": "Chiedi dettagli, mettilo alle strette", "round.prompt3": "L'indizio di chi suonava strano?", "round.prompt4": "Niente fretta — ascolta", "round.prompt5": "Fai parlare il sospettato", "round.timeUp": "Tempo scaduto!", "round.restartTimer": "Riavvia il timer"},
}

VOTE = {
    "de": {"vote.label": "Zeit der Enthüllung", "vote.accuseHint": "Zeig mit dem Finger auf den Verdächtigen", "vote.accused": "Angeklagt", "vote.reveal": "ENTHÜLLEN"},
    "ar": {"vote.label": "وقت الكشف", "vote.accuseHint": "وجّه إصبعك نحو المشتبه به", "vote.accused": "متهم", "vote.reveal": "اكشف"},
    "be": {"vote.label": "Час выкрыцця", "vote.accuseHint": "Пакажы пальцам на падазронага", "vote.accused": "Абвінавачаны", "vote.reveal": "ВЫКРЫЦЬ"},
    "da": {"vote.label": "Afsløringens tid", "vote.accuseHint": "Peg fingeren mod den mistænkte", "vote.accused": "Anklaget", "vote.reveal": "AFSLØR"},
    "id": {"vote.label": "Waktunya terbongkar", "vote.accuseHint": "Tunjuk jarimu ke tersangka", "vote.accused": "Terdakwa", "vote.reveal": "BONGKAR"},
    "fil": {"vote.label": "Oras na ng pagbunyag", "vote.accuseHint": "Ituro ang daliri sa suspek", "vote.accused": "Inakusahan", "vote.reveal": "IBUNYAG"},
    "fi": {"vote.label": "Paljastuksen aika", "vote.accuseHint": "Osoita sormella epäiltyä", "vote.accused": "Syytetty", "vote.reveal": "PALJASTA"},
    "fr": {"vote.label": "Moment de vérité", "vote.accuseHint": "Pointe le suspect du doigt", "vote.accused": "Accusé", "vote.reveal": "RÉVÉLER"},
    "nl": {"vote.label": "Tijd voor onthulling", "vote.accuseHint": "Wijs met je vinger naar de verdachte", "vote.accused": "Beschuldigd", "vote.reveal": "ONTHUL"},
    "hr": {"vote.label": "Vrijeme otkrivanja", "vote.accuseHint": "Uperi prst u sumnjivca", "vote.accused": "Optužen", "vote.reveal": "OTKRIJ"},
    "ca": {"vote.label": "Hora de revelar", "vote.accuseHint": "Assenyala el sospitós amb el dit", "vote.accused": "Acusat", "vote.reveal": "REVELA"},
    "pl": {"vote.label": "Czas ujawnienia", "vote.accuseHint": "Wskaż palcem podejrzanego", "vote.accused": "Oskarżony", "vote.reveal": "UJAWNIJ"},
    "ms": {"vote.label": "Masa untuk dedah", "vote.accuseHint": "Tuding jari ke suspek", "vote.accused": "Dituduh", "vote.reveal": "DEDAH"},
    "nb": {"vote.label": "Avsløringens tid", "vote.accuseHint": "Pek fingeren mot den mistenkte", "vote.accused": "Anklaget", "vote.reveal": "AVSLØR"},
    "pt": {"vote.label": "Hora de revelar", "vote.accuseHint": "Aponta o dedo ao suspeito", "vote.accused": "Acusado", "vote.reveal": "REVELAR"},
    "ro": {"vote.label": "Momentul dezvăluirii", "vote.accuseHint": "Arată cu degetul spre suspect", "vote.accused": "Acuzat", "vote.reveal": "DEZVĂLUIE"},
    "ru": {"vote.label": "Время разоблачения", "vote.accuseHint": "Укажи пальцем на подозреваемого", "vote.accused": "Обвиняемый", "vote.reveal": "РАЗОБЛАЧИТЬ"},
    "uk": {"vote.label": "Час викриття", "vote.accuseHint": "Вкажи пальцем на підозрюваного", "vote.accused": "Звинувачений", "vote.reveal": "ВИКРИТИ"},
    "el": {"vote.label": "Ώρα αποκάλυψης", "vote.accuseHint": "Δείξε τον ύποπτο με το δάχτυλο", "vote.accused": "Κατηγορούμενος", "vote.reveal": "ΑΠΟΚΑΛΥΨΕ"},
    "cs": {"vote.label": "Čas odhalení", "vote.accuseHint": "Ukaž prstem na podezřelého", "vote.accused": "Obviněný", "vote.reveal": "ODHAL"},
    "es": {"vote.label": "Hora de revelar", "vote.accuseHint": "Señala con el dedo al sospechoso", "vote.accused": "Acusado", "vote.reveal": "REVELAR"},
    "sv": {"vote.label": "Dags att avslöja", "vote.accuseHint": "Peka finger mot den misstänkte", "vote.accused": "Anklagad", "vote.reveal": "AVSLÖJA"},
    "it": {"vote.label": "Ora della verità", "vote.accuseHint": "Punta il dito verso il sospettato", "vote.accused": "Accusato", "vote.reveal": "RIVELA"},
}

HOME = {
    "de": {"home.chooseMode": "Modus wählen", "home.lobbyLabel": "Aufstellung dieser Runde", "home.playersReady": "{n} Spieler bereit", "home.editRoster": "Bearbeiten", "home.tapToStart": "Tippen zum Start"},
    "ar": {"home.chooseMode": "اختر وضعًا", "home.lobbyLabel": "تشكيلة هذه الجولة", "home.playersReady": "{n} لاعبين جاهزين", "home.editRoster": "تعديل", "home.tapToStart": "اضغط للبدء"},
    "be": {"home.chooseMode": "Абяры рэжым", "home.lobbyLabel": "Склад гэтага раунда", "home.playersReady": "{n} гульцоў гатова", "home.editRoster": "Змяніць", "home.tapToStart": "Націсні, каб пачаць"},
    "da": {"home.chooseMode": "Vælg tilstand", "home.lobbyLabel": "Denne rundes opstilling", "home.playersReady": "{n} spillere klar", "home.editRoster": "Rediger", "home.tapToStart": "Tryk for at starte"},
    "id": {"home.chooseMode": "Pilih mode", "home.lobbyLabel": "Susunan ronde ini", "home.playersReady": "{n} pemain siap", "home.editRoster": "Ubah", "home.tapToStart": "Ketuk untuk mulai"},
    "fil": {"home.chooseMode": "Pumili ng mode", "home.lobbyLabel": "Lineup ng round na ito", "home.playersReady": "{n} players handa na", "home.editRoster": "I-edit", "home.tapToStart": "I-tap para magsimula"},
    "fi": {"home.chooseMode": "Valitse tila", "home.lobbyLabel": "Tämän kierroksen kokoonpano", "home.playersReady": "{n} pelaajaa valmiina", "home.editRoster": "Muokkaa", "home.tapToStart": "Aloita napauttamalla"},
    "fr": {"home.chooseMode": "Choisis un mode", "home.lobbyLabel": "La compo de ce tour", "home.playersReady": "{n} joueurs prêts", "home.editRoster": "Modifier", "home.tapToStart": "Touche pour commencer"},
    "nl": {"home.chooseMode": "Kies een modus", "home.lobbyLabel": "Opstelling van deze ronde", "home.playersReady": "{n} spelers klaar", "home.editRoster": "Bewerken", "home.tapToStart": "Tik om te starten"},
    "hr": {"home.chooseMode": "Odaberi način", "home.lobbyLabel": "Postava ove runde", "home.playersReady": "{n} igrača spremno", "home.editRoster": "Uredi", "home.tapToStart": "Dodirni za početak"},
    "ca": {"home.chooseMode": "Tria un mode", "home.lobbyLabel": "L'alineació d'aquesta ronda", "home.playersReady": "{n} jugadors a punt", "home.editRoster": "Edita", "home.tapToStart": "Toca per començar"},
    "pl": {"home.chooseMode": "Wybierz tryb", "home.lobbyLabel": "Skład tej rundy", "home.playersReady": "{n} graczy gotowych", "home.editRoster": "Edytuj", "home.tapToStart": "Dotknij, aby zacząć"},
    "ms": {"home.chooseMode": "Pilih mod", "home.lobbyLabel": "Barisan pusingan ini", "home.playersReady": "{n} pemain sedia", "home.editRoster": "Sunting", "home.tapToStart": "Ketik untuk mula"},
    "nb": {"home.chooseMode": "Velg modus", "home.lobbyLabel": "Denne rundens oppstilling", "home.playersReady": "{n} spillere klare", "home.editRoster": "Rediger", "home.tapToStart": "Trykk for å starte"},
    "pt": {"home.chooseMode": "Escolhe um modo", "home.lobbyLabel": "A escalação desta ronda", "home.playersReady": "{n} jogadores prontos", "home.editRoster": "Editar", "home.tapToStart": "Toca para começar"},
    "ro": {"home.chooseMode": "Alege un mod", "home.lobbyLabel": "Formația acestei runde", "home.playersReady": "{n} jucători pregătiți", "home.editRoster": "Editează", "home.tapToStart": "Atinge pentru a începe"},
    "ru": {"home.chooseMode": "Выбери режим", "home.lobbyLabel": "Состав этого раунда", "home.playersReady": "{n} игроков готово", "home.editRoster": "Изменить", "home.tapToStart": "Нажми, чтобы начать"},
    "uk": {"home.chooseMode": "Обери режим", "home.lobbyLabel": "Склад цього раунду", "home.playersReady": "{n} гравців готово", "home.editRoster": "Змінити", "home.tapToStart": "Торкнись, щоб почати"},
    "el": {"home.chooseMode": "Διάλεξε λειτουργία", "home.lobbyLabel": "Η σύνθεση αυτού του γύρου", "home.playersReady": "{n} παίκτες έτοιμοι", "home.editRoster": "Επεξεργασία", "home.tapToStart": "Πάτα για έναρξη"},
    "cs": {"home.chooseMode": "Vyber režim", "home.lobbyLabel": "Sestava tohoto kola", "home.playersReady": "{n} hráčů připraveno", "home.editRoster": "Upravit", "home.tapToStart": "Klepnutím začni"},
    "es": {"home.chooseMode": "Elige un modo", "home.lobbyLabel": "La alineación de esta ronda", "home.playersReady": "{n} jugadores listos", "home.editRoster": "Editar", "home.tapToStart": "Toca para empezar"},
    "sv": {"home.chooseMode": "Välj läge", "home.lobbyLabel": "Den här rundans uppställning", "home.playersReady": "{n} spelare redo", "home.editRoster": "Redigera", "home.tapToStart": "Tryck för att starta"},
    "it": {"home.chooseMode": "Scegli una modalità", "home.lobbyLabel": "La formazione di questo turno", "home.playersReady": "{n} giocatori pronti", "home.editRoster": "Modifica", "home.tapToStart": "Tocca per iniziare"},
}

PLAYERS = {
    "de": {"players.title": "Stell dein Team auf"},
    "ar": {"players.title": "شكّل فريقك"},
    "be": {"players.title": "Збяры каманду"},
    "da": {"players.title": "Saml dit hold"},
    "id": {"players.title": "Susun timmu"},
    "fil": {"players.title": "Buuin ang iyong grupo"},
    "fi": {"players.title": "Kokoa joukkueesi"},
    "fr": {"players.title": "Forme ton équipe"},
    "nl": {"players.title": "Stel je team samen"},
    "hr": {"players.title": "Sastavi ekipu"},
    "ca": {"players.title": "Forma el teu equip"},
    "pl": {"players.title": "Zbierz drużynę"},
    "ms": {"players.title": "Bina pasukan kamu"},
    "nb": {"players.title": "Sett sammen laget ditt"},
    "pt": {"players.title": "Monta a tua equipa"},
    "ro": {"players.title": "Formează-ți echipa"},
    "ru": {"players.title": "Собери команду"},
    "uk": {"players.title": "Збери команду"},
    "el": {"players.title": "Φτιάξε την ομάδα σου"},
    "cs": {"players.title": "Sestav svůj tým"},
    "es": {"players.title": "Forma tu equipo"},
    "sv": {"players.title": "Sätt ihop ditt lag"},
    "it": {"players.title": "Forma la tua squadra"},
}

CATS = {
    "de": {"categories.surprise": "Überrasch mich"},
    "ar": {"categories.surprise": "فاجئني"},
    "be": {"categories.surprise": "Здзіві мяне"},
    "da": {"categories.surprise": "Overrask mig"},
    "id": {"categories.surprise": "Kejutkan aku"},
    "fil": {"categories.surprise": "Gulatin mo ako"},
    "fi": {"categories.surprise": "Yllätä minut"},
    "fr": {"categories.surprise": "Surprends-moi"},
    "nl": {"categories.surprise": "Verras me"},
    "hr": {"categories.surprise": "Iznenadi me"},
    "ca": {"categories.surprise": "Sorprèn-me"},
    "pl": {"categories.surprise": "Zaskocz mnie"},
    "ms": {"categories.surprise": "Kejutkan saya"},
    "nb": {"categories.surprise": "Overrask meg"},
    "pt": {"categories.surprise": "Surpreende-me"},
    "ro": {"categories.surprise": "Surprinde-mă"},
    "ru": {"categories.surprise": "Удиви меня"},
    "uk": {"categories.surprise": "Здивуй мене"},
    "el": {"categories.surprise": "Έκπληξέ με"},
    "cs": {"categories.surprise": "Překvap mě"},
    "es": {"categories.surprise": "Sorpréndeme"},
    "sv": {"categories.surprise": "Överraska mig"},
    "it": {"categories.surprise": "Sorprendimi"},
}

GSET = {
    "de": {"gameSettings.playersLabel": "Spieler", "gameSettings.impostersLabel": "Betrüger", "gameSettings.durationLabel": "Zeit"},
    "ar": {"gameSettings.playersLabel": "لاعبون", "gameSettings.impostersLabel": "دخلاء", "gameSettings.durationLabel": "الوقت"},
    "be": {"gameSettings.playersLabel": "Гульцы", "gameSettings.impostersLabel": "Самазванцы", "gameSettings.durationLabel": "Час"},
    "da": {"gameSettings.playersLabel": "Spillere", "gameSettings.impostersLabel": "Bedragere", "gameSettings.durationLabel": "Tid"},
    "id": {"gameSettings.playersLabel": "Pemain", "gameSettings.impostersLabel": "Penyusup", "gameSettings.durationLabel": "Waktu"},
    "fil": {"gameSettings.playersLabel": "Players", "gameSettings.impostersLabel": "Imposter", "gameSettings.durationLabel": "Oras"},
    "fi": {"gameSettings.playersLabel": "Pelaajat", "gameSettings.impostersLabel": "Huijarit", "gameSettings.durationLabel": "Aika"},
    "fr": {"gameSettings.playersLabel": "Joueurs", "gameSettings.impostersLabel": "Imposteurs", "gameSettings.durationLabel": "Temps"},
    "nl": {"gameSettings.playersLabel": "Spelers", "gameSettings.impostersLabel": "Bedriegers", "gameSettings.durationLabel": "Tijd"},
    "hr": {"gameSettings.playersLabel": "Igrači", "gameSettings.impostersLabel": "Varalice", "gameSettings.durationLabel": "Vrijeme"},
    "ca": {"gameSettings.playersLabel": "Jugadors", "gameSettings.impostersLabel": "Impostors", "gameSettings.durationLabel": "Temps"},
    "pl": {"gameSettings.playersLabel": "Gracze", "gameSettings.impostersLabel": "Oszuści", "gameSettings.durationLabel": "Czas"},
    "ms": {"gameSettings.playersLabel": "Pemain", "gameSettings.impostersLabel": "Penyamar", "gameSettings.durationLabel": "Masa"},
    "nb": {"gameSettings.playersLabel": "Spillere", "gameSettings.impostersLabel": "Bedragere", "gameSettings.durationLabel": "Tid"},
    "pt": {"gameSettings.playersLabel": "Jogadores", "gameSettings.impostersLabel": "Impostores", "gameSettings.durationLabel": "Tempo"},
    "ro": {"gameSettings.playersLabel": "Jucători", "gameSettings.impostersLabel": "Impostori", "gameSettings.durationLabel": "Timp"},
    "ru": {"gameSettings.playersLabel": "Игроки", "gameSettings.impostersLabel": "Самозванцы", "gameSettings.durationLabel": "Время"},
    "uk": {"gameSettings.playersLabel": "Гравці", "gameSettings.impostersLabel": "Самозванці", "gameSettings.durationLabel": "Час"},
    "el": {"gameSettings.playersLabel": "Παίκτες", "gameSettings.impostersLabel": "Απατεώνες", "gameSettings.durationLabel": "Χρόνος"},
    "cs": {"gameSettings.playersLabel": "Hráči", "gameSettings.impostersLabel": "Podvodníci", "gameSettings.durationLabel": "Čas"},
    "es": {"gameSettings.playersLabel": "Jugadores", "gameSettings.impostersLabel": "Impostores", "gameSettings.durationLabel": "Tiempo"},
    "sv": {"gameSettings.playersLabel": "Spelare", "gameSettings.impostersLabel": "Bedragare", "gameSettings.durationLabel": "Tid"},
    "it": {"gameSettings.playersLabel": "Giocatori", "gameSettings.impostersLabel": "Impostori", "gameSettings.durationLabel": "Tempo"},
}

def modekeys(vals):
    ks = ["mode.classic.title", "mode.classic.subtitle", "mode.classic.clue",
          "mode.chain.title", "mode.chain.subtitle", "mode.chain.clue",
          "mode.doubleAgent.title", "mode.doubleAgent.subtitle", "mode.doubleAgent.clue",
          "mode.emoji.title", "mode.emoji.subtitle", "mode.emoji.clue",
          "mode.rapid.title", "mode.rapid.subtitle", "mode.rapid.clue",
          "mode.drawing.title", "mode.drawing.subtitle", "mode.drawing.clue"]
    return dict(zip(ks, vals))

MODES = {
    "de": modekeys(["Klassischer Imposter", "Beschreibe das Wort, verrate es nicht", "Gib einen Hinweis, ohne das Wort zu nennen.", "Hinweiskette", "Jeder fügt ein Wort zur Kette hinzu", "Füge ein Wort hinzu, das an die vorherigen anknüpft.", "Doppelagent", "Zwei geheime Wörter sind im Spiel", "Beschreibe dein Wort — vielleicht ist deins das falsche.", "Emoji-Modus", "Kein Reden, nur Emojis", "Keine Worte — gib deinen Hinweis nur mit Emojis.", "Blitzrunde", "Sekunden pro Person, schnell", "Schnell! Gib deinen Hinweis, bevor die Zeit abläuft.", "Zeichenmodus", "Keine Worte, nur Zeichnen", "Zeichne deinen Hinweis in einem Strich."]),
    "ar": modekeys(["الدخيل الكلاسيكي", "صِف الكلمة دون أن تكشفها", "أعطِ تلميحًا واحدًا دون قول الكلمة.", "سلسلة التلميحات", "كل لاعب يضيف كلمة إلى السلسلة", "أضف كلمة ترتبط بالتلميحات قبلك.", "العميل المزدوج", "كلمتان سريتان في اللعبة", "صِف كلمتك — لكن ربما تكون كلمتك المزيفة.", "وضع الإيموجي", "لا كلام، إيموجي فقط", "بلا كلمات — أعطِ تلميحك بالإيموجي فقط.", "جولة سريعة", "ثوانٍ لكل لاعب، سريعة", "بسرعة! أعطِ تلميحك قبل نفاد الوقت.", "وضع الرسم", "بلا كلمات، مجرد رسم", "ارسم تلميحك بخط واحد."]),
    "be": modekeys(["Класічны самазванец", "Апішы слова, не выдаючы яго", "Дай адну падказку, не называючы слова.", "Ланцуг падказак", "Кожны дадае слова да ланцуга", "Дадай слова, звязанае з папярэднімі падказкамі.", "Двайны агент", "У гульні два сакрэтныя словы", "Апішы сваё слова — але, можа, тваё фальшывае.", "Рэжым эмодзі", "Ніякіх слоў, толькі эмодзі", "Без слоў — давай падказку толькі эмодзі.", "Хуткі раунд", "Секунды на кожнага, хутка", "Хутчэй! Дай падказку, пакуль час не выйшаў.", "Рэжым малявання", "Ніякіх слоў, толькі малюнак", "Намалюй падказку адной лініяй."]),
    "da": modekeys(["Klassisk bedrager", "Beskriv ordet uden at afsløre det", "Giv ét hint uden at sige ordet.", "Hint-kæde", "Alle føjer et ord til kæden", "Tilføj et ord, der hænger sammen med de forrige hint.", "Dobbeltagent", "To hemmelige ord er i spil", "Beskriv dit ord — men måske er dit det falske.", "Emoji-tilstand", "Ingen tale, kun emojis", "Ingen ord — giv dit hint kun med emojis.", "Lynrunde", "Sekunder hver, hurtigt", "Hurtigt! Giv dit hint, før tiden løber ud.", "Tegnetilstand", "Ingen ord, bare din tegning", "Tegn dit hint i ét enkelt streg."]),
    "id": modekeys(["Penyusup Klasik", "Jelaskan katanya, jangan ungkap", "Beri satu petunjuk tanpa menyebut katanya.", "Rantai Petunjuk", "Semua menambah satu kata ke rantai", "Tambahkan satu kata yang terkait petunjuk sebelumnya.", "Agen Ganda", "Dua kata rahasia sedang beredar", "Jelaskan katamu — tapi mungkin punyamu palsu.", "Mode Emoji", "Tanpa bicara, hanya emoji", "Tanpa kata — beri petunjuk hanya dengan emoji.", "Ronde Kilat", "Hitungan detik tiap orang, cepat", "Cepat! Beri petunjukmu sebelum waktu habis.", "Mode Gambar", "Tanpa kata, hanya gambarmu", "Gambar petunjukmu dalam satu goresan."]),
    "fil": modekeys(["Klasikong Imposter", "Ilarawan ang salita, huwag ibunyag", "Magbigay ng isang clue nang hindi binibigkas.", "Kadena ng Clue", "Bawat isa'y nagdadagdag ng salita", "Magdagdag ng salitang konektado sa nauna.", "Double Agent", "May dalawang lihim na salita", "Ilarawan ang salita mo — baka peke ang sa'yo.", "Emoji Mode", "Walang salita, emoji lang", "Walang salita — clue gamit ang emoji lang.", "Mabilis na Round", "Ilang segundo bawat isa, mabilis", "Bilis! Ibigay ang clue bago maubos ang oras.", "Drawing Mode", "Walang salita, guhit lang", "Iguhit ang clue sa isang hagod."]),
    "fi": modekeys(["Klassinen huijari", "Kuvaile sana paljastamatta sitä", "Anna yksi vihje sanomatta sanaa.", "Vihjeketju", "Jokainen lisää ketjuun sanan", "Lisää sana, joka liittyy edellisiin vihjeisiin.", "Kaksoisagentti", "Pelissä on kaksi salaista sanaa", "Kuvaile sanasi — mutta ehkä sinun on väärä.", "Emoji-tila", "Ei puhetta, vain emojit", "Ei sanoja — anna vihjeesi vain emojeilla.", "Pikakierros", "Sekunteja per pelaaja, nopeaa", "Nopeasti! Anna vihje ennen ajan loppumista.", "Piirtotila", "Ei sanoja, vain piirroksesi", "Piirrä vihjeesi yhdellä vedolla."]),
    "fr": modekeys(["Imposteur classique", "Décris le mot sans le révéler", "Donne un indice sans dire le mot.", "Chaîne d'indices", "Chacun ajoute un mot à la chaîne", "Ajoute un mot lié aux indices précédents.", "Agent double", "Deux mots secrets en jeu", "Décris ton mot — mais le tien est peut-être le faux.", "Mode Emoji", "Pas de parole, que des emojis", "Pas de mots — donne ton indice en emojis seulement.", "Manche éclair", "Quelques secondes chacun, rapide", "Vite ! Donne ton indice avant la fin du temps.", "Mode Dessin", "Pas de mots, juste ton dessin", "Dessine ton indice d'un seul trait."]),
    "nl": modekeys(["Klassieke bedrieger", "Beschrijf het woord, verklap het niet", "Geef één hint zonder het woord te zeggen.", "Hintketen", "Iedereen voegt een woord toe", "Voeg een woord toe dat aansluit op de vorige hints.", "Dubbelagent", "Er zijn twee geheime woorden", "Beschrijf je woord — misschien is het jouwe nep.", "Emoji-modus", "Niet praten, alleen emoji's", "Geen woorden — geef je hint alleen met emoji's.", "Bliksemronde", "Seconden per persoon, snel", "Snel! Geef je hint voordat de tijd om is.", "Tekenmodus", "Geen woorden, alleen je tekening", "Teken je hint in één streek."]),
    "hr": modekeys(["Klasični varalica", "Opiši riječ, ne odaj je", "Daj jednu natuknicu bez izgovaranja riječi.", "Lanac natuknica", "Svatko dodaje riječ u lanac", "Dodaj riječ povezanu s prethodnim natuknicama.", "Dvostruki agent", "U igri su dvije tajne riječi", "Opiši svoju riječ — možda je tvoja lažna.", "Emoji način", "Bez govora, samo emojiji", "Bez riječi — daj natuknicu samo emojijima.", "Brza runda", "Sekunde po igraču, brzo", "Brzo! Daj natuknicu prije isteka vremena.", "Način crtanja", "Bez riječi, samo tvoj crtež", "Nacrtaj natuknicu jednim potezom."]),
    "ca": modekeys(["Impostor clàssic", "Descriu la paraula sense revelar-la", "Dona una pista sense dir la paraula.", "Cadena de pistes", "Cadascú afegeix una paraula", "Afegeix una paraula lligada a les pistes anteriors.", "Agent doble", "Hi ha dues paraules secretes", "Descriu la teva paraula — potser la teva és la falsa.", "Mode Emoji", "Sense parlar, només emojis", "Sense paraules — dona la pista només amb emojis.", "Ronda llampec", "Segons per persona, ràpid", "Ràpid! Dona la pista abans que s'acabi el temps.", "Mode Dibuix", "Sense paraules, només el teu dibuix", "Dibuixa la pista amb un sol traç."]),
    "pl": modekeys(["Klasyczny oszust", "Opisz słowo, nie zdradzaj go", "Podaj jedną wskazówkę, nie mówiąc słowa.", "Łańcuch wskazówek", "Każdy dodaje słowo do łańcucha", "Dodaj słowo powiązane z wcześniejszymi wskazówkami.", "Podwójny agent", "W grze są dwa tajne słowa", "Opisz swoje słowo — może twoje jest fałszywe.", "Tryb Emoji", "Bez mówienia, tylko emoji", "Bez słów — podaj wskazówkę tylko emoji.", "Runda błyskawiczna", "Sekundy na osobę, szybko", "Szybko! Podaj wskazówkę, zanim skończy się czas.", "Tryb rysowania", "Bez słów, tylko twój rysunek", "Narysuj wskazówkę jedną kreską."]),
    "ms": modekeys(["Penyamar Klasik", "Terangkan perkataan, jangan dedah", "Beri satu petunjuk tanpa menyebutnya.", "Rantaian Petunjuk", "Semua menambah satu perkataan", "Tambah perkataan yang berkait dengan petunjuk sebelum.", "Ejen Berkembar", "Dua perkataan rahsia dalam permainan", "Terangkan perkataan kamu — mungkin milik kamu palsu.", "Mod Emoji", "Tiada percakapan, emoji sahaja", "Tanpa kata — beri petunjuk dengan emoji sahaja.", "Pusingan Pantas", "Beberapa saat setiap orang, pantas", "Cepat! Beri petunjuk sebelum masa tamat.", "Mod Lukisan", "Tiada kata, hanya lukisan kamu", "Lukis petunjuk kamu dalam satu lakaran."]),
    "nb": modekeys(["Klassisk bedrager", "Beskriv ordet uten å røpe det", "Gi ett hint uten å si ordet.", "Hintkjede", "Alle legger til et ord i kjeden", "Legg til et ord som henger sammen med hintene før.", "Dobbeltagent", "To hemmelige ord er i spill", "Beskriv ordet ditt — kanskje ditt er det falske.", "Emoji-modus", "Ingen prat, bare emojier", "Ingen ord — gi hintet bare med emojier.", "Lynrunde", "Sekunder hver, raskt", "Fort! Gi hintet før tiden er ute.", "Tegnemodus", "Ingen ord, bare tegningen din", "Tegn hintet i ett strøk."]),
    "pt": modekeys(["Impostor Clássico", "Descreve a palavra sem a revelar", "Dá uma pista sem dizer a palavra.", "Cadeia de Pistas", "Cada um acrescenta uma palavra", "Acrescenta uma palavra ligada às pistas anteriores.", "Agente Duplo", "Há duas palavras secretas em jogo", "Descreve a tua palavra — mas talvez a tua seja a falsa.", "Modo Emoji", "Sem falar, só emojis", "Sem palavras — dá a pista só com emojis.", "Ronda Relâmpago", "Segundos por pessoa, rápido", "Rápido! Dá a pista antes que o tempo acabe.", "Modo Desenho", "Sem palavras, só o teu desenho", "Desenha a tua pista num só traço."]),
    "ro": modekeys(["Impostor clasic", "Descrie cuvântul fără să-l dezvălui", "Dă un indiciu fără să spui cuvântul.", "Lanț de indicii", "Fiecare adaugă un cuvânt la lanț", "Adaugă un cuvânt legat de indiciile anterioare.", "Agent dublu", "Două cuvinte secrete sunt în joc", "Descrie-ți cuvântul — poate al tău e cel fals.", "Mod Emoji", "Fără vorbe, doar emoji", "Fără cuvinte — dă indiciul doar cu emoji.", "Rundă fulger", "Secunde de fiecare, rapid", "Repede! Dă indiciul înainte să expire timpul.", "Mod Desen", "Fără cuvinte, doar desenul tău", "Desenează indiciul dintr-o singură linie."]),
    "ru": modekeys(["Классический самозванец", "Опиши слово, не выдавая его", "Дай одну подсказку, не называя слово.", "Цепочка подсказок", "Каждый добавляет слово в цепочку", "Добавь слово, связанное с прежними подсказками.", "Двойной агент", "В игре два секретных слова", "Опиши своё слово — но, может, твоё поддельное.", "Режим эмодзи", "Без слов, только эмодзи", "Без слов — дай подсказку только эмодзи.", "Быстрый раунд", "Секунды на каждого, быстро", "Быстрее! Дай подсказку, пока не вышло время.", "Режим рисования", "Без слов, только твой рисунок", "Нарисуй подсказку одной линией."]),
    "uk": modekeys(["Класичний самозванець", "Опиши слово, не видаючи його", "Дай одну підказку, не називаючи слово.", "Ланцюг підказок", "Кожен додає слово до ланцюга", "Додай слово, пов'язане з попередніми підказками.", "Подвійний агент", "У грі два таємні слова", "Опиши своє слово — але, можливо, твоє фальшиве.", "Режим емодзі", "Без слів, лише емодзі", "Без слів — дай підказку лише емодзі.", "Швидкий раунд", "Секунди на кожного, швидко", "Швидше! Дай підказку, поки не вийшов час.", "Режим малювання", "Без слів, лише твій малюнок", "Намалюй підказку однією лінією."]),
    "el": modekeys(["Κλασικός απατεώνας", "Περίγραψε τη λέξη χωρίς να την αποκαλύψεις", "Δώσε ένα στοιχείο χωρίς να πεις τη λέξη.", "Αλυσίδα στοιχείων", "Καθένας προσθέτει μια λέξη", "Πρόσθεσε μια λέξη που συνδέεται με τα προηγούμενα.", "Διπλός πράκτορας", "Δύο μυστικές λέξεις παίζουν", "Περίγραψε τη λέξη σου — ίσως η δική σου είναι ψεύτικη.", "Λειτουργία Emoji", "Χωρίς ομιλία, μόνο emoji", "Χωρίς λέξεις — δώσε το στοιχείο μόνο με emoji.", "Γύρος αστραπή", "Δευτερόλεπτα ο καθένας, γρήγορα", "Γρήγορα! Δώσε το στοιχείο πριν τελειώσει ο χρόνος.", "Λειτουργία σχεδίασης", "Χωρίς λέξεις, μόνο το σχέδιό σου", "Σχεδίασε το στοιχείο με μία γραμμή."]),
    "cs": modekeys(["Klasický podvodník", "Popiš slovo, ale neprozraď ho", "Dej jednu nápovědu, aniž bys řekl slovo.", "Řetěz nápověd", "Každý přidá slovo do řetězu", "Přidej slovo navazující na předchozí nápovědy.", "Dvojitý agent", "Ve hře jsou dvě tajná slova", "Popiš své slovo — možná je to tvoje falešné.", "Režim Emoji", "Žádné mluvení, jen emoji", "Bez slov — dej nápovědu jen emoji.", "Bleskové kolo", "Sekundy na každého, rychle", "Rychle! Dej nápovědu, než vyprší čas.", "Režim kreslení", "Žádná slova, jen tvá kresba", "Nakresli nápovědu jedním tahem."]),
    "es": modekeys(["Impostor clásico", "Describe la palabra sin revelarla", "Da una pista sin decir la palabra.", "Cadena de pistas", "Cada uno añade una palabra", "Añade una palabra ligada a las pistas anteriores.", "Agente doble", "Hay dos palabras secretas en juego", "Describe tu palabra — pero quizá la tuya es la falsa.", "Modo Emoji", "Sin hablar, solo emojis", "Sin palabras — da tu pista solo con emojis.", "Ronda relámpago", "Segundos por persona, rápido", "¡Rápido! Da tu pista antes de que acabe el tiempo.", "Modo Dibujo", "Sin palabras, solo tu dibujo", "Dibuja tu pista de un solo trazo."]),
    "sv": modekeys(["Klassisk bedragare", "Beskriv ordet utan att avslöja det", "Ge en ledtråd utan att säga ordet.", "Ledtrådskedja", "Alla lägger till ett ord i kedjan", "Lägg till ett ord som knyter an till tidigare ledtrådar.", "Dubbelagent", "Två hemliga ord är i spel", "Beskriv ditt ord — men kanske är ditt det falska.", "Emoji-läge", "Inget prat, bara emojis", "Inga ord — ge din ledtråd med bara emojis.", "Blixtrunda", "Sekunder var, snabbt", "Snabbt! Ge din ledtråd innan tiden tar slut.", "Ritläge", "Inga ord, bara din teckning", "Rita din ledtråd med ett enda streck."]),
    "it": modekeys(["Impostore classico", "Descrivi la parola senza rivelarla", "Dai un indizio senza dire la parola.", "Catena di indizi", "Ognuno aggiunge una parola", "Aggiungi una parola legata agli indizi precedenti.", "Agente doppio", "Ci sono due parole segrete", "Descrivi la tua parola — ma forse la tua è quella falsa.", "Modalità Emoji", "Niente parole, solo emoji", "Niente parole — dai l'indizio solo con emoji.", "Round lampo", "Secondi a testa, veloce", "Veloce! Dai l'indizio prima che scada il tempo.", "Modalità Disegno", "Niente parole, solo il tuo disegno", "Disegna il tuo indizio con un solo tratto."]),
}

def obkeys(vals):
    ks = ["onboarding.1.title", "onboarding.1.body", "onboarding.1.cta",
          "onboarding.2.title", "onboarding.2.body", "onboarding.2.cta",
          "onboarding.3.title", "onboarding.3.body", "onboarding.3.cta"]
    return dict(zip(ks, vals))

ONBOARD = {
    "de": obkeys(["Alle dabei. Einer lügt.", "Reicht das Handy herum. Alle sehen dasselbe geheime Wort — außer einem. Das ist der Betrüger.", "Wie das?", "Gib einen Hinweis, verrate nichts", "Du bist dran: Deute das Wort an, ohne es zu sagen. Zwinkere den Wissenden zu, täusche den Betrüger. Der Betrüger blufft nur.", "Und dann?", "Reden, verdächtigen, entlarven", "Diskutiert und zeigt auf den Verdächtigen. Trefft den Richtigen und ihr gewinnt; entkommt der Betrüger, ist die Runde seine.", "Los geht's"]),
    "ar": obkeys(["الجميع هنا. واحد يكذب.", "مرّروا الهاتف. الجميع يرى الكلمة السرية نفسها — إلا واحدًا. هذا هو الدخيل.", "كيف ذلك؟", "أعطِ تلميحًا دون أن تفضح", "دورك: لمّح للكلمة دون قولها. اغمز لمن يعرف، اخدع الدخيل. أما الدخيل فيخادع فقط.", "ثم ماذا؟", "تحدّث، اشتبه، اكشف", "ناقشوا ثم أشيروا إلى المشتبه به. أصيبوا الصحيح وتفوزون؛ أفلت الدخيل فالجولة له.", "لنبدأ"]),
    "be": obkeys(["Усе тут. Адзін хлусіць.", "Перадавайце тэлефон. Усе бачаць адно сакрэтнае слова — акрамя аднаго. Гэта самазванец.", "Як гэта?", "Дай падказку, але не выдай", "Твая чарга: намякні на слова, не называючы яго. Падміргні тым, хто ведае, абдуры самазванца. Самазванец жа проста блефуе.", "А потым?", "Гавары, падазравай, выкрывай", "Абмяркуйце і пакажыце на падазронага. Знойдзеце правільнага — выйграеце; уцячэ самазванец — раунд яго.", "Пачнём"]),
    "da": obkeys(["Alle er med. En lyver.", "Send telefonen rundt. Alle ser det samme hemmelige ord — undtagen én. Det er bedrageren.", "Hvordan det?", "Giv et hint, røb intet", "Din tur: antyd ordet uden at sige det. Blink til dem der ved det, narr bedrageren. Bedrageren bluffer bare.", "Og så?", "Tal, mistænk, afslør", "Diskutér og peg på den mistænkte. Ram den rigtige og I vinder; slipper bedrageren væk, er runden hans.", "Lad os begynde"]),
    "id": obkeys(["Semua ikut. Satu berbohong.", "Edarkan ponsel. Semua melihat kata rahasia sama — kecuali satu. Itulah si penyusup.", "Bagaimana bisa?", "Beri petunjuk, jangan bocorkan", "Giliranmu: isyaratkan katanya tanpa menyebut. Kedipi yang tahu, kelabui penyusup. Si penyusup cuma menggertak.", "Lalu?", "Bicara, curigai, bongkar", "Berdebat lalu tunjuk tersangka. Tepat sasaran, kalian menang; penyusup lolos, ronde jadi miliknya.", "Ayo mulai"]),
    "fil": obkeys(["Kasama lahat. Isa ang nagsisinungaling.", "Ipasa ang telepono. Iisa ang nakikitang lihim na salita — maliban sa isa. Siya ang imposter.", "Paano 'yon?", "Magbigay ng clue, wag ibunyag", "Turn mo: ipahiwatig nang di binibigkas. Kindatan ang nakakaalam, lokohin ang imposter. Ang imposter, nag-bbluff lang.", "Tapos?", "Mag-usap, maghinala, ibunyag", "Magtalo at ituro ang suspek. Tama kayo, panalo; nakatakas ang imposter, kanya ang round.", "Simulan na"]),
    "fi": obkeys(["Kaikki mukana. Yksi valehtelee.", "Kierrätä puhelinta. Kaikki näkevät saman salaisen sanan — paitsi yksi. Hän on huijari.", "Miten niin?", "Anna vihje, älä paljasta", "Sinun vuorosi: vihjaa sanaan sanomatta sitä. Iskе silmää tietäville, hämää huijaria. Huijari vain bluffaa.", "Entä sitten?", "Puhu, epäile, paljasta", "Keskustelkaa ja osoittakaa epäiltyä. Osukaa oikeaan ja voitatte; huijarin livahtaessa kierros on hänen.", "Aloitetaan"]),
    "fr": obkeys(["Tous présents. Un ment.", "Faites tourner le téléphone. Tous voient le même mot secret — sauf un. C'est l'imposteur.", "C'est-à-dire ?", "Donne un indice, sans te trahir", "À toi : évoque le mot sans le dire. Fais un clin d'œil aux initiés, trompe l'imposteur. Lui, il bluffe.", "Et ensuite ?", "Parle, soupçonne, démasque", "Débattez puis pointez le suspect. Visez juste et vous gagnez ; si l'imposteur s'échappe, la manche est à lui.", "C'est parti"]),
    "nl": obkeys(["Iedereen mee. Eén liegt.", "Geef de telefoon door. Iedereen ziet hetzelfde geheime woord — behalve één. Dat is de bedrieger.", "Hoezo?", "Geef een hint, verklap niks", "Jouw beurt: hint naar het woord zonder het te zeggen. Knipoog naar wie het weet, misleid de bedrieger. Die bluft gewoon.", "En dan?", "Praat, verdenk, ontmasker", "Overleg en wijs de verdachte aan. Raak de juiste en je wint; ontsnapt de bedrieger, dan is de ronde van hem.", "We beginnen"]),
    "hr": obkeys(["Svi su tu. Jedan laže.", "Dodajte telefon. Svi vide istu tajnu riječ — osim jednog. To je varalica.", "Kako to?", "Daj natuknicu, ne odaj se", "Tvoj red: natukni riječ bez izgovaranja. Namigni onima koji znaju, prevari varalicu. Varalica samo blefira.", "A onda?", "Pričaj, sumnjaj, razotkrij", "Raspravite pa upri prst u sumnjivca. Pogodite pravog i pobjeđujete; umakne li varalica, runda je njegova.", "Krenimo"]),
    "ca": obkeys(["Tothom hi és. Un menteix.", "Passeu el telèfon. Tots veuen la mateixa paraula secreta — excepte un. És l'impostor.", "Com és això?", "Dona una pista, sense delatar-te", "El teu torn: insinua la paraula sense dir-la. Pica l'ullet als qui ho saben, enganya l'impostor. Ell només fa faroL.", "I després?", "Parla, sospita, desemmascara", "Debateu i assenyaleu el sospitós. Encerteu el bo i guanyeu; si l'impostor s'escapa, la ronda és seva.", "Comencem"]),
    "pl": obkeys(["Wszyscy grają. Jeden kłamie.", "Podawajcie telefon. Wszyscy widzą to samo tajne słowo — oprócz jednego. To oszust.", "Jak to?", "Daj wskazówkę, nie wygadaj się", "Twoja kolej: napomknij o słowie, nie mówiąc go. Mrugnij do wtajemniczonych, zmyl oszusta. On tylko blefuje.", "I co dalej?", "Rozmawiaj, podejrzewaj, demaskuj", "Dyskutujcie i wskażcie podejrzanego. Trafcie właściwego, a wygrywacie; oszust ucieknie — runda jego.", "Zaczynamy"]),
    "ms": obkeys(["Semua sertai. Seorang menipu.", "Edarkan telefon. Semua nampak perkataan rahsia sama — kecuali seorang. Itulah penyamar.", "Macam mana?", "Beri petunjuk, jangan bocor", "Giliran kamu: isyaratkan perkataan tanpa menyebut. Kenyit pada yang tahu, perdaya penyamar. Penyamar cuma berlagak.", "Kemudian?", "Berbual, syak, dedah", "Berbincang lalu tuding suspek. Tepat, kamu menang; penyamar terlepas, pusingan miliknya.", "Jom mula"]),
    "nb": obkeys(["Alle er med. Én lyver.", "Send telefonen rundt. Alle ser det samme hemmelige ordet — bortsett fra én. Det er bedrageren.", "Hvordan da?", "Gi et hint, røp ingenting", "Din tur: antyd ordet uten å si det. Blunk til dem som vet, lur bedrageren. Bedrageren bare bløffer.", "Og så?", "Snakk, mistenk, avslør", "Diskutér og pek på den mistenkte. Treff riktig og dere vinner; slipper bedrageren unna, er runden hans.", "La oss begynne"]),
    "pt": obkeys(["Todos dentro. Um mente.", "Passem o telefone. Todos veem a mesma palavra secreta — exceto um. Esse é o impostor.", "Como assim?", "Dá uma pista, sem te entregar", "A tua vez: sugere a palavra sem a dizer. Pisca aos que sabem, engana o impostor. Ele só faz bluff.", "E depois?", "Fala, suspeita, expõe", "Debatam e apontem ao suspeito. Acertem no certo e ganham; se o impostor escapar, a ronda é dele.", "Vamos começar"]),
    "ro": obkeys(["Toți sunt aici. Unul minte.", "Pasați telefonul. Toți văd același cuvânt secret — mai puțin unul. Acela e impostorul.", "Cum adică?", "Dă un indiciu, nu te da de gol", "E rândul tău: sugerează cuvântul fără să-l spui. Fă cu ochiul celor care știu, păcălește impostorul. El doar blufează.", "Și apoi?", "Vorbește, suspectează, demască", "Dezbateți și arătați spre suspect. Nimeriți-l pe cel bun și câștigați; scapă impostorul, runda e a lui.", "Să începem"]),
    "ru": obkeys(["Все в деле. Один лжёт.", "Передавайте телефон. Все видят одно секретное слово — кроме одного. Это самозванец.", "Это как?", "Дай подсказку, но не выдай", "Твой ход: намекни на слово, не называя его. Подмигни знающим, обмани самозванца. Он же просто блефует.", "А дальше?", "Говори, подозревай, разоблачай", "Обсудите и укажите на подозреваемого. Угадали — победа; самозванец ускользнул — раунд за ним.", "Начнём"]),
    "uk": obkeys(["Усі в грі. Один бреше.", "Передавайте телефон. Усі бачать одне таємне слово — крім одного. Це самозванець.", "Тобто як?", "Дай підказку, та не видай", "Твоя черга: натякни на слово, не називаючи. Підморгни тим, хто знає, обдури самозванця. Він лише блефує.", "А далі?", "Говори, підозрюй, викривай", "Обговоріть і вкажіть на підозрюваного. Вгадали — перемога; самозванець утік — раунд його.", "Почнімо"]),
    "el": obkeys(["Όλοι μέσα. Ένας λέει ψέματα.", "Περάστε το τηλέφωνο. Όλοι βλέπουν την ίδια μυστική λέξη — εκτός από έναν. Αυτός είναι ο απατεώνας.", "Δηλαδή;", "Δώσε στοιχείο, μην προδοθείς", "Σειρά σου: υπαινίξου τη λέξη χωρίς να την πεις. Κλείσε το μάτι σε όσους ξέρουν, ξεγέλασε τον απατεώνα. Αυτός απλώς μπλοφάρει.", "Και μετά;", "Μίλα, υποψιάσου, ξεσκέπασε", "Συζητήστε και δείξτε τον ύποπτο. Βρείτε τον σωστό και κερδίζετε· ξεφύγει ο απατεώνας, ο γύρος δικός του.", "Ας ξεκινήσουμε"]),
    "cs": obkeys(["Všichni hrají. Jeden lže.", "Posílejte telefon dokola. Všichni vidí stejné tajné slovo — kromě jednoho. To je podvodník.", "Jak to?", "Dej nápovědu, neprozraď se", "Jsi na řadě: naznač slovo, aniž bys ho řekl. Mrkni na ty, co vědí, oklam podvodníka. Ten jen blafuje.", "A pak?", "Mluv, podezřívej, odhal", "Diskutujte a ukažte na podezřelého. Trefte správného a vyhráváte; unikne podvodník, kolo je jeho.", "Začněme"]),
    "es": obkeys(["Todos dentro. Uno miente.", "Pasad el teléfono. Todos ven la misma palabra secreta — menos uno. Ese es el impostor.", "¿Cómo es eso?", "Da una pista, sin delatarte", "Tu turno: insinúa la palabra sin decirla. Guiña a los que saben, engaña al impostor. Él solo farolea.", "¿Y luego?", "Habla, sospecha, desenmascara", "Debatid y señalad al sospechoso. Acertad al bueno y ganáis; si el impostor se escapa, la ronda es suya.", "Empecemos"]),
    "sv": obkeys(["Alla med. En ljuger.", "Skicka runt telefonen. Alla ser samma hemliga ord — utom en. Det är bedragaren.", "Hur då?", "Ge en ledtråd, avslöja inget", "Din tur: antyd ordet utan att säga det. Blinka åt de som vet, lura bedragaren. Bedragaren bara bluffar.", "Och sen?", "Prata, misstänk, avslöja", "Diskutera och peka på den misstänkte. Träffa rätt och ni vinner; slipper bedragaren undan är rundan hans.", "Nu kör vi"]),
    "it": obkeys(["Ci sono tutti. Uno mente.", "Passate il telefono. Tutti vedono la stessa parola segreta — tranne uno. Quello è l'impostore.", "Cioè?", "Dai un indizio, non tradirti", "Tocca a te: allude alla parola senza dirla. Strizza l'occhio a chi sa, inganna l'impostore. Lui bluffa e basta.", "E poi?", "Parla, sospetta, smaschera", "Discutete e indicate il sospettato. Azzeccate quello giusto e vincete; se l'impostore sfugge, il round è suo.", "Iniziamo"]),
}

if __name__ == "__main__":
    tables = {"REVEAL": REVEAL, "CLUE": CLUE, "DISCUSS": DISCUSS, "VOTE": VOTE, "HOME": HOME, "PLAYERS": PLAYERS, "CATS": CATS, "GSET": GSET, "MODES": MODES, "ONBOARD": ONBOARD}
    which = sys.argv[1] if len(sys.argv) > 1 else "CLUE"
    n = apply(tables[which])
    print("updated", n, "files with", which)
