#!/usr/bin/env python3
"""Generate remaining Imposter Party locales: de, fr, it, el, ro, nl, pl."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
EN = json.loads((OUT / "en.json").read_text(encoding="utf-8"))

def write(code, over):
    data = dict(EN)
    data.update(over)
    path = OUT / f"{code}.json"
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.name} ({len(data)} keys)")

DE = {
  "meta.languageName": "Deutsch", "meta.locale": "de",
  "common.continue": "Weiter", "common.next": "Weiter", "common.back": "Zurück",
  "common.close": "Schließen", "common.cancel": "Abbrechen", "common.gotIt": "Verstanden!",
  "common.play": "SPIELEN", "common.skip": "Überspringen", "common.settings": "Einstellungen",
  "common.info": "Info", "common.accept": "Akzeptieren", "common.decline": "Ablehnen",
  "common.on": "An", "common.off": "Aus", "common.restore": "Wiederherstellen",
  "common.terms": "Bedingungen", "common.privacy": "Datenschutz",
  "onboarding.1.title": "Sofortiger Spaß überall!",
  "onboarding.1.body": "Spieleabend, Roadtrip oder erstes Date — Imposter Party bricht das Eis.",
  "onboarding.1.cta": "Ich bin dabei!",
  "onboarding.2.title": "Wer spielt Theater?",
  "onboarding.2.body": "Einer lügt. Die anderen kennen das Wort. Findest du den Imposter rechtzeitig?",
  "onboarding.2.cta": "Verstanden",
  "onboarding.3.title": "Sprich klug. Rate gut.",
  "onboarding.3.body": "Beschreibe das Geheimwort, ohne es zu sagen. Vorsicht — der Imposter hört mit.",
  "onboarding.3.cta": "Los geht’s!",
  "tutorial.1.title": "Themen wählen", "tutorial.1.body": "Wähle ein oder mehrere Themen passend zur Party.",
  "tutorial.2.title": "Rolle prüfen", "tutorial.2.body": "Alle sehen das Wort… außer dem Imposter. Sein Ziel: untertauchen.",
  "tutorial.3.title": "Hinweis geben", "tutorial.3.body": "Ein kluger Hinweis: klar für Wissende — verwirrend für den Imposter.",
  "tutorial.4.title": "Zeit zum Abstimmen", "tutorial.4.body": "Gespräch vorbei. Stimme ab und entlarve den Imposter!",
  "tutorial.4.win": "Richtig — ihr gewinnt", "tutorial.4.lose": "Daneben — der Imposter gewinnt",
  "tutorial.4.warning": "Errät der Imposter das Wort vor Ablauf, gewinnt er sofort",
  "paywall.title": "Weiter für vollen Zugang", "paywall.freeTrial": "Noch unsicher? Kostenlos testen",
  "paywall.yearly": "Jährlich", "paywall.weekly": "Wöchentlich", "paywall.bestDeal": "Bestes Angebot",
  "paywall.mostPopular": "Am beliebtesten", "paywall.cancelAnytime": "Jederzeit kündbar",
  "paywall.tryFree": "Kostenlos testen", "paywall.continue": "Weiter",
  "home.classicTitle": "Klassischer Imposter", "home.classicSubtitle": "Beschreibe das Wort, ohne erwischt zu werden!",
  "home.drawingTitle": "Zeichenmodus", "home.drawingSubtitle": "Keine Worte — nur dein Zeichentalent!",
  "settings.title": "Einstellungen", "settings.language": "Sprache", "settings.contact": "Kontakt",
  "settings.privacy": "Datenschutz", "settings.terms": "Nutzungsbedingungen",
  "settings.vibration": "Vibration", "settings.userId": "Benutzer-ID: {id}",
  "players.title": "Spieler hinzufügen", "players.placeholder": "Name von Spieler {n}",
  "players.add": "Spieler hinzufügen", "players.minHint": "Mindestens 3 Spieler", "players.maxHint": "Maximal 15 Spieler",
  "categories.title": "Kategorien", "categories.selected": "{n} Kategorie(n)",
  "categories.party": "Partyzeit", "categories.partyDesc": "Lachen, Chaos und Spaß für jede Gruppe.",
  "categories.football": "Fußball", "categories.footballDesc": "Tore, Legenden und goldene Schuhe — sei Fan!",
  "categories.food": "Essen", "categories.foodDesc": "Leckere Themen — falsch tippen und du bist toast!",
  "categories.celebs": "Promis", "categories.celebsDesc": "Namen aus Film und Musik. Smalltalk!",
  "categories.hobbies": "Hobbys", "categories.hobbiesDesc": "Leidenschaften — erfinde oder fliege auf!",
  "categories.family": "Familie", "categories.familyDesc": "Familie kennt dich — erwischt sie den Bluff?",
  "categories.education": "Schule", "categories.educationDesc": "Prüfungen und Schule — bluffe wie Hausaufgaben erledigt!",
  "categories.nature": "Natur", "categories.natureDesc": "Bäume, Ozeane und Wildnis — tu so, als kenntest du dich aus.",
  "categories.characters": "Charaktere", "categories.charactersDesc": "Helden und Schurken — tu so, als kenntest du sie.",
  "categories.jobs": "Berufe", "categories.jobsDesc": "Vom Chirurgen zum Streamer — spiele mit oder fliege auf!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Filme und Kultmomente — bleib auf der Bühne.",
  "categories.brands": "Marken", "categories.brandsDesc": "Bekannte Namen und Dinge — finde sie oder fake es!",
  "categories.places": "Orte", "categories.placesDesc": "Länder und Städte — tu so, als wärst du da gewesen!",
  "categories.animals": "Tiere", "categories.animalsDesc": "Von Haustieren bis Raubtieren — kannst du untertauchen?",
  "categories.sports": "Sport", "categories.sportsDesc": "Fan oder Faker — lass es nicht merken.",
  "categories.newyear": "Neujahr", "categories.newyearDesc": "Winterspaß — wer ist brav, wer frech?",
  "gameSettings.title": "Spieleinstellungen", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Manche Runden drehen die Regeln um. Erwarte Überraschungen!",
  "gameSettings.imposters": "Imposter", "gameSettings.impostersDesc": "Wie viele geheime Imposter? Für {n} Spieler empfohlen: {rec}",
  "gameSettings.roundDuration": "Rundendauer", "gameSettings.roundDurationDesc": "Wie lange dauert die Diskussion?",
  "gameSettings.imposterHints": "Hinweise für Imposter", "gameSettings.imposterHintsDesc": "Sollen Imposter einen Hinweis zum Wort bekommen?",
  "gameSettings.playSummary": "{n} Imposter",
  "pass.givePhone": "Gib das Handy an {name}", "pass.swipeHint": "Nach oben wischen, um das Geheimwort zu sehen",
  "pass.imposter": "IMPOSTER", "pass.hint": "Hinweis: {hint}",
  "pass.readyTitle": "Bereit zum Start!", "pass.startGame": "Spiel starten",
  "round.startAsking": "Fang an zu fragen!", "round.pause": "Pause", "round.resume": "Fortsetzen",
  "round.paused": "Pausiert", "round.tapToContinue": "Tippen zum Fortsetzen", "round.vote": "Abstimmen",
  "round.howToTitle": "So spielt man",
  "round.howTo1": "Kennst du das Wort? Gib clevere Hinweise — verrate es nicht.",
  "round.howTo2": "Bist du der Imposter? Mische dich unter und rate aus den Hinweisen.",
  "round.howTo3": "Wenn bereit: Pause und stimmt ab.",
  "drawing.starting": "{name} beginnt", "drawing.instruction": "Zeichne den Hinweis in einem Strich, dann weitergeben",
  "drawing.exitTitle": "Spiel verlassen?", "drawing.exitBody": "Wirklich das aktuelle Spiel verlassen?", "drawing.exitConfirm": "Verlassen",
  "vote.title": "Wer ist der Imposter?", "vote.instruction": "Stimme für den, der deiner Meinung nach blufft",
  "vote.ready": "Wenn bereit, Stimmen senden!", "vote.send": "STIMMEN SENDEN",
  "results.title": "Ergebnisse", "results.imposterWins": "Imposter gewinnt!",
  "results.imposterWinsBody": "Der Imposter ist unbemerkt entkommen", "results.crewWins": "Team gewinnt!",
  "results.crewWinsBody": "Ihr habt den Imposter gefunden!", "results.imposterGuessed": "Imposter gewinnt!",
  "results.imposterGuessedBody": "Der Imposter hat das Geheimwort erraten", "results.secretWord": "Geheimwort",
  "results.playAgain": "NOCHMAL SPIELEN", "results.momentOfTruth": "AUGENBLICK DER WAHRHEIT",
  "rate.title": "Bewerte Imposter Party!", "rate.body": "Wir stecken unser Herz in dieses Spiel.",
  "rate.incentive": "Deine Bewertung hilft uns — 5 Sterne", "rate.cta": "Bewerten",
  "support.title": "Support verbessern", "support.body": "Begrenzte Nutzungsdaten können an Apple geteilt werden, um Support und Käufe zu verbessern.",
}

FR = {
  "meta.languageName": "Français", "meta.locale": "fr",
  "common.continue": "Continuer", "common.next": "Suivant", "common.back": "Retour",
  "common.close": "Fermer", "common.cancel": "Annuler", "common.gotIt": "Compris !",
  "common.play": "JOUER", "common.skip": "Passer", "common.settings": "Réglages",
  "common.info": "Info", "common.accept": "Accepter", "common.decline": "Refuser",
  "common.on": "Oui", "common.off": "Non", "common.restore": "Restaurer",
  "common.terms": "Conditions", "common.privacy": "Confidentialité",
  "onboarding.1.title": "Du fun partout, tout de suite !",
  "onboarding.1.body": "Soirée jeux, route ou premier rendez-vous bizarre — Imposter Party brise la glace.",
  "onboarding.1.cta": "J’en suis !",
  "onboarding.2.title": "Qui fait semblant ?",
  "onboarding.2.body": "L’un d’entre vous ment. Les autres connaissent le mot. Trouvez l’imposteur à temps ?",
  "onboarding.2.cta": "Compris",
  "onboarding.3.title": "Parle malin. Devine bien.",
  "onboarding.3.body": "Décris le mot secret sans le dire. Attention — l’imposteur écoute.",
  "onboarding.3.cta": "On joue !",
  "tutorial.1.title": "Choisis des thèmes", "tutorial.1.body": "Choisis un ou plusieurs thèmes selon l’ambiance.",
  "tutorial.2.title": "Vérifie ton rôle", "tutorial.2.body": "Tout le monde voit le mot… sauf l’imposteur. Son but : se fondre.",
  "tutorial.3.title": "Donne un indice", "tutorial.3.body": "Un indice malin : clair pour ceux qui savent — confus pour l’imposteur.",
  "tutorial.4.title": "Votez !", "tutorial.4.body": "Fin des discussions. Votez pour démasquer l’imposteur !",
  "tutorial.4.win": "Bon choix — vous gagnez", "tutorial.4.lose": "Raté — l’Imposteur gagne",
  "tutorial.4.warning": "Si l’imposteur trouve le mot à temps, il gagne aussitôt",
  "paywall.title": "Continuez pour un accès complet", "paywall.freeTrial": "Pas sûr ? Essayez gratuitement",
  "paywall.yearly": "Annuel", "paywall.weekly": "Hebdo", "paywall.bestDeal": "Meilleure offre",
  "paywall.mostPopular": "Le plus populaire", "paywall.cancelAnytime": "Annulez quand vous voulez",
  "paywall.tryFree": "Essayer gratuitement", "paywall.continue": "Continuer",
  "home.classicTitle": "Imposter classique", "home.classicSubtitle": "Décris le mot sans te faire prendre !",
  "home.drawingTitle": "Mode dessin", "home.drawingSubtitle": "Pas de mots — juste ton dessin !",
  "settings.title": "Réglages", "settings.language": "Langue", "settings.contact": "Nous contacter",
  "settings.privacy": "Confidentialité", "settings.terms": "Conditions d’utilisation",
  "settings.vibration": "Vibration", "settings.userId": "ID utilisateur : {id}",
  "players.title": "Ajouter des joueurs", "players.placeholder": "Nom du joueur {n}",
  "players.add": "Ajouter un joueur", "players.minHint": "Au moins 3 joueurs", "players.maxHint": "Maximum 15 joueurs",
  "categories.title": "Catégories", "categories.selected": "{n} catégorie(s)",
  "categories.party": "Fête", "categories.partyDesc": "Rires, chaos et fun pour tout groupe.",
  "categories.football": "Football", "categories.footballDesc": "Buts, légendes et crampons d’or — sois fan !",
  "categories.food": "Nourriture", "categories.foodDesc": "Sujets savoureux — un faux pas et c’est grillé !",
  "categories.celebs": "Célébrités", "categories.celebsDesc": "Noms du cinéma et de la musique. Small talk !",
  "categories.hobbies": "Loisirs", "categories.hobbiesDesc": "Passions secrètes — invente ou sois démasqué !",
  "categories.family": "Famille", "categories.familyDesc": "La famille te connaît — attraperont-ils le bluff ?",
  "categories.education": "École", "categories.educationDesc": "Examens et cours — bluffe comme si tu avais révisé !",
  "categories.nature": "Nature", "categories.natureDesc": "Arbres, océans et faune — fais l’expert.",
  "categories.characters": "Personnages", "categories.charactersDesc": "Héros et méchants — fais semblant de les connaître.",
  "categories.jobs": "Métiers", "categories.jobsDesc": "Du chirurgien au streameur — imite ou sois grillé !",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Films et moments cultes — reste sur scène.",
  "categories.brands": "Marques", "categories.brandsDesc": "Noms célèbres et objets — trouve ou fake !",
  "categories.places": "Lieux", "categories.placesDesc": "Pays et villes — comme si tu y étais allé !",
  "categories.animals": "Animaux", "categories.animalsDesc": "Des animaux de compagnie aux fauves — peux-tu te fondre ?",
  "categories.sports": "Sports", "categories.sportsDesc": "Fan ou fakeur — que ça ne se voie pas.",
  "categories.newyear": "Nouvel An", "categories.newyearDesc": "Ambiance d’hiver — qui est sage ou coquin ?",
  "gameSettings.title": "Réglages de partie", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Certains tours bouleversent les règles. Attendez l’imprévu !",
  "gameSettings.imposters": "Imposteurs", "gameSettings.impostersDesc": "Combien d’imposteurs ? Pour {n} joueurs : {rec}",
  "gameSettings.roundDuration": "Durée du tour", "gameSettings.roundDurationDesc": "Combien dure la discussion ?",
  "gameSettings.imposterHints": "Indices pour imposteurs", "gameSettings.imposterHintsDesc": "Les imposteurs doivent-ils recevoir un indice ?",
  "gameSettings.playSummary": "{n} imposteur(s)",
  "pass.givePhone": "Passe le téléphone à {name}", "pass.swipeHint": "Glisse vers le haut pour voir le mot secret",
  "pass.imposter": "IMPOSTEUR", "pass.hint": "Indice : {hint}",
  "pass.readyTitle": "Prêts à commencer !", "pass.startGame": "Lancer la partie",
  "round.startAsking": "Commence à poser des questions !", "round.pause": "Pause", "round.resume": "Reprendre",
  "round.paused": "En pause", "round.tapToContinue": "Touche pour continuer", "round.vote": "Voter",
  "round.howToTitle": "Comment jouer",
  "round.howTo1": "Tu connais le mot ? Donne des indices malins sans le révéler.",
  "round.howTo2": "Tu es l’Imposteur ? Fond-toi et devine grâce aux indices.",
  "round.howTo3": "Quand vous êtes prêts, pausez et votez.",
  "drawing.starting": "{name} commence", "drawing.instruction": "Dessine l’indice en un seul trait, puis passe",
  "drawing.exitTitle": "Quitter la partie ?", "drawing.exitBody": "Sûr de vouloir quitter ?", "drawing.exitConfirm": "Quitter",
  "vote.title": "Qui est l’Imposteur ?", "vote.instruction": "Vote pour celui qui fait semblant",
  "vote.ready": "Prêts ? Envoyez les votes !", "vote.send": "ENVOYER LES VOTES",
  "results.title": "Résultats", "results.imposterWins": "L’Imposteur gagne !",
  "results.imposterWinsBody": "L’imposteur s’est échappé sans être vu", "results.crewWins": "L’équipe gagne !",
  "results.crewWinsBody": "Vous avez trouvé l’imposteur !", "results.imposterGuessed": "L’Imposteur gagne !",
  "results.imposterGuessedBody": "L’imposteur a trouvé le mot secret", "results.secretWord": "Mot secret",
  "results.playAgain": "REJOUER", "results.momentOfTruth": "MOMENT DE VÉRITÉ",
  "rate.title": "Note Imposter Party !", "rate.body": "On a mis tout notre cœur dans ce jeu.",
  "rate.incentive": "Ton avis nous aide — 5 étoiles", "rate.cta": "Nous noter",
  "support.title": "Améliorer le support", "support.body": "Des données d’usage limitées peuvent être partagées avec Apple pour améliorer le support et les achats.",
}

IT = {
  "meta.languageName": "Italiano", "meta.locale": "it",
  "common.continue": "Continua", "common.next": "Avanti", "common.back": "Indietro",
  "common.close": "Chiudi", "common.cancel": "Annulla", "common.gotIt": "Capito!",
  "common.play": "GIOCA", "common.skip": "Salta", "common.settings": "Impostazioni",
  "common.info": "Info", "common.accept": "Accetta", "common.decline": "Rifiuta",
  "common.on": "Sì", "common.off": "No", "common.restore": "Ripristina",
  "common.terms": "Termini", "common.privacy": "Privacy",
  "onboarding.1.title": "Divertimento ovunque, subito!",
  "onboarding.1.body": "Serata giochi, viaggio o primo appuntamento strano — Imposter Party spezza il ghiaccio.",
  "onboarding.1.cta": "Ci sto!",
  "onboarding.2.title": "Chi sta fingendo?",
  "onboarding.2.body": "Uno mente. Gli altri sanno la parola. Troverete l’impostore in tempo?",
  "onboarding.2.cta": "Capito",
  "onboarding.3.title": "Parla bene. Indovina meglio.",
  "onboarding.3.body": "Descrivi la parola segreta senza dirla. Attento — l’impostore ascolta.",
  "onboarding.3.cta": "Giochiamo!",
  "tutorial.1.title": "Scegli i temi", "tutorial.1.body": "Scegli uno o più temi adatti alla festa.",
  "tutorial.2.title": "Controlla il ruolo", "tutorial.2.body": "Tutti vedono la parola… tranne l’impostore. Il suo scopo: mimetizzarsi.",
  "tutorial.3.title": "Dai un indizio", "tutorial.3.body": "Un indizio furbo: chiaro per chi sa — confuso per l’impostore.",
  "tutorial.4.title": "Tempo di votare", "tutorial.4.body": "Fine chiacchiere. Votate per smascherare l’impostore!",
  "tutorial.4.win": "Giusto — avete vinto", "tutorial.4.lose": "Sbagliato — vince l’Impostore",
  "tutorial.4.warning": "Se l’impostore indovina la parola in tempo, vince subito",
  "paywall.title": "Continua per l’accesso completo", "paywall.freeTrial": "Non sei sicuro? Prova gratis",
  "paywall.yearly": "Annuale", "paywall.weekly": "Settimanale", "paywall.bestDeal": "Offerta migliore",
  "paywall.mostPopular": "Più popolare", "paywall.cancelAnytime": "Annulla quando vuoi",
  "paywall.tryFree": "Prova gratis", "paywall.continue": "Continua",
  "home.classicTitle": "Imposter classico", "home.classicSubtitle": "Descrivi la parola senza farti beccare!",
  "home.drawingTitle": "Modalità disegno", "home.drawingSubtitle": "Niente parole — solo il tuo disegno!",
  "settings.title": "Impostazioni", "settings.language": "Lingua", "settings.contact": "Contattaci",
  "settings.privacy": "Privacy", "settings.terms": "Termini d’uso",
  "settings.vibration": "Vibrazione", "settings.userId": "ID utente: {id}",
  "players.title": "Aggiungi giocatori", "players.placeholder": "Nome del giocatore {n}",
  "players.add": "Aggiungi giocatore", "players.minHint": "Almeno 3 giocatori", "players.maxHint": "Massimo 15 giocatori",
  "categories.title": "Categorie", "categories.selected": "{n} categor(ia/ie)",
  "categories.party": "Festa", "categories.partyDesc": "Risate, caos e divertimento per ogni gruppo.",
  "categories.football": "Calcio", "categories.footballDesc": "Gol, leggende e scarpe d’oro — fai il tifoso!",
  "categories.food": "Cibo", "categories.foodDesc": "Argomenti gustosi — sbagli e sei fregato!",
  "categories.celebs": "Vip", "categories.celebsDesc": "Nomi di cinema e musica. Chiacchiere leggere!",
  "categories.hobbies": "Hobby", "categories.hobbiesDesc": "Passioni segrete — inventa o vieni smascherato!",
  "categories.family": "Famiglia", "categories.familyDesc": "La famiglia ti conosce — prenderanno il bluff?",
  "categories.education": "Scuola", "categories.educationDesc": "Esami e lezioni — bluffa come se avessi studiato!",
  "categories.nature": "Natura", "categories.natureDesc": "Alberi, oceani e fauna — fai l’esperto.",
  "categories.characters": "Personaggi", "categories.charactersDesc": "Eroi e cattivi — fai finta di conoscerli.",
  "categories.jobs": "Lavori", "categories.jobsDesc": "Dal chirurgo allo streamer — imita o ti beccano!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Film e momenti iconici — resta in scena.",
  "categories.brands": "Brand", "categories.brandsDesc": "Nomi famosi e oggetti — trovali o fingi!",
  "categories.places": "Luoghi", "categories.placesDesc": "Paesi e città — come se ci fossi stato!",
  "categories.animals": "Animali", "categories.animalsDesc": "Dagli animali domestici alle belve — sai mimetizzarti?",
  "categories.sports": "Sport", "categories.sportsDesc": "Tifoso o finto — non far vedere.",
  "categories.newyear": "Capodanno", "categories.newyearDesc": "Atmosfera invernale — chi è bravo o birichino?",
  "gameSettings.title": "Impostazioni partita", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Alcuni turni capovolgono le regole. Aspettati l’inaspettato!",
  "gameSettings.imposters": "Impostori", "gameSettings.impostersDesc": "Quanti impostori? Per {n} giocatori: {rec}",
  "gameSettings.roundDuration": "Durata turno", "gameSettings.roundDurationDesc": "Quanto dura la discussione?",
  "gameSettings.imposterHints": "Indizi per impostori", "gameSettings.imposterHintsDesc": "Gli impostori devono ricevere un indizio?",
  "gameSettings.playSummary": "{n} impostore/i",
  "pass.givePhone": "Passa il telefono a {name}", "pass.swipeHint": "Scorri in alto per vedere la parola segreta",
  "pass.imposter": "IMPOSTORE", "pass.hint": "Indizio: {hint}",
  "pass.readyTitle": "Pronti a iniziare!", "pass.startGame": "Inizia partita",
  "round.startAsking": "Inizia a chiedere!", "round.pause": "Pausa", "round.resume": "Riprendi",
  "round.paused": "In pausa", "round.tapToContinue": "Tocca per continuare", "round.vote": "Vota",
  "round.howToTitle": "Come si gioca",
  "round.howTo1": "Sai la parola? Dai indizi furbi senza rivelarla.",
  "round.howTo2": "Sei l’Impostore? Mimetizzati e indovina dagli indizi altrui.",
  "round.howTo3": "Quando siete pronti, pausa e votate.",
  "drawing.starting": "{name} inizia", "drawing.instruction": "Disegna l’indizio con un solo tratto, poi passa",
  "drawing.exitTitle": "Uscire dalla partita?", "drawing.exitBody": "Sei sicuro di voler uscire?", "drawing.exitConfirm": "Esci",
  "vote.title": "Chi è l’Impostore?", "vote.instruction": "Vota chi pensi stia fingendo",
  "vote.ready": "Pronti? Inviate i voti!", "vote.send": "INVIA VOTI",
  "results.title": "Risultati", "results.imposterWins": "Vince l’Impostore!",
  "results.imposterWinsBody": "L’impostore è scappato senza essere notato", "results.crewWins": "Vince la squadra!",
  "results.crewWinsBody": "Avete trovato l’impostore!", "results.imposterGuessed": "Vince l’Impostore!",
  "results.imposterGuessedBody": "L’impostore ha indovinato la parola segreta", "results.secretWord": "Parola segreta",
  "results.playAgain": "GIOCA ANCORA", "results.momentOfTruth": "MOMENTO DELLA VERITÀ",
  "rate.title": "Valuta Imposter Party!", "rate.body": "Ci mettiamo il cuore in questo gioco.",
  "rate.incentive": "La tua recensione ci aiuta — 5 stelle", "rate.cta": "Valutaci",
  "support.title": "Migliora il supporto", "support.body": "Dati d’uso limitati possono essere condivisi con Apple per migliorare supporto e acquisti.",
}

# Greek, Romanian, Dutch, Polish - continue in same file
EL = {
  "meta.languageName": "Ελληνικά", "meta.locale": "el",
  "common.continue": "Συνέχεια", "common.next": "Επόμενο", "common.back": "Πίσω",
  "common.close": "Κλείσιμο", "common.cancel": "Ακύρωση", "common.gotIt": "Το κατάλαβα!",
  "common.play": "ΠΑΙΞΕ", "common.skip": "Παράλειψη", "common.settings": "Ρυθμίσεις",
  "common.info": "Πληροφορίες", "common.accept": "Αποδοχή", "common.decline": "Απόρριψη",
  "common.on": "Ναι", "common.off": "Όχι", "common.restore": "Επαναφορά",
  "common.terms": "Όροι", "common.privacy": "Απόρρητο",
  "onboarding.1.title": "Άμεση διασκέδαση παντού!",
  "onboarding.1.body": "Βραδιά παιχνιδιού, ταξίδι ή πρώτο ραντεβού — το Imposter Party σπάει τον πάγο.",
  "onboarding.1.cta": "Είμαι μέσα!",
  "onboarding.2.title": "Ποιος προσποιείται;",
  "onboarding.2.body": "Ένας λέει ψέματα. Οι άλλοι ξέρουν τη λέξη. Θα βρείτε τον impostor;",
  "onboarding.2.cta": "Το κατάλαβα",
  "onboarding.3.title": "Μίλα έξυπνα. Μάντεψε σωστά.",
  "onboarding.3.body": "Περίγραψε τη μυστική λέξη χωρίς να την πεις. Πρόσεχε — ο impostor ακούει.",
  "onboarding.3.cta": "Πάμε!",
  "tutorial.1.title": "Διάλεξε θέματα", "tutorial.1.body": "Διάλεξε ένα ή περισσότερα θέματα για το πάρτι.",
  "tutorial.2.title": "Δες τον ρόλο σου", "tutorial.2.body": "Όλοι βλέπουν τη λέξη… εκτός από τον impostor. Στόχος του: να μπερδευτεί.",
  "tutorial.3.title": "Δώσε υπόδειξη", "tutorial.3.body": "Έξυπνη υπόδειξη: καθαρή για όσους ξέρουν — μπερδεμένη για τον impostor.",
  "tutorial.4.title": "Ώρα για ψήφο", "tutorial.4.body": "Τέλος συζήτησης. Ψηφίστε για να αποκαλύψετε τον impostor!",
  "tutorial.4.win": "Σωστά — κερδίσατε", "tutorial.4.lose": "Λάθος — κερδίζει ο Impostor",
  "tutorial.4.warning": "Αν ο impostor μαντέψει τη λέξη εγκαίρως, κερδίζει αμέσως",
  "paywall.title": "Συνέχισε για πλήρη πρόσβαση", "paywall.freeTrial": "Δεν είσαι σίγουρος; Δοκίμασε δωρεάν",
  "paywall.yearly": "Ετήσιο", "paywall.weekly": "Εβδομαδιαίο", "paywall.bestDeal": "Καλύτερη προσφορά",
  "paywall.mostPopular": "Πιο δημοφιλές", "paywall.cancelAnytime": "Ακύρωση οποτεδήποτε",
  "paywall.tryFree": "Δωρεάν δοκιμή", "paywall.continue": "Συνέχεια",
  "home.classicTitle": "Κλασικός Imposter", "home.classicSubtitle": "Περίγραψε τη λέξη χωρίς να σε πιάσουν!",
  "home.drawingTitle": "Λειτουργία σχεδίου", "home.drawingSubtitle": "Χωρίς λέξεις — μόνο σχέδιο!",
  "settings.title": "Ρυθμίσεις", "settings.language": "Γλώσσα", "settings.contact": "Επικοινωνία",
  "settings.privacy": "Απόρρητο", "settings.terms": "Όροι χρήσης",
  "settings.vibration": "Δόνηση", "settings.userId": "ID χρήστη: {id}",
  "players.title": "Προσθήκη παικτών", "players.placeholder": "Όνομα παίκτη {n}",
  "players.add": "Προσθήκη παίκτη", "players.minHint": "Τουλάχιστον 3 παίκτες", "players.maxHint": "Μέγιστο 15 παίκτες",
  "categories.title": "Κατηγορίες", "categories.selected": "{n} κατηγορ.",
  "categories.party": "Πάρτι", "categories.partyDesc": "Γέλια και λίγο χάος για κάθε παρέα.",
  "categories.football": "Ποδόσφαιρο", "categories.footballDesc": "Γκολ, θρύλοι και χρυσά παπούτσια — κάνε τον φαν!",
  "categories.food": "Φαγητό", "categories.foodDesc": "Νόστιμα θέματα — λάθος λέξη και κάηκες!",
  "categories.celebs": "Διάσημοι", "categories.celebsDesc": "Ονόματα από σινεμά και μουσική. Ελαφριά κουβέντα!",
  "categories.hobbies": "Χόμπι", "categories.hobbiesDesc": "Πάθη και μυστικά — επινόησε ή αποκαλύψου!",
  "categories.family": "Οικογένεια", "categories.familyDesc": "Η οικογένεια σε ξέρει — θα πιάσουν το μπλόφα;",
  "categories.education": "Σχολείο", "categories.educationDesc": "Εξετάσεις και μαθήματα — μπλόφαρε σαν να διάβασες!",
  "categories.nature": "Φύση", "categories.natureDesc": "Δέντρα, ωκεανοί και άγρια ζωή — κάνε τον ειδικό.",
  "categories.characters": "Χαρακτήρες", "categories.charactersDesc": "Ήρωες και κακοί — προσποιήσου ότι τους ξέρεις.",
  "categories.jobs": "Επαγγέλματα", "categories.jobsDesc": "Από χειρουργό έως streamer — μίμησε ή σε πιάνουν!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Ταινίες και εμβληματικές στιγμές — μείνε στη σκηνή.",
  "categories.brands": "Μάρκες", "categories.brandsDesc": "Διάσημα ονόματα και αντικείμενα — βρες ή προσποιήσου!",
  "categories.places": "Μέρη", "categories.placesDesc": "Χώρες και πόλεις — σαν να έχεις πάει!",
  "categories.animals": "Ζώα", "categories.animalsDesc": "Από κατοικίδια έως άγρια — μπορείς να μπερδευτείς;",
  "categories.sports": "Αθλήματα", "categories.sportsDesc": "Φαν ή ψεύτης — μην φανεί.",
  "categories.newyear": "Πρωτοχρονιά", "categories.newyearDesc": "Χειμωνιάτικο κέφι — ποιος είναι άτακτος;",
  "gameSettings.title": "Ρυθμίσεις παιχνιδιού", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Κάποιοι γύροι αλλάζουν τους κανόνες. Περίμενε το απρόσμενο!",
  "gameSettings.imposters": "Imposters", "gameSettings.impostersDesc": "Πόσοι μυστικοί imposters; Για {n} παίκτες: {rec}",
  "gameSettings.roundDuration": "Διάρκεια γύρου", "gameSettings.roundDurationDesc": "Πόσο διαρκεί η συζήτηση;",
  "gameSettings.imposterHints": "Υποδείξεις για imposters", "gameSettings.imposterHintsDesc": "Να παίρνουν υπόδειξη για τη λέξη;",
  "gameSettings.playSummary": "{n} impostor(es)",
  "pass.givePhone": "Δώσε το τηλέφωνο στον/στην {name}", "pass.swipeHint": "Σύρε πάνω για να δεις τη μυστική λέξη",
  "pass.imposter": "IMPOSTER", "pass.hint": "Υπόδειξη: {hint}",
  "pass.readyTitle": "Έτοιμοι να ξεκινήσουμε!", "pass.startGame": "Έναρξη παιχνιδιού",
  "round.startAsking": "Ξεκίνα τις ερωτήσεις!", "round.pause": "Παύση", "round.resume": "Συνέχεια",
  "round.paused": "Σε παύση", "round.tapToContinue": "Πάτα για συνέχεια", "round.vote": "Ψήφος",
  "round.howToTitle": "Πώς παίζεται",
  "round.howTo1": "Ξέρεις τη λέξη; Δώσε έξυπνες υποδείξεις χωρίς να την αποκαλύψεις.",
  "round.howTo2": "Είσαι ο Imposter; Μπέρδεψου και μάντεψε από τις υποδείξεις.",
  "round.howTo3": "Όταν είστε έτοιμοι, παύση και ψηφίστε.",
  "drawing.starting": "Ο/Η {name} ξεκινά", "drawing.instruction": "Σχεδίασε την υπόδειξη με μία γραμμή και πέρασε",
  "drawing.exitTitle": "Έξοδος από το παιχνίδι;", "drawing.exitBody": "Θέλεις σίγουρα να φύγεις;", "drawing.exitConfirm": "Έξοδος",
  "vote.title": "Ποιος είναι ο Imposter;", "vote.instruction": "Ψήφισε όποιον νομίζεις ότι προσποιείται",
  "vote.ready": "Έτοιμοι; Στείλτε τις ψήφους!", "vote.send": "ΑΠΟΣΤΟΛΗ ΨΗΦΩΝ",
  "results.title": "Αποτελέσματα", "results.imposterWins": "Κερδίζει ο Imposter!",
  "results.imposterWinsBody": "Ο impostor ξέφυγε απαρατήρητος", "results.crewWins": "Κερδίζει η ομάδα!",
  "results.crewWinsBody": "Βρήκατε τον impostor!", "results.imposterGuessed": "Κερδίζει ο Imposter!",
  "results.imposterGuessedBody": "Ο impostor μάντεψε τη μυστική λέξη", "results.secretWord": "Μυστική λέξη",
  "results.playAgain": "ΠΑΙΞΕ ΞΑΝΑ", "results.momentOfTruth": "ΣΤΙΓΜΗ ΑΛΗΘΕΙΑΣ",
  "rate.title": "Βαθμολόγησε το Imposter Party!", "rate.body": "Βάλαμε την καρδιά μας σε αυτό το παιχνίδι.",
  "rate.incentive": "Η κριτική σου μας βοηθά — 5 αστέρια", "rate.cta": "Βαθμολόγησε",
  "support.title": "Βελτίωσε την υποστήριξη", "support.body": "Περιορισμένα δεδομένα χρήσης μπορεί να κοινοποιηθούν στην Apple για καλύτερη υποστήριξη και αγορές.",
}

RO = {
  "meta.languageName": "Română", "meta.locale": "ro",
  "common.continue": "Continuă", "common.next": "Următorul", "common.back": "Înapoi",
  "common.close": "Închide", "common.cancel": "Anulează", "common.gotIt": "Am înțeles!",
  "common.play": "JOACĂ", "common.skip": "Omite", "common.settings": "Setări",
  "common.info": "Info", "common.accept": "Acceptă", "common.decline": "Refuză",
  "common.on": "Pornit", "common.off": "Oprit", "common.restore": "Restaurează",
  "common.terms": "Termeni", "common.privacy": "Confidențialitate",
  "onboarding.1.title": "Distracție instantanee oriunde!",
  "onboarding.1.body": "Seară de jocuri, drum sau o întâlnire ciudată — Imposter Party sparge gheața.",
  "onboarding.1.cta": "Sunt în!",
  "onboarding.2.title": "Cine se preface?",
  "onboarding.2.body": "Unul minte. Restul știu cuvântul. Găsiți impostorul la timp?",
  "onboarding.2.cta": "Am înțeles",
  "onboarding.3.title": "Vorbește inteligent. Ghicește bine.",
  "onboarding.3.body": "Descrie cuvântul secret fără să-l spui. Atenție — impostorul ascultă.",
  "onboarding.3.cta": "Să jucăm!",
  "tutorial.1.title": "Alege teme", "tutorial.1.body": "Alege una sau mai multe teme potrivite petrecerii.",
  "tutorial.2.title": "Verifică rolul", "tutorial.2.body": "Toți văd cuvântul… în afară de impostor. Scopul lui: să se amestece.",
  "tutorial.3.title": "Dă un indiciu", "tutorial.3.body": "Un indiciu inteligent: clar pentru cei care știu — confuz pentru impostor.",
  "tutorial.4.title": "Timp de vot", "tutorial.4.body": "Discuția s-a terminat. Votați ca să demascați impostorul!",
  "tutorial.4.win": "Corect — ați câștigat", "tutorial.4.lose": "Greșit — câștigă Impostorul",
  "tutorial.4.warning": "Dacă impostorul ghicește cuvântul la timp, câștigă imediat",
  "paywall.title": "Continuă pentru acces complet", "paywall.freeTrial": "Nu ești sigur? Încearcă gratis",
  "paywall.yearly": "Anual", "paywall.weekly": "Săptămânal", "paywall.bestDeal": "Cea mai bună ofertă",
  "paywall.mostPopular": "Cel mai popular", "paywall.cancelAnytime": "Anulează oricând",
  "paywall.tryFree": "Încearcă gratis", "paywall.continue": "Continuă",
  "home.classicTitle": "Imposter clasic", "home.classicSubtitle": "Descrie cuvântul fără să fii prins!",
  "home.drawingTitle": "Mod desen", "home.drawingSubtitle": "Fără cuvinte — doar desenul tău!",
  "settings.title": "Setări", "settings.language": "Limbă", "settings.contact": "Contactează-ne",
  "settings.privacy": "Confidențialitate", "settings.terms": "Termeni de utilizare",
  "settings.vibration": "Vibrație", "settings.userId": "ID utilizator: {id}",
  "players.title": "Adaugă jucători", "players.placeholder": "Numele jucătorului {n}",
  "players.add": "Adaugă jucător", "players.minHint": "Minim 3 jucători", "players.maxHint": "Maxim 15 jucători",
  "categories.title": "Categorii", "categories.selected": "{n} categorii",
  "categories.party": "Petrecere", "categories.partyDesc": "Râsete, haos și distracție pentru orice grup.",
  "categories.football": "Fotbal", "categories.footballDesc": "Goluri, legende și ghete de aur — fii fan!",
  "categories.food": "Mâncare", "categories.foodDesc": "Subiecte gustoase — greșești și ești prăjit!",
  "categories.celebs": "Vedete", "categories.celebsDesc": "Nume din film și muzică. Discuții ușoare!",
  "categories.hobbies": "Hobby-uri", "categories.hobbiesDesc": "Pasiuni secrete — inventează sau fii demascat!",
  "categories.family": "Familie", "categories.familyDesc": "Familia te cunoaște — prind bluff-ul?",
  "categories.education": "Școală", "categories.educationDesc": "Examene și ore — bluffează ca și cum ai învățat!",
  "categories.nature": "Natură", "categories.natureDesc": "Copaci, oceane și natură sălbatică — pretinde că știi.",
  "categories.characters": "Personaje", "categories.charactersDesc": "Eroi și răufăcători — pretinde că îi cunoști.",
  "categories.jobs": "Meserii", "categories.jobsDesc": "De la chirurg la streamer — imită sau ești prins!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Filme și momente iconice — rămâi pe scenă.",
  "categories.brands": "Branduri", "categories.brandsDesc": "Nume celebre și obiecte — găsește sau fake!",
  "categories.places": "Locuri", "categories.placesDesc": "Țări și orașe — ca și cum ai fost acolo!",
  "categories.animals": "Animale", "categories.animalsDesc": "De la animale de companie la sălbăticiuni — te poți amesteca?",
  "categories.sports": "Sport", "categories.sportsDesc": "Fan sau impostor — să nu se vadă.",
  "categories.newyear": "Anul Nou", "categories.newyearDesc": "Atmosferă de iarnă — cine e obraznic?",
  "gameSettings.title": "Setări joc", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Unele runde răstoarnă regulile. Așteaptă neașteptatul!",
  "gameSettings.imposters": "Impostori", "gameSettings.impostersDesc": "Câți impostori secreți? Pentru {n} jucători: {rec}",
  "gameSettings.roundDuration": "Durata rundei", "gameSettings.roundDurationDesc": "Cât durează discuția?",
  "gameSettings.imposterHints": "Indicii pentru impostori", "gameSettings.imposterHintsDesc": "Impostorii să primească un indiciu?",
  "gameSettings.playSummary": "{n} impostor(i)",
  "pass.givePhone": "Dă telefonul lui {name}", "pass.swipeHint": "Glisează în sus pentru cuvântul secret",
  "pass.imposter": "IMPOSTOR", "pass.hint": "Indiciu: {hint}",
  "pass.readyTitle": "Suntem gata!", "pass.startGame": "Începe jocul",
  "round.startAsking": "Începe să întrebi!", "round.pause": "Pauză", "round.resume": "Continuă",
  "round.paused": "În pauză", "round.tapToContinue": "Atinge pentru a continua", "round.vote": "Votează",
  "round.howToTitle": "Cum se joacă",
  "round.howTo1": "Știi cuvântul? Dă indicii inteligente fără să-l dezvălui.",
  "round.howTo2": "Ești Impostorul? Amestecă-te și ghicește din indicii altora.",
  "round.howTo3": "Când sunteți gata, pauză și votați.",
  "drawing.starting": "{name} începe", "drawing.instruction": "Desenează indiciul dintr-o singură linie, apoi pasează",
  "drawing.exitTitle": "Ieși din joc?", "drawing.exitBody": "Sigur vrei să ieși?", "drawing.exitConfirm": "Ieși",
  "vote.title": "Cine este Impostorul?", "vote.instruction": "Votează pe cine crezi că se preface",
  "vote.ready": "Gata? Trimiteți voturile!", "vote.send": "TRIMITE VOTURI",
  "results.title": "Rezultate", "results.imposterWins": "Impostorul câștigă!",
  "results.imposterWinsBody": "Impostorul a scăpat neobservat", "results.crewWins": "Echipa câștigă!",
  "results.crewWinsBody": "Ați găsit impostorul!", "results.imposterGuessed": "Impostorul câștigă!",
  "results.imposterGuessedBody": "Impostorul a ghicit cuvântul secret", "results.secretWord": "Cuvânt secret",
  "results.playAgain": "JOACĂ DIN NOU", "results.momentOfTruth": "MOMENTUL ADEVĂRULUI",
  "rate.title": "Evaluează Imposter Party!", "rate.body": "Am pus tot sufletul în acest joc.",
  "rate.incentive": "Recenzia ta ne ajută — 5 stele", "rate.cta": "Evaluează-ne",
  "support.title": "Îmbunătățește suportul", "support.body": "Date limitate de utilizare pot fi partajate cu Apple pentru a îmbunătăți suportul și achizițiile.",
}

NL = {
  "meta.languageName": "Nederlands", "meta.locale": "nl",
  "common.continue": "Doorgaan", "common.next": "Volgende", "common.back": "Terug",
  "common.close": "Sluiten", "common.cancel": "Annuleren", "common.gotIt": "Begrepen!",
  "common.play": "SPELEN", "common.skip": "Overslaan", "common.settings": "Instellingen",
  "common.info": "Info", "common.accept": "Accepteren", "common.decline": "Weigeren",
  "common.on": "Aan", "common.off": "Uit", "common.restore": "Herstellen",
  "common.terms": "Voorwaarden", "common.privacy": "Privacy",
  "onboarding.1.title": "Direct plezier overal!",
  "onboarding.1.body": "Spelavond, roadtrip of rare eerste date — Imposter Party breekt het ijs.",
  "onboarding.1.cta": "Ik doe mee!",
  "onboarding.2.title": "Wie doet alsof?",
  "onboarding.2.body": "Eén liegt. De rest kent het woord. Vinden jullie de imposter op tijd?",
  "onboarding.2.cta": "Begrepen",
  "onboarding.3.title": "Praat slim. Raad goed.",
  "onboarding.3.body": "Beschrijf het geheime woord zonder het te zeggen. Let op — de imposter luistert.",
  "onboarding.3.cta": "Laten we spelen!",
  "tutorial.1.title": "Kies thema’s", "tutorial.1.body": "Kies een of meer thema’s die bij het feest passen.",
  "tutorial.2.title": "Check je rol", "tutorial.2.body": "Iedereen ziet het woord… behalve de imposter. Doel: opgaan in de groep.",
  "tutorial.3.title": "Geef een hint", "tutorial.3.body": "Een slimme hint: duidelijk voor wie het weet — verwarrend voor de imposter.",
  "tutorial.4.title": "Tijd om te stemmen", "tutorial.4.body": "Gepraat klaar. Stem om de imposter te ontmaskeren!",
  "tutorial.4.win": "Goed — jullie winnen", "tutorial.4.lose": "Mis — de Imposter wint",
  "tutorial.4.warning": "Raadt de imposter het woord op tijd, wint die meteen",
  "paywall.title": "Ga door voor volledige toegang", "paywall.freeTrial": "Nog twijfels? Probeer gratis",
  "paywall.yearly": "Jaarlijks", "paywall.weekly": "Wekelijks", "paywall.bestDeal": "Beste deal",
  "paywall.mostPopular": "Meest populair", "paywall.cancelAnytime": "Altijd opzegbaar",
  "paywall.tryFree": "Gratis proberen", "paywall.continue": "Doorgaan",
  "home.classicTitle": "Klassieke Imposter", "home.classicSubtitle": "Beschrijf het woord zonder gepakt te worden!",
  "home.drawingTitle": "Tekenmodus", "home.drawingSubtitle": "Geen woorden — alleen je tekenkunst!",
  "settings.title": "Instellingen", "settings.language": "Taal", "settings.contact": "Contact",
  "settings.privacy": "Privacy", "settings.terms": "Gebruiksvoorwaarden",
  "settings.vibration": "Trilling", "settings.userId": "Gebruikers-ID: {id}",
  "players.title": "Spelers toevoegen", "players.placeholder": "Naam van speler {n}",
  "players.add": "Speler toevoegen", "players.minHint": "Minimaal 3 spelers", "players.maxHint": "Maximaal 15 spelers",
  "categories.title": "Categorieën", "categories.selected": "{n} categorie(ën)",
  "categories.party": "Feest", "categories.partyDesc": "Lachen, chaos en plezier voor elke groep.",
  "categories.football": "Voetbal", "categories.footballDesc": "Goals, legendes en gouden schoenen — wees fan!",
  "categories.food": "Eten", "categories.foodDesc": "Lekkere onderwerpen — zeg iets fout en je bent toast!",
  "categories.celebs": "Bekenden", "categories.celebsDesc": "Namen uit film en muziek. Smalltalk!",
  "categories.hobbies": "Hobby’s", "categories.hobbiesDesc": "Passies — verzin of word ontmaskerd!",
  "categories.family": "Familie", "categories.familyDesc": "Familie kent je — prikken ze door de bluf?",
  "categories.education": "School", "categories.educationDesc": "Toetsen en lessen — bluf alsof je huiswerk deed!",
  "categories.nature": "Natuur", "categories.natureDesc": "Bomen, oceanen en wildlife — doe alsof je het weet.",
  "categories.characters": "Personages", "categories.charactersDesc": "Helden en schurken — doe alsof je ze kent.",
  "categories.jobs": "Beroepen", "categories.jobsDesc": "Van chirurg tot streamer — imiteer of word gepakt!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Films en iconische momenten — blijf op het podium.",
  "categories.brands": "Merken", "categories.brandsDesc": "Bekende namen en spullen — vind of fake!",
  "categories.places": "Plaatsen", "categories.placesDesc": "Landen en steden — alsof je er bent geweest!",
  "categories.animals": "Dieren", "categories.animalsDesc": "Van huisdieren tot roofdieren — kun je opgaan?",
  "categories.sports": "Sport", "categories.sportsDesc": "Fan of faker — laat het niet merken.",
  "categories.newyear": "Nieuwjaar", "categories.newyearDesc": "Wintersfeer — wie is stout of lief?",
  "gameSettings.title": "Spelinstellingen", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Sommige rondes draaien de regels om. Verwacht het onverwachte!",
  "gameSettings.imposters": "Imposters", "gameSettings.impostersDesc": "Hoeveel geheime imposters? Voor {n} spelers: {rec}",
  "gameSettings.roundDuration": "Rondeduur", "gameSettings.roundDurationDesc": "Hoe lang duurt de discussie?",
  "gameSettings.imposterHints": "Hints voor imposters", "gameSettings.imposterHintsDesc": "Krijgen imposters een hint over het woord?",
  "gameSettings.playSummary": "{n} imposter(s)",
  "pass.givePhone": "Geef de telefoon aan {name}", "pass.swipeHint": "Veeg omhoog om het geheime woord te zien",
  "pass.imposter": "IMPOSTER", "pass.hint": "Hint: {hint}",
  "pass.readyTitle": "Klaar om te starten!", "pass.startGame": "Start het spel",
  "round.startAsking": "Begin met vragen!", "round.pause": "Pauze", "round.resume": "Hervatten",
  "round.paused": "Gepauzeerd", "round.tapToContinue": "Tik om door te gaan", "round.vote": "Stem",
  "round.howToTitle": "Hoe speel je",
  "round.howTo1": "Ken je het woord? Geef slimme hints zonder het te verklappen.",
  "round.howTo2": "Ben jij de Imposter? Meng je en raad via andermans hints.",
  "round.howTo3": "Klaar? Pauzeer en stem op de imposter.",
  "drawing.starting": "{name} begint", "drawing.instruction": "Teken de hint in één streep, geef dan door",
  "drawing.exitTitle": "Spel verlaten?", "drawing.exitBody": "Weet je zeker dat je wilt stoppen?", "drawing.exitConfirm": "Verlaten",
  "vote.title": "Wie is de Imposter?", "vote.instruction": "Stem op wie jij denkt dat bluft",
  "vote.ready": "Klaar? Stuur de stemmen!", "vote.send": "STEMMEN VERSTUREN",
  "results.title": "Resultaten", "results.imposterWins": "Imposter wint!",
  "results.imposterWinsBody": "De imposter ontsnapte ongezien", "results.crewWins": "Team wint!",
  "results.crewWinsBody": "Jullie vonden de imposter!", "results.imposterGuessed": "Imposter wint!",
  "results.imposterGuessedBody": "De imposter raadde het geheime woord", "results.secretWord": "Geheim woord",
  "results.playAgain": "OPNIEUW SPELEN", "results.momentOfTruth": "MOMENT VAN DE WAARHEID",
  "rate.title": "Beoordeel Imposter Party!", "rate.body": "We stoppen ons hart in dit spel.",
  "rate.incentive": "Jouw review helpt ons — 5 sterren", "rate.cta": "Beoordeel ons",
  "support.title": "Verbeter je support", "support.body": "Beperkte gebruiksgegevens kunnen met Apple worden gedeeld om support en aankopen te verbeteren.",
}

PL = {
  "meta.languageName": "Polski", "meta.locale": "pl",
  "common.continue": "Kontynuuj", "common.next": "Dalej", "common.back": "Wstecz",
  "common.close": "Zamknij", "common.cancel": "Anuluj", "common.gotIt": "Rozumiem!",
  "common.play": "GRAJ", "common.skip": "Pomiń", "common.settings": "Ustawienia",
  "common.info": "Info", "common.accept": "Akceptuj", "common.decline": "Odrzuć",
  "common.on": "Wł.", "common.off": "Wył.", "common.restore": "Przywróć",
  "common.terms": "Warunki", "common.privacy": "Prywatność",
  "onboarding.1.title": "Natychmiastowa zabawa wszędzie!",
  "onboarding.1.body": "Wieczór gier, podróż lub dziwna pierwsza randka — Imposter Party przełamuje lody.",
  "onboarding.1.cta": "Jestem w grze!",
  "onboarding.2.title": "Kto ściemnia?",
  "onboarding.2.body": "Jeden kłamie. Reszta zna słowo. Zdążycie znaleźć impostora?",
  "onboarding.2.cta": "Rozumiem",
  "onboarding.3.title": "Mów mądrze. Zgaduj dobrze.",
  "onboarding.3.body": "Opisz tajne słowo, nie wypowiadając go. Uwaga — impostor słucha.",
  "onboarding.3.cta": "Grajmy!",
  "tutorial.1.title": "Wybierz tematy", "tutorial.1.body": "Wybierz jeden lub więcej tematów na imprezę.",
  "tutorial.2.title": "Sprawdź rolę", "tutorial.2.body": "Wszyscy widzą słowo… poza impostorem. Cel: wtopić się.",
  "tutorial.3.title": "Daj wskazówkę", "tutorial.3.body": "Sprytna wskazówka: jasna dla tych, którzy wiedzą — myląca dla impostora.",
  "tutorial.4.title": "Czas głosować", "tutorial.4.body": "Koniec rozmowy. Głosujcie, by demaskować impostora!",
  "tutorial.4.win": "Trafione — wygrywacie", "tutorial.4.lose": "Pudło — wygrywa Impostor",
  "tutorial.4.warning": "Jeśli impostor zgadnie słowo na czas, wygrywa od razu",
  "paywall.title": "Kontynuuj, by uzyskać pełny dostęp", "paywall.freeTrial": "Nie jesteś pewien? Wypróbuj za darmo",
  "paywall.yearly": "Rocznie", "paywall.weekly": "Tygodniowo", "paywall.bestDeal": "Najlepsza oferta",
  "paywall.mostPopular": "Najpopularniejsze", "paywall.cancelAnytime": "Anuluj kiedy chcesz",
  "paywall.tryFree": "Wypróbuj za darmo", "paywall.continue": "Kontynuuj",
  "home.classicTitle": "Klasyczny Imposter", "home.classicSubtitle": "Opisz słowo, nie dając się złapać!",
  "home.drawingTitle": "Tryb rysowania", "home.drawingSubtitle": "Bez słów — tylko rysunek!",
  "settings.title": "Ustawienia", "settings.language": "Język", "settings.contact": "Kontakt",
  "settings.privacy": "Prywatność", "settings.terms": "Warunki użytkowania",
  "settings.vibration": "Wibracje", "settings.userId": "ID użytkownika: {id}",
  "players.title": "Dodaj graczy", "players.placeholder": "Imię gracza {n}",
  "players.add": "Dodaj gracza", "players.minHint": "Minimum 3 graczy", "players.maxHint": "Maksimum 15 graczy",
  "categories.title": "Kategorie", "categories.selected": "{n} kategori(e/i)",
  "categories.party": "Impreza", "categories.partyDesc": "Śmiech, chaos i zabawa dla każdej grupy.",
  "categories.football": "Piłka nożna", "categories.footballDesc": "Gole, legendy i złote buty — bądź fanem!",
  "categories.food": "Jedzenie", "categories.foodDesc": "Smaczne tematy — pomyl się i jesteś spalone!",
  "categories.celebs": "Celebryci", "categories.celebsDesc": "Imiona z filmu i muzyki. Luźna rozmowa!",
  "categories.hobbies": "Hobby", "categories.hobbiesDesc": "Pasje i sekrety — zmyśl lub zostań zdemaskowany!",
  "categories.family": "Rodzina", "categories.familyDesc": "Rodzina cię zna — czy złapie blef?",
  "categories.education": "Szkoła", "categories.educationDesc": "Egzaminy i lekcje — blefuj jakbyś odrobił zadanie!",
  "categories.nature": "Natura", "categories.natureDesc": "Drzewa, oceany i dzika przyroda — udawaj eksperta.",
  "categories.characters": "Postacie", "categories.charactersDesc": "Bohaterowie i złoczyńcy — udawaj, że ich znasz.",
  "categories.jobs": "Zawody", "categories.jobsDesc": "Od chirurga do streamera — naśladuj albo wpadniesz!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Filmy i kultowe momenty — zostań na scenie.",
  "categories.brands": "Marki", "categories.brandsDesc": "Słynne nazwy i przedmioty — znajdź lub udawaj!",
  "categories.places": "Miejsca", "categories.placesDesc": "Kraje i miasta — jakbyś tam był!",
  "categories.animals": "Zwierzęta", "categories.animalsDesc": "Od pupili po dzikie bestie — dasz radę się wtopić?",
  "categories.sports": "Sport", "categories.sportsDesc": "Fan czy fałszerz — nie daj po sobie poznać.",
  "categories.newyear": "Nowy Rok", "categories.newyearDesc": "Zimowa atmosfera — kto grzeczny, kto nie?",
  "gameSettings.title": "Ustawienia gry", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Niektóre rundy odwrócą zasady. Spodziewaj się niespodzianek!",
  "gameSettings.imposters": "Impostorzy", "gameSettings.impostersDesc": "Ilu tajnych impostorów? Dla {n} graczy: {rec}",
  "gameSettings.roundDuration": "Czas rundy", "gameSettings.roundDurationDesc": "Jak długo trwa dyskusja?",
  "gameSettings.imposterHints": "Wskazówki dla impostorów", "gameSettings.imposterHintsDesc": "Czy impostorzy mają dostać wskazówkę o słowie?",
  "gameSettings.playSummary": "{n} impostor(ów)",
  "pass.givePhone": "Podaj telefon {name}", "pass.swipeHint": "Przesuń w górę, by zobaczyć tajne słowo",
  "pass.imposter": "IMPOSTOR", "pass.hint": "Wskazówka: {hint}",
  "pass.readyTitle": "Gotowi do startu!", "pass.startGame": "Rozpocznij grę",
  "round.startAsking": "Zaczynaj pytać!", "round.pause": "Pauza", "round.resume": "Wznów",
  "round.paused": "Wstrzymano", "round.tapToContinue": "Dotknij, by kontynuować", "round.vote": "Głosuj",
  "round.howToTitle": "Jak grać",
  "round.howTo1": "Znasz słowo? Dawaj sprytne wskazówki, ale go nie zdradzaj.",
  "round.howTo2": "Jesteś Impostorem? Wtapiaj się i zgaduj ze wskazówek innych.",
  "round.howTo3": "Gdy będziecie gotowi — pauza i głosowanie.",
  "drawing.starting": "{name} zaczyna", "drawing.instruction": "Narysuj wskazówkę jednym ruchem, potem podaj dalej",
  "drawing.exitTitle": "Wyjść z gry?", "drawing.exitBody": "Na pewno chcesz wyjść?", "drawing.exitConfirm": "Wyjdź",
  "vote.title": "Kto jest Impostorem?", "vote.instruction": "Zagłosuj na tego, kto Twoim zdaniem ściemnia",
  "vote.ready": "Gotowi? Wyślijcie głosy!", "vote.send": "WYŚLIJ GŁOSY",
  "results.title": "Wyniki", "results.imposterWins": "Impostor wygrywa!",
  "results.imposterWinsBody": "Impostor uciekł niezauważony", "results.crewWins": "Drużyna wygrywa!",
  "results.crewWinsBody": "Znaleźliście impostora!", "results.imposterGuessed": "Impostor wygrywa!",
  "results.imposterGuessedBody": "Impostor odgadł tajne słowo", "results.secretWord": "Tajne słowo",
  "results.playAgain": "GRAJ PONOWNIE", "results.momentOfTruth": "MOMENT PRAWDY",
  "rate.title": "Oceń Imposter Party!", "rate.body": "Wkładamy w tę grę całe serce.",
  "rate.incentive": "Twoja recenzja nam pomaga — 5 gwiazdek", "rate.cta": "Oceń nas",
  "support.title": "Ulepsz wsparcie", "support.body": "Ograniczone dane użycia mogą być udostępniane Apple w celu poprawy wsparcia i zakupów.",
}

for code, over in [("de", DE), ("fr", FR), ("it", IT), ("el", EL), ("ro", RO), ("nl", NL), ("pl", PL)]:
    write(code, over)

# locale README
readme = """# Localization

**Default:** `en` (English)

**Supported (12):** en, tr, ru, es, pt, de, fr, it, el, ro, nl, pl

## Resolution order
1. Manual language override (Settings → Language), if set
2. Device language / region if in supported list
3. Fallback → `en`

## Placeholders
- `{n}` — number
- `{name}` — player name
- `{id}` — user id
- `{hint}` — imposter hint
- `{rec}` — recommended imposters

## Files
Flat JSON key → string maps. Same keys in every locale.
"""
(OUT / "README.md").write_text(readme, encoding="utf-8")
print("wrote README.md")
print("done")
