#!/usr/bin/env python3
"""Generate Imposter Party localization JSON files (12 languages)."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent

# locale code -> translations dict (flat keys). en is source; others override.
# Missing keys fall back to English when merging.

EN = {
  "meta.languageName": "English",
  "meta.locale": "en",

  "app.name": "Imposter Party",

  "common.continue": "Continue",
  "common.next": "Next",
  "common.back": "Back",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.gotIt": "Got it!",
  "common.play": "PLAY",
  "common.skip": "Skip",
  "common.settings": "Settings",
  "common.info": "Info",
  "common.accept": "Accept",
  "common.decline": "Decline",
  "common.on": "On",
  "common.off": "Off",
  "common.restore": "Restore",
  "common.terms": "Terms",
  "common.privacy": "Privacy",

  "onboarding.1.title": "Instant fun everywhere!",
  "onboarding.1.body": "Game night, road trip, even a weird first date — Imposter Party breaks the ice and starts the fun.",
  "onboarding.1.cta": "I'm in!",
  "onboarding.2.title": "Who's faking it?",
  "onboarding.2.body": "One of you is lying. The rest know the word. Can you find the imposter before it's too late?",
  "onboarding.2.cta": "Got it",
  "onboarding.3.title": "Speak smart. Guess well.",
  "onboarding.3.body": "Describe the secret word without saying it. Careful — the imposter is listening and trying to blend in.",
  "onboarding.3.cta": "Let's play!",

  "tutorial.1.title": "Pick themes",
  "tutorial.1.body": "Choose one or more themes that fit the mood and your party.",
  "tutorial.2.title": "Check your role",
  "tutorial.2.body": "Everyone sees the secret word… except the imposter — they only see their role. Their goal? Blend in.",
  "tutorial.3.title": "Give a hint",
  "tutorial.3.body": "Give a clever hint or association. Clear for those who know — confusing for the imposter.",
  "tutorial.4.title": "Time to vote",
  "tutorial.4.body": "Talking is over. Vote to expose the imposter!",
  "tutorial.4.win": "You guessed right — you win",
  "tutorial.4.lose": "You missed — the Imposter wins",
  "tutorial.4.warning": "If the imposter guesses the word before time runs out, they win instantly",

  "paywall.title": "Continue for full access",
  "paywall.freeTrial": "Not sure yet? Try for free",
  "paywall.yearly": "Yearly",
  "paywall.weekly": "Weekly",
  "paywall.bestDeal": "Best deal",
  "paywall.mostPopular": "Most popular",
  "paywall.cancelAnytime": "Cancel anytime",
  "paywall.tryFree": "Try for free",
  "paywall.continue": "Continue",

  "home.classicTitle": "Classic Imposter",
  "home.classicSubtitle": "Describe the word without getting caught!",
  "home.drawingTitle": "Drawing mode",
  "home.drawingSubtitle": "No words — just your drawing skills!",

  "settings.title": "Settings",
  "settings.language": "Language",
  "settings.contact": "Contact us",
  "settings.privacy": "Privacy",
  "settings.terms": "Terms of use",
  "settings.vibration": "Vibration",
  "settings.userId": "User ID: {id}",

  "players.title": "Add players",
  "players.placeholder": "Enter player {n}'s name",
  "players.add": "Add player",
  "players.minHint": "At least 3 players to start",
  "players.maxHint": "Maximum 15 players",

  "categories.title": "Categories",
  "categories.selected": "{n} categor(y/ies)",
  "categories.party": "Party time",
  "categories.partyDesc": "Chill fun, laughs, and a bit of chaos — perfect for every group.",
  "categories.football": "Football",
  "categories.footballDesc": "Goals, legends, and golden boots — play the fan or get a red card!",
  "categories.food": "Food",
  "categories.foodDesc": "Tasty topics — say the wrong thing and you're toast!",
  "categories.celebs": "Celebrities",
  "categories.celebsDesc": "Famous names from film, music and more. Keep it casual!",
  "categories.hobbies": "Hobbies",
  "categories.hobbiesDesc": "Passions and secret pleasures — invent the hobby or get exposed!",
  "categories.family": "Family",
  "categories.familyDesc": "Family knows you best — but can they still catch your bluff?",
  "categories.education": "Education",
  "categories.educationDesc": "Exams, classes, school life — bluff like you did the homework!",
  "categories.nature": "Nature",
  "categories.natureDesc": "Trees, oceans, weather and wildlife — act like you know nature.",
  "categories.characters": "Characters",
  "categories.charactersDesc": "Heroes, villains and legends — pretend you know the character.",
  "categories.jobs": "Jobs",
  "categories.jobsDesc": "From surgeon to streamer — mimic the job or get caught!",
  "categories.hollywood": "Hollywood",
  "categories.hollywoodDesc": "Movies, actors and iconic moments — bluff to stay on stage.",
  "categories.brands": "Brands",
  "categories.brandsDesc": "Famous names and everyday items — find them or fake it!",
  "categories.places": "Places",
  "categories.placesDesc": "Countries, landmarks, cities — act like you've been there!",
  "categories.animals": "Animals",
  "categories.animalsDesc": "From pets to wild beasts — can you blend in?",
  "categories.sports": "Sports",
  "categories.sportsDesc": "Fan or faker — don't let it show.",
  "categories.newyear": "New Year",
  "categories.newyearDesc": "Winter fun and celebration vibes — who is naughty or nice?",

  "gameSettings.title": "Game settings",
  "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Some rounds will flip the rules. Expect the unexpected!",
  "gameSettings.imposters": "Imposters",
  "gameSettings.impostersDesc": "How many secret imposters? Recommended for {n} players: {rec}",
  "gameSettings.roundDuration": "Round duration",
  "gameSettings.roundDurationDesc": "How long should each discussion round last?",
  "gameSettings.imposterHints": "Hints for imposters",
  "gameSettings.imposterHintsDesc": "Should imposters get a hint about the secret word?",
  "gameSettings.playSummary": "{n} imposter(s)",

  "pass.givePhone": "Give the phone to {name}",
  "pass.swipeHint": "Swipe up to see the secret word",
  "pass.imposter": "IMPOSTER",
  "pass.hint": "Hint: {hint}",
  "pass.readyTitle": "We're ready to start!",
  "pass.startGame": "Start the game",

  "round.startAsking": "Start asking!",
  "round.pause": "Pause",
  "round.resume": "Resume",
  "round.paused": "Paused",
  "round.tapToContinue": "Tap to continue",
  "round.vote": "Vote",
  "round.howToTitle": "How to play",
  "round.howTo1": "Know the word? Give clever hints, help your team — but don't reveal it.",
  "round.howTo2": "Are you the Imposter? Blend in, stay calm, and guess the secret from others' hints.",
  "round.howTo3": "When ready, pause and vote to find the imposter.",

  "drawing.starting": "{name} is starting",
  "drawing.instruction": "Draw the hint in a single stroke, then pass to the next player",
  "drawing.exitTitle": "Exit game?",
  "drawing.exitBody": "Are you sure you want to leave the current game?",
  "drawing.exitConfirm": "Exit",

  "vote.title": "Who is the Imposter?",
  "vote.instruction": "Vote for whoever you think is faking it",
  "vote.ready": "When you're ready, send your votes!",
  "vote.send": "SEND VOTES",

  "results.title": "Results",
  "results.imposterWins": "Imposter wins!",
  "results.imposterWinsBody": "The imposter escaped unnoticed",
  "results.crewWins": "Crew wins!",
  "results.crewWinsBody": "You found the imposter!",
  "results.imposterGuessed": "Imposter wins!",
  "results.imposterGuessedBody": "The imposter guessed the secret word",
  "results.secretWord": "Secret word",
  "results.playAgain": "PLAY AGAIN",
  "results.momentOfTruth": "MOMENT OF TRUTH",

  "rate.title": "Rate Imposter Party!",
  "rate.body": "We're friends who poured our hearts into this game.",
  "rate.incentive": "Your review helps us grow — give 5 stars",
  "rate.cta": "Rate us",

  "support.title": "Improve your support experience",
  "support.body": "Limited app usage data may be shared with Apple to improve support and help with purchases.",
}

# Translations: only values that differ from EN structure - full dicts for each lang
TR = {
  "meta.languageName": "Türkçe",
  "meta.locale": "tr",
  "common.continue": "Devam",
  "common.next": "İleri",
  "common.back": "Geri",
  "common.close": "Kapat",
  "common.cancel": "İptal",
  "common.gotIt": "Anladım!",
  "common.play": "OYNA",
  "common.skip": "Atla",
  "common.settings": "Ayarlar",
  "common.info": "Bilgi",
  "common.accept": "Kabul et",
  "common.decline": "Reddet",
  "common.on": "Açık",
  "common.off": "Kapalı",
  "common.restore": "Geri yükle",
  "common.terms": "Koşullar",
  "common.privacy": "Gizlilik",
  "onboarding.1.title": "Anında eğlence her yerde!",
  "onboarding.1.body": "Oyun gecesi, yolculuk, hatta garip bir ilk buluşmada bile — Imposter Party buzları eritir ve eğlenceyi başlatır.",
  "onboarding.1.cta": "Ben de varım!",
  "onboarding.2.title": "Kim numara yapıyor?",
  "onboarding.2.body": "Biriniz yalan söylüyor. Gerisi kelimeyi biliyor. Çok geç olmadan impostoru bulabilecek misiniz?",
  "onboarding.2.cta": "Anladım",
  "onboarding.3.title": "Akıllıca konuş. İyi tahmin et.",
  "onboarding.3.body": "Gizli kelimeyi söylemeden tarif et. Ama dikkat — impostor dinliyor ve aranıza karışmaya çalışıyor.",
  "onboarding.3.cta": "Oynayalım!",
  "tutorial.1.title": "Temaları seç",
  "tutorial.1.body": "Havana ve partine uygun bir veya birden fazla tema seç.",
  "tutorial.2.title": "Rolünü kontrol et",
  "tutorial.2.body": "Herkes gizli kelimeyi görür… impostor hariç — o sadece rolünü görür. Amacı? Karışmak.",
  "tutorial.3.title": "İpucu ver",
  "tutorial.3.body": "Akıllıca bir ipucu ya da çağrışım ver. Bilenler için net — impostor için kafa karıştırıcı.",
  "tutorial.4.title": "Oy verme zamanı",
  "tutorial.4.body": "Konuşma bitti. Şimdi impostoru ifşa etmek için oy verin!",
  "tutorial.4.win": "Doğru bildin — kazandın",
  "tutorial.4.lose": "Kaçırdın — Impostor kazanır",
  "tutorial.4.warning": "Impostor süre dolmadan kelimeyi tahmin ederse, anında kazanır",
  "paywall.title": "Tam erişim için devam edin",
  "paywall.freeTrial": "Henüz emin değil misin? Ücretsiz dene",
  "paywall.yearly": "Yıllık",
  "paywall.weekly": "Haftalık",
  "paywall.bestDeal": "En iyi fırsat",
  "paywall.mostPopular": "En popüler",
  "paywall.cancelAnytime": "İstediğin zaman iptal et",
  "paywall.tryFree": "Ücretsiz deneyin",
  "paywall.continue": "Devam",
  "home.classicTitle": "Klasik Imposter",
  "home.classicSubtitle": "Kelimeyi yakalanmadan anlatın!",
  "home.drawingTitle": "Çizim modu",
  "home.drawingSubtitle": "Kelime yok, sadece çizim yeteneğiniz!",
  "settings.title": "Ayarlar",
  "settings.language": "Dil",
  "settings.contact": "Bize ulaş",
  "settings.privacy": "Gizlilik",
  "settings.terms": "Kullanım koşulları",
  "settings.vibration": "Titreşim",
  "settings.userId": "Kullanıcı ID: {id}",
  "players.title": "Oyuncu ekle",
  "players.placeholder": "{n}. oyuncunun adını gir",
  "players.add": "Oyuncu ekle",
  "players.minHint": "Başlamak için en az 3 oyuncu",
  "players.maxHint": "En fazla 15 oyuncu",
  "categories.title": "Kategoriler",
  "categories.selected": "{n} kategori",
  "categories.party": "Parti zamanı",
  "categories.partyDesc": "Rahat eğlence, kahkahalar ve biraz kaos — her grup için mükemmel.",
  "categories.football": "Futbol",
  "categories.footballDesc": "Goller, efsaneler ve altın krampon — fan rolü yap ya da kırmızı kart!",
  "categories.food": "Yemek",
  "categories.foodDesc": "Lezzetli konular ama yanlış bir şey söylersen yanarsın!",
  "categories.celebs": "Ünlüler",
  "categories.celebsDesc": "Film, müzik ve daha fazlasından ünlü isimler. Havadan sudan konuş!",
  "categories.hobbies": "Hobiler",
  "categories.hobbiesDesc": "Tutkular, uğraşlar ve gizli zevkler — hobiyi uydur ya da ifşa ol!",
  "categories.family": "Aile",
  "categories.familyDesc": "Aile seni en iyi tanır — ama yine de numaranı yakalayabilirler mi?",
  "categories.education": "Eğitim",
  "categories.educationDesc": "Sınavlar, dersler ve okul hayatı — ödevini yapmış gibi blöf yap!",
  "categories.nature": "Doğa",
  "categories.natureDesc": "Ağaçlar, okyanuslar, hava durumu ve vahşi yaşam — doğayı biliyormuş gibi yap.",
  "categories.characters": "Karakterler",
  "categories.charactersDesc": "Kahramanlar, kötüler ve efsaneler — karakteri tanıyormuş gibi yap.",
  "categories.jobs": "Meslekler",
  "categories.jobsDesc": "Cerrahtan yayıncıya — mesleği taklit et yoksa yakalanırsın!",
  "categories.hollywood": "Hollywood",
  "categories.hollywoodDesc": "Filmler, oyuncular ve ikonik anlar — sahnede kalmak için iyi blöf yap.",
  "categories.brands": "Markalar",
  "categories.brandsDesc": "Ünlü isimler ve günlük eşyaları bul — ya da numara yap!",
  "categories.places": "Yerler",
  "categories.placesDesc": "Ülkeler, simge yapılar, şehirler — sanki oraya gitmişsin gibi davran!",
  "categories.animals": "Hayvanlar",
  "categories.animalsDesc": "Evcil hayvanlardan vahşi canavarlara — kendini ele vermeden karışabilir misin?",
  "categories.sports": "Sporlar",
  "categories.sportsDesc": "İster hayran ol ister numara yap, belli etmemen gerekecek.",
  "categories.newyear": "Yılbaşı",
  "categories.newyearDesc": "Kış eğlencesi ve kutlama havası — kim iyi kim yaramaz?",
  "gameSettings.title": "Oyun ayarları",
  "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Bazı turlar kurallarınızı alt üst edecek. Beklenmedik olanı bekleyin!",
  "gameSettings.imposters": "Impostorlar",
  "gameSettings.impostersDesc": "Kaç oyuncu gizli impostor olsun? {n} oyuncu için önerilen: {rec}",
  "gameSettings.roundDuration": "Tur süresi",
  "gameSettings.roundDurationDesc": "Her tartışma turu ne kadar sürsün?",
  "gameSettings.imposterHints": "Impostorlar için ipuçları",
  "gameSettings.imposterHintsDesc": "Impostorlar gizli kelime hakkında ipucu almalı mı?",
  "gameSettings.playSummary": "{n} impostor",
  "pass.givePhone": "Telefonu {name} ver",
  "pass.swipeHint": "Gizli kelimeyi görmek için yukarı kaydır",
  "pass.imposter": "İMPOSTOR",
  "pass.hint": "İpucu: {hint}",
  "pass.readyTitle": "Başlamaya hazırız!",
  "pass.startGame": "Oyunu başlat",
  "round.startAsking": "Sormaya başla!",
  "round.pause": "Duraklat",
  "round.resume": "Devam et",
  "round.paused": "Duraklatıldı",
  "round.tapToContinue": "Devam etmek için dokun",
  "round.vote": "Oy ver",
  "round.howToTitle": "Nasıl oynanır",
  "round.howTo1": "Kelimeyi biliyor musun? Akıllıca ipuçları ver, takımına yardım et ama ortaya çıkarma.",
  "round.howTo2": "Impostor musun? Karış, sakin kal ve diğerlerinin ipuçlarından sırrı tahmin etmeye çalış.",
  "round.howTo3": "Hazır olduğunuzda, duraklatın ve impostoru bulmak için oy verin.",
  "drawing.starting": "{name} başlıyor",
  "drawing.instruction": "İpucunu tek çizgiyle çiz, sonra sıradaki oyuncuya devret",
  "drawing.exitTitle": "Oyundan çık?",
  "drawing.exitBody": "Mevcut oyundan çıkmak istediğinden emin misin?",
  "drawing.exitConfirm": "Çık",
  "vote.title": "Impostor kim?",
  "vote.instruction": "Kimin numara yaptığını düşünüyorsan ona oy ver",
  "vote.ready": "Hazır olduğunuzda oylarınızı gönderin!",
  "vote.send": "OYLARI GÖNDER",
  "results.title": "Sonuçlar",
  "results.imposterWins": "Impostor kazandı!",
  "results.imposterWinsBody": "Impostor fark edilmeden kaçtı",
  "results.crewWins": "Takım kazandı!",
  "results.crewWinsBody": "Impostoru buldunuz!",
  "results.imposterGuessed": "Impostor kazandı!",
  "results.imposterGuessedBody": "Impostor gizli kelimeyi tahmin etti",
  "results.secretWord": "Gizli kelime",
  "results.playAgain": "TEKRAR OYNA",
  "results.momentOfTruth": "GERÇEĞİN ANI",
  "rate.title": "Imposter Party'yi puanla!",
  "rate.body": "Bu oyuna tüm kalbimizi koyan bir ekibiz.",
  "rate.incentive": "Yorumun büyümemize yardımcı oluyor — 5 yıldızın",
  "rate.cta": "Bizi puanla",
  "support.title": "Destek deneyiminizi geliştirin",
  "support.body": "Destek ve satın alma yardımını iyileştirmek için sınırlı uygulama kullanım verisi Apple ile paylaşılabilir.",
}

# For other languages I'll embed complete overrides similarly but more compact via a generator approach
# Full professional translations for remaining languages:

RU = {
  "meta.languageName": "Русский", "meta.locale": "ru",
  "common.continue": "Продолжить", "common.next": "Далее", "common.back": "Назад",
  "common.close": "Закрыть", "common.cancel": "Отмена", "common.gotIt": "Понятно!",
  "common.play": "ИГРАТЬ", "common.skip": "Пропустить", "common.settings": "Настройки",
  "common.info": "Инфо", "common.accept": "Принять", "common.decline": "Отклонить",
  "common.on": "Вкл", "common.off": "Выкл", "common.restore": "Восстановить",
  "common.terms": "Условия", "common.privacy": "Конфиденциальность",
  "onboarding.1.title": "Мгновенное веселье везде!",
  "onboarding.1.body": "Игровой вечер, поездка или странное первое свидание — Imposter Party растопит лёд.",
  "onboarding.1.cta": "Я с вами!",
  "onboarding.2.title": "Кто притворяется?",
  "onboarding.2.body": "Один из вас врёт. Остальные знают слово. Сможете найти самозванца вовремя?",
  "onboarding.2.cta": "Понятно",
  "onboarding.3.title": "Говори умно. Угадывай точно.",
  "onboarding.3.body": "Опиши секретное слово, не называя его. Осторожно — самозванец слушает.",
  "onboarding.3.cta": "Поиграем!",
  "tutorial.1.title": "Выберите темы", "tutorial.1.body": "Выберите одну или несколько тем под настроение вечеринки.",
  "tutorial.2.title": "Проверь роль", "tutorial.2.body": "Все видят секретное слово… кроме самозванца. Его цель — смешаться.",
  "tutorial.3.title": "Дай подсказку", "tutorial.3.body": "Умная ассоциация: ясно для знающих — запутанно для самозванца.",
  "tutorial.4.title": "Время голосовать", "tutorial.4.body": "Разговор окончен. Голосуйте, чтобы раскрыть самозванца!",
  "tutorial.4.win": "Угадали — победа", "tutorial.4.lose": "Промах — побеждает самозванец",
  "tutorial.4.warning": "Если самозванец угадает слово до конца времени — мгновенная победа",
  "paywall.title": "Продолжите для полного доступа", "paywall.freeTrial": "Не уверены? Попробуйте бесплатно",
  "paywall.yearly": "Годовой", "paywall.weekly": "Недельный", "paywall.bestDeal": "Лучшая сделка",
  "paywall.mostPopular": "Самый популярный", "paywall.cancelAnytime": "Отмена в любое время",
  "paywall.tryFree": "Попробовать бесплатно", "paywall.continue": "Продолжить",
  "home.classicTitle": "Классический Imposter", "home.classicSubtitle": "Опиши слово и не попадись!",
  "home.drawingTitle": "Режим рисования", "home.drawingSubtitle": "Без слов — только твой рисунок!",
  "settings.title": "Настройки", "settings.language": "Язык", "settings.contact": "Связаться с нами",
  "settings.privacy": "Конфиденциальность", "settings.terms": "Условия использования",
  "settings.vibration": "Вибрация", "settings.userId": "ID пользователя: {id}",
  "players.title": "Добавить игроков", "players.placeholder": "Имя игрока {n}",
  "players.add": "Добавить игрока", "players.minHint": "Минимум 3 игрока", "players.maxHint": "Максимум 15 игроков",
  "categories.title": "Категории", "categories.selected": "{n} категор.",
  "categories.party": "Вечеринка", "categories.partyDesc": "Смех, хаос и лёгкое веселье для любой компании.",
  "categories.football": "Футбол", "categories.footballDesc": "Голы, легенды и золотые бутсы — будь фанатом!",
  "categories.food": "Еда", "categories.foodDesc": "Вкусные темы — ошибись, и ты поджарен!",
  "categories.celebs": "Звёзды", "categories.celebsDesc": "Имена из кино и музыки. Лёгкая беседа!",
  "categories.hobbies": "Хобби", "categories.hobbiesDesc": "Увлечения и секреты — выдумай или разоблачись!",
  "categories.family": "Семья", "categories.familyDesc": "Семья знает тебя — но поймает ли блеф?",
  "categories.education": "Учёба", "categories.educationDesc": "Экзамены и школа — блефуй, будто делал домашку!",
  "categories.nature": "Природа", "categories.natureDesc": "Деревья, океаны и дикая природа — притворись экспертом.",
  "categories.characters": "Персонажи", "categories.charactersDesc": "Герои и злодеи — притворись, что знаешь героя.",
  "categories.jobs": "Профессии", "categories.jobsDesc": "От хирурга до стримера — сыграй роль или спалишься!",
  "categories.hollywood": "Голливуд", "categories.hollywoodDesc": "Фильмы и культовые моменты — держись на сцене.",
  "categories.brands": "Бренды", "categories.brandsDesc": "Известные имена и вещи — найди или притворись!",
  "categories.places": "Места", "categories.placesDesc": "Страны и города — будто ты там был!",
  "categories.animals": "Животные", "categories.animalsDesc": "От питомцев до хищников — сможешь смешаться?",
  "categories.sports": "Спорт", "categories.sportsDesc": "Фанат или притворщик — не покажи это.",
  "categories.newyear": "Новый год", "categories.newyearDesc": "Зимнее веселье — кто хороший, кто шалун?",
  "gameSettings.title": "Настройки игры", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Некоторые раунды перевернут правила. Жди неожиданного!",
  "gameSettings.imposters": "Самозванцы", "gameSettings.impostersDesc": "Сколько самозванцев? Для {n} игроков рекомендуется: {rec}",
  "gameSettings.roundDuration": "Длительность раунда", "gameSettings.roundDurationDesc": "Сколько длится обсуждение?",
  "gameSettings.imposterHints": "Подсказки самозванцам", "gameSettings.imposterHintsDesc": "Давать самозванцам подсказку о слове?",
  "gameSettings.playSummary": "{n} самозванец(а)",
  "pass.givePhone": "Передай телефон {name}", "pass.swipeHint": "Свайп вверх, чтобы увидеть секретное слово",
  "pass.imposter": "САМОЗВАНЕЦ", "pass.hint": "Подсказка: {hint}",
  "pass.readyTitle": "Готовы начать!", "pass.startGame": "Начать игру",
  "round.startAsking": "Начинай спрашивать!", "round.pause": "Пауза", "round.resume": "Продолжить",
  "round.paused": "Пауза", "round.tapToContinue": "Нажми, чтобы продолжить", "round.vote": "Голосовать",
  "round.howToTitle": "Как играть",
  "round.howTo1": "Знаешь слово? Давай умные подсказки, но не раскрывай его.",
  "round.howTo2": "Ты самозванец? Смешайся и угадай слово по чужим подсказкам.",
  "round.howTo3": "Когда готовы — пауза и голосуйте за самозванца.",
  "drawing.starting": "{name} начинает", "drawing.instruction": "Нарисуй подсказку одним штрихом, затем передай дальше",
  "drawing.exitTitle": "Выйти из игры?", "drawing.exitBody": "Точно хочешь выйти из текущей игры?", "drawing.exitConfirm": "Выйти",
  "vote.title": "Кто самозванец?", "vote.instruction": "Голосуй за того, кто притворяется",
  "vote.ready": "Когда готовы — отправьте голоса!", "vote.send": "ОТПРАВИТЬ ГОЛОСА",
  "results.title": "Результаты", "results.imposterWins": "Самозванец победил!",
  "results.imposterWinsBody": "Самозванец ушёл незамеченным", "results.crewWins": "Команда победила!",
  "results.crewWinsBody": "Вы нашли самозванца!", "results.imposterGuessed": "Самозванец победил!",
  "results.imposterGuessedBody": "Самозванец угадал секретное слово", "results.secretWord": "Секретное слово",
  "results.playAgain": "ИГРАТЬ СНОВА", "results.momentOfTruth": "МОМЕНТ ИСТИНЫ",
  "rate.title": "Оцени Imposter Party!", "rate.body": "Мы вложили в эту игру всё сердце.",
  "rate.incentive": "Твой отзыв помогает нам расти — 5 звёзд", "rate.cta": "Оценить",
  "support.title": "Улучшите поддержку", "support.body": "Ограниченные данные об использовании могут передаваться Apple для улучшения поддержки и покупок.",
}

def merge(base, over):
  out = dict(base)
  out.update(over)
  return out

# Remaining languages - substantial translations
ES = merge(EN, {
  "meta.languageName": "Español", "meta.locale": "es",
  "common.continue": "Continuar", "common.next": "Siguiente", "common.back": "Atrás",
  "common.close": "Cerrar", "common.cancel": "Cancelar", "common.gotIt": "¡Entendido!",
  "common.play": "JUGAR", "common.skip": "Omitir", "common.settings": "Ajustes",
  "common.info": "Info", "common.accept": "Aceptar", "common.decline": "Rechazar",
  "common.on": "Sí", "common.off": "No", "common.restore": "Restaurar",
  "common.terms": "Términos", "common.privacy": "Privacidad",
  "onboarding.1.title": "¡Diversión al instante en cualquier lugar!",
  "onboarding.1.body": "Noche de juegos, viaje o una cita rara — Imposter Party rompe el hielo.",
  "onboarding.1.cta": "¡Cuento conmigo!",
  "onboarding.2.title": "¿Quién está fingiendo?",
  "onboarding.2.body": "Uno miente. Los demás saben la palabra. ¿Pillaréis al impostor a tiempo?",
  "onboarding.2.cta": "Entendido",
  "onboarding.3.title": "Habla con cabeza. Adivina bien.",
  "onboarding.3.body": "Describe la palabra secreta sin decirla. Cuidado: el impostor escucha.",
  "onboarding.3.cta": "¡Juguemos!",
  "tutorial.1.title": "Elige temas", "tutorial.1.body": "Elige uno o más temas según el ambiente de la fiesta.",
  "tutorial.2.title": "Comprueba tu rol", "tutorial.2.body": "Todos ven la palabra… excepto el impostor. Su meta: mezclarse.",
  "tutorial.3.title": "Da una pista", "tutorial.3.body": "Una pista lista: clara para quien sabe, confusa para el impostor.",
  "tutorial.4.title": "Hora de votar", "tutorial.4.body": "Se acabó hablar. ¡Votad para desenmascarar al impostor!",
  "tutorial.4.win": "Acertaste — ganáis", "tutorial.4.lose": "Fallaste — gana el Impostor",
  "tutorial.4.warning": "Si el impostor adivina la palabra a tiempo, gana al instante",
  "paywall.title": "Continúa para acceso total", "paywall.freeTrial": "¿Dudas? Prueba gratis",
  "paywall.yearly": "Anual", "paywall.weekly": "Semanal", "paywall.bestDeal": "Mejor oferta",
  "paywall.mostPopular": "Más popular", "paywall.cancelAnytime": "Cancela cuando quieras",
  "paywall.tryFree": "Probar gratis", "paywall.continue": "Continuar",
  "home.classicTitle": "Imposter clásico", "home.classicSubtitle": "¡Describe la palabra sin que te pillen!",
  "home.drawingTitle": "Modo dibujo", "home.drawingSubtitle": "¡Sin palabras, solo tu dibujo!",
  "settings.title": "Ajustes", "settings.language": "Idioma", "settings.contact": "Contacto",
  "settings.privacy": "Privacidad", "settings.terms": "Términos de uso",
  "settings.vibration": "Vibración", "settings.userId": "ID de usuario: {id}",
  "players.title": "Añadir jugadores", "players.placeholder": "Nombre del jugador {n}",
  "players.add": "Añadir jugador", "players.minHint": "Mínimo 3 jugadores", "players.maxHint": "Máximo 15 jugadores",
  "categories.title": "Categorías", "categories.selected": "{n} categoría(s)",
  "categories.party": "Fiesta", "categories.partyDesc": "Risas, caos y diversión para cualquier grupo.",
  "categories.football": "Fútbol", "categories.footballDesc": "Goles, leyendas y botas de oro — ¡sé hincha!",
  "categories.food": "Comida", "categories.foodDesc": "Temas deliciosos — ¡si fallas, estás frito!",
  "categories.celebs": "Famosos", "categories.celebsDesc": "Nombres de cine y música. ¡Charla ligera!",
  "categories.hobbies": "Hobbies", "categories.hobbiesDesc": "Pasiones secretas — ¡invéntatelo o te descubren!",
  "categories.family": "Familia", "categories.familyDesc": "La familia te conoce — ¿pillarán el farol?",
  "categories.education": "Educación", "categories.educationDesc": "Exámenes y colegio — farolea como si hubieras hecho los deberes.",
  "categories.nature": "Naturaleza", "categories.natureDesc": "Árboles, océanos y fauna — actúa como experto.",
  "categories.characters": "Personajes", "categories.charactersDesc": "Héroes y villanos — finge que los conoces.",
  "categories.jobs": "Trabajos", "categories.jobsDesc": "De cirujano a streamer — ¡imita o te pillan!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Cine y momentos icónicos — mantente en escena.",
  "categories.brands": "Marcas", "categories.brandsDesc": "Nombres famosos y objetos — ¡encuéntralos o finge!",
  "categories.places": "Lugares", "categories.placesDesc": "Países y ciudades — ¡como si hubieras estado!",
  "categories.animals": "Animales", "categories.animalsDesc": "De mascotas a fieras — ¿puedes camuflarte?",
  "categories.sports": "Deportes", "categories.sportsDesc": "Fan o farsante — no se note.",
  "categories.newyear": "Año Nuevo", "categories.newyearDesc": "Ambiente invernal — ¿quién se porta mal?",
  "gameSettings.title": "Ajustes de partida", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Algunas rondas cambiarán las reglas. ¡Espera lo inesperado!",
  "gameSettings.imposters": "Impostores", "gameSettings.impostersDesc": "¿Cuántos impostores? Para {n} jugadores: {rec}",
  "gameSettings.roundDuration": "Duración de ronda", "gameSettings.roundDurationDesc": "¿Cuánto dura la discusión?",
  "gameSettings.imposterHints": "Pistas para impostores", "gameSettings.imposterHintsDesc": "¿Deben recibir una pista sobre la palabra?",
  "gameSettings.playSummary": "{n} impostor(es)",
  "pass.givePhone": "Pasa el teléfono a {name}", "pass.swipeHint": "Desliza hacia arriba para ver la palabra secreta",
  "pass.imposter": "IMPOSTOR", "pass.hint": "Pista: {hint}",
  "pass.readyTitle": "¡Listos para empezar!", "pass.startGame": "Empezar partida",
  "round.startAsking": "¡Empieza a preguntar!", "round.pause": "Pausa", "round.resume": "Reanudar",
  "round.paused": "En pausa", "round.tapToContinue": "Toca para continuar", "round.vote": "Votar",
  "round.howToTitle": "Cómo jugar",
  "round.howTo1": "¿Sabes la palabra? Da pistas listas sin revelarla.",
  "round.howTo2": "¿Eres el Impostor? Mézclate y adivina con las pistas de los demás.",
  "round.howTo3": "Cuando estéis listos, pausad y votad al impostor.",
  "drawing.starting": "{name} empieza", "drawing.instruction": "Dibuja la pista en un solo trazo y pasa al siguiente",
  "drawing.exitTitle": "¿Salir de la partida?", "drawing.exitBody": "¿Seguro que quieres salir?", "drawing.exitConfirm": "Salir",
  "vote.title": "¿Quién es el Impostor?", "vote.instruction": "Vota a quien creas que finge",
  "vote.ready": "¡Cuando estéis listos, enviad los votos!", "vote.send": "ENVIAR VOTOS",
  "results.title": "Resultados", "results.imposterWins": "¡Gana el Impostor!",
  "results.imposterWinsBody": "El impostor escapó sin ser visto", "results.crewWins": "¡Gana el equipo!",
  "results.crewWinsBody": "¡Encontrasteis al impostor!", "results.imposterGuessed": "¡Gana el Impostor!",
  "results.imposterGuessedBody": "El impostor adivinó la palabra secreta", "results.secretWord": "Palabra secreta",
  "results.playAgain": "JUGAR DE NUEVO", "results.momentOfTruth": "MOMENTO DE LA VERDAD",
  "rate.title": "¡Valora Imposter Party!", "rate.body": "Ponemos el corazón en este juego.",
  "rate.incentive": "Tu reseña nos ayuda a crecer — 5 estrellas", "rate.cta": "Valóranos",
  "support.title": "Mejora tu experiencia de soporte", "support.body": "Se pueden compartir datos limitados de uso con Apple para mejorar el soporte y las compras.",
})

PT = merge(EN, {
  "meta.languageName": "Português", "meta.locale": "pt",
  "common.continue": "Continuar", "common.next": "Seguinte", "common.back": "Voltar",
  "common.close": "Fechar", "common.cancel": "Cancelar", "common.gotIt": "Entendi!",
  "common.play": "JOGAR", "common.skip": "Saltar", "common.settings": "Definições",
  "common.info": "Info", "common.accept": "Aceitar", "common.decline": "Recusar",
  "common.on": "Ligado", "common.off": "Desligado", "common.restore": "Restaurar",
  "common.terms": "Termos", "common.privacy": "Privacidade",
  "onboarding.1.title": "Diversão instantânea em todo o lado!",
  "onboarding.1.body": "Noite de jogos, viagem ou um primeiro encontro estranho — Imposter Party quebra o gelo.",
  "onboarding.1.cta": "Eu topo!",
  "onboarding.2.title": "Quem está a fingir?",
  "onboarding.2.body": "Um de vocês mente. Os outros sabem a palavra. Conseguem apanhar o impostor a tempo?",
  "onboarding.2.cta": "Entendi",
  "onboarding.3.title": "Fala com jeito. Adivinha bem.",
  "onboarding.3.body": "Descreve a palavra secreta sem a dizer. Cuidado — o impostor está a ouvir.",
  "onboarding.3.cta": "Vamos jogar!",
  "tutorial.1.title": "Escolhe temas", "tutorial.1.body": "Escolhe um ou mais temas para o clima da festa.",
  "tutorial.2.title": "Vê o teu papel", "tutorial.2.body": "Todos veem a palavra… exceto o impostor. O objetivo? Misturar-se.",
  "tutorial.3.title": "Dá uma pista", "tutorial.3.body": "Uma pista inteligente: clara para quem sabe, confusa para o impostor.",
  "tutorial.4.title": "Hora de votar", "tutorial.4.body": "Acabou a conversa. Votem para expor o impostor!",
  "tutorial.4.win": "Acertaste — ganharam", "tutorial.4.lose": "Falharam — o Impostor ganha",
  "tutorial.4.warning": "Se o impostor adivinhar a palavra a tempo, ganha de imediato",
  "paywall.title": "Continua para acesso total", "paywall.freeTrial": "Ainda em dúvida? Experimenta grátis",
  "paywall.yearly": "Anual", "paywall.weekly": "Semanal", "paywall.bestDeal": "Melhor oferta",
  "paywall.mostPopular": "Mais popular", "paywall.cancelAnytime": "Cancela quando quiseres",
  "paywall.tryFree": "Experimentar grátis", "paywall.continue": "Continuar",
  "home.classicTitle": "Imposter clássico", "home.classicSubtitle": "Descreve a palavra sem seres apanhado!",
  "home.drawingTitle": "Modo desenho", "home.drawingSubtitle": "Sem palavras — só o teu desenho!",
  "settings.title": "Definições", "settings.language": "Idioma", "settings.contact": "Contactar-nos",
  "settings.privacy": "Privacidade", "settings.terms": "Termos de utilização",
  "settings.vibration": "Vibração", "settings.userId": "ID de utilizador: {id}",
  "players.title": "Adicionar jogadores", "players.placeholder": "Nome do jogador {n}",
  "players.add": "Adicionar jogador", "players.minHint": "Mínimo 3 jogadores", "players.maxHint": "Máximo 15 jogadores",
  "categories.title": "Categorias", "categories.selected": "{n} categoria(s)",
  "categories.party": "Festa", "categories.partyDesc": "Risadas, caos e diversão para qualquer grupo.",
  "categories.football": "Futebol", "categories.footballDesc": "Golos, lendas e botas de ouro — sê adepto!",
  "categories.food": "Comida", "categories.foodDesc": "Temas saborosos — erra e estás perdido!",
  "categories.celebs": "Famosos", "categories.celebsDesc": "Nomes do cinema e da música. Conversa leve!",
  "categories.hobbies": "Hobbies", "categories.hobbiesDesc": "Paixões secretas — inventa ou és apanhado!",
  "categories.family": "Família", "categories.familyDesc": "A família conhece-te — apanham o blefe?",
  "categories.education": "Educação", "categories.educationDesc": "Exames e escola — blefa como se tivesses feito o TPC!",
  "categories.nature": "Natureza", "categories.natureDesc": "Árvores, oceanos e vida selvagem — finge que sabes.",
  "categories.characters": "Personagens", "categories.charactersDesc": "Heróis e vilões — finge que os conheces.",
  "categories.jobs": "Profissões", "categories.jobsDesc": "De cirurgião a streamer — imita ou és apanhado!",
  "categories.hollywood": "Hollywood", "categories.hollywoodDesc": "Filmes e momentos icónicos — mantém-te em cena.",
  "categories.brands": "Marcas", "categories.brandsDesc": "Nomes famosos e objetos — encontra ou finge!",
  "categories.places": "Lugares", "categories.placesDesc": "Países e cidades — como se lá tivesses estado!",
  "categories.animals": "Animais", "categories.animalsDesc": "De animais de estimação a feras — consegues misturar-te?",
  "categories.sports": "Desporto", "categories.sportsDesc": "Fã ou fingidor — não se note.",
  "categories.newyear": "Ano Novo", "categories.newyearDesc": "Ambiente de inverno — quem se porta mal?",
  "gameSettings.title": "Definições do jogo", "gameSettings.mysteryTwist": "Mystery Twist",
  "gameSettings.mysteryTwistDesc": "Algumas rondas viram as regras. Espera o inesperado!",
  "gameSettings.imposters": "Impostores", "gameSettings.impostersDesc": "Quantos impostores? Para {n} jogadores: {rec}",
  "gameSettings.roundDuration": "Duração da ronda", "gameSettings.roundDurationDesc": "Quanto dura a discussão?",
  "gameSettings.imposterHints": "Dicas para impostores", "gameSettings.imposterHintsDesc": "Os impostores devem receber uma dica sobre a palavra?",
  "gameSettings.playSummary": "{n} impostor(es)",
  "pass.givePhone": "Passa o telemóvel a {name}", "pass.swipeHint": "Desliza para cima para ver a palavra secreta",
  "pass.imposter": "IMPOSTOR", "pass.hint": "Dica: {hint}",
  "pass.readyTitle": "Prontos a começar!", "pass.startGame": "Começar o jogo",
  "round.startAsking": "Começa a perguntar!", "round.pause": "Pausa", "round.resume": "Continuar",
  "round.paused": "Em pausa", "round.tapToContinue": "Toca para continuar", "round.vote": "Votar",
  "round.howToTitle": "Como jogar",
  "round.howTo1": "Sabes a palavra? Dá pistas inteligentes sem a revelar.",
  "round.howTo2": "És o Impostor? Mistura-te e adivinha com as pistas dos outros.",
  "round.howTo3": "Quando estiverem prontos, pausem e votem no impostor.",
  "drawing.starting": "{name} começa", "drawing.instruction": "Desenha a dica num só traço e passa ao seguinte",
  "drawing.exitTitle": "Sair do jogo?", "drawing.exitBody": "Tens a certeza que queres sair?", "drawing.exitConfirm": "Sair",
  "vote.title": "Quem é o Impostor?", "vote.instruction": "Vota em quem achas que está a fingir",
  "vote.ready": "Quando estiverem prontos, enviem os votos!", "vote.send": "ENVIAR VOTOS",
  "results.title": "Resultados", "results.imposterWins": "O Impostor ganhou!",
  "results.imposterWinsBody": "O impostor escapou sem ser notado", "results.crewWins": "A equipa ganhou!",
  "results.crewWinsBody": "Encontraram o impostor!", "results.imposterGuessed": "O Impostor ganhou!",
  "results.imposterGuessedBody": "O impostor adivinhou a palavra secreta", "results.secretWord": "Palavra secreta",
  "results.playAgain": "JOGAR DE NOVO", "results.momentOfTruth": "MOMENTO DA VERDADE",
  "rate.title": "Avalia o Imposter Party!", "rate.body": "Pomos o coração neste jogo.",
  "rate.incentive": "A tua avaliação ajuda-nos a crescer — 5 estrelas", "rate.cta": "Avaliar",
  "support.title": "Melhora a experiência de suporte", "support.body": "Dados limitados de uso podem ser partilhados com a Apple para melhorar o suporte e as compras.",
})

print("Writing localization files...")
langs = {
  "en": EN,
  "tr": merge(EN, TR),
  "ru": merge(EN, RU),
  "es": ES,
  "pt": PT,
}

# Write first batch; remaining languages in second write below
for code, data in langs.items():
  path = OUT / f"{code}.json"
  path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
  print(f"  wrote {path.name} ({len(data)} keys)")

print("Batch 1 done")
